# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Blue\InductionerMissile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")

var InheritsFromPreceding: String = "Projectiles\\Blue\\Missile.ets"  # Projectiles\Blue\InductionerMissile.ets:3

# Projectiles\Blue\InductionerMissile.ets:5
func CreateData(Entity) -> void:
	pass

# Projectiles\Blue\InductionerMissile.ets:9
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 11
	TMeshComponent.new().Create(Entity, "Units\\Blue\\MissileTurret\\Missile\\Missile.xml").ApplyLegacySizeFactor()  # 14

# Projectiles\Blue\InductionerMissile.ets:19
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 21
	TPositionerSplineComponent.new().Create(Entity).StartTangent(0.0, 0.0, 2.0).EndTangent(1.0, 0.0, 1.0).BindToSubPosition("missile_launcher", [0, 1])  # 27
	TSoundComponent.new().Create(Entity, "event:/card/blue/unit/inductioner/missile_impact").TriggerOnFree()  # 32
