# Generated by tools/transpile_scripts.py from Scripts\Spells\White\LightPulse.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\White\LightPulse.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiWelaRange, [0], 2.0)  # 5
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [0], 8)  # 6
	Entity.Blackboard.SetValue(C.eiWelaRange, [1], 5.0)  # 8
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [1], 14)  # 9

# Spells\White\LightPulse.ets:12
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 14
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [10]).MustHave([C.upUnit]).MustNotHave([C.upLegendary, C.upSpellImmune])  # 18
	TWelaTargetConstraintEnemiesComponent.new().CreateGrouped(Entity, [10])  # 21
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [11]).MustNotHave([C.upImmuneToStateEffects])  # 24
	TWelaTargetConstraintBooleanComponent.new().CreateGrouped(Entity, [0]).GroupA([10]).GroupB([11]).OperatorAnd()  # 27
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [12]).MustHave([C.upUnit]).MustNotHave([C.upLegendary, C.upNoAutoAttack])  # 34
	TWelaTargetConstraintEnemiesComponent.new().CreateGrouped(Entity, [12])  # 37
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [13]).MustNotHave([C.upImmuneToStateEffects, C.upImmuneToBlinded])  # 40
	TWelaTargetConstraintBooleanComponent.new().CreateGrouped(Entity, [1]).GroupA([12]).GroupB([13]).OperatorAnd()  # 43
	TTextureRangeIndicatorComponent.new().CreateGrouped(Entity, [0]).SetTexture("SpelltargetGeneric.png")  # 49
	TTextureRangeIndicatorComponent.new().CreateGrouped(Entity, [1]).SetTexture("SpelltargetGround.png")  # 51
	TRangeIndicatorHighlightEntitiesComponent.new().CreateGrouped(Entity, [1]).Valid([12]).Invalid([13])  # 53
	TRangeIndicatorHighlightEntitiesComponent.new().CreateGrouped(Entity, [0]).Valid([10]).Invalid([11])  # 56

# Spells\White\LightPulse.ets:62
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 64
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [0], "Modifiers\\Stun.dws")  # 91
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [1], "Modifiers\\Blind.dws")  # 92
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/card/white/spell/light_pulse/cast").TriggerOnCreate()  # 95
	TParticleEffectComponent.new().CreateGrouped(Entity, [1], "\\White\\light_pulse_cast.pfx", 6.0).ActivateOnCreate().ScaleWith(C.eiWelaRange)  # 98
	TCameraShakerComponent.new().CreateGrouped(Entity, []).PresetRotationMedium().ActivateOnFree()  # 102
	TCameraShakerComponent.new().CreateGrouped(Entity, []).PresetVectorMedium().ActivateOnFree()  # 106
	TParticleEffectComponent.new().CreateGrouped(Entity, [1], "\\White\\white_border_wide_once.pfx", 5.0).ActivateOnCreate().FixedOrientationDefault().ScaleWith(C.eiWelaRange).FixedHeightGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 110
