# Generated by tools/transpile_scripts.py from Scripts\Spells\White\ShieldsUp.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\White\ShieldsUp.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiWelaRange, [0], 6.0)  # 5
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [0], 30)  # 6

# Spells\White\ShieldsUp.ets:9
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 11
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [10]).MustHave([C.upUnit]).MustNotHave([C.upBase])  # 14
	TWelaTargetConstraintAlliesComponent.new().CreateGrouped(Entity, [10])  # 17
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [11]).MustNotHave([C.upHasShieldBlock])  # 20
	TWelaTargetConstraintBooleanComponent.new().CreateGrouped(Entity, [0]).GroupA([10]).GroupB([11]).OperatorAnd()  # 23
	TTextureRangeIndicatorComponent.new().CreateGrouped(Entity, [0]).SetTexture("SpelltargetGround.png")  # 29
	TRangeIndicatorHighlightEntitiesComponent.new().CreateGrouped(Entity, [0]).Valid([10]).Invalid([11])  # 31

# Spells\White\ShieldsUp.ets:37
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 39
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [0], "Modifiers\\Shieldblock.dws")  # 56
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/card/white/spell/shields_up/cast").TriggerOnCreate()  # 59
	TParticleEffectComponent.new().CreateGrouped(Entity, [0], "\\White\\shields_up_cast.pfx", 5.0).ActivateOnCreate().ScaleWith(C.eiWelaRange)  # 62
	TCameraShakerComponent.new().CreateGrouped(Entity, []).PresetRotationLight().ActivateOnCreate()  # 66
	TCameraShakerComponent.new().CreateGrouped(Entity, []).PresetVectorLight().ActivateOnCreate()  # 70
	TParticleEffectComponent.new().CreateGrouped(Entity, [0], "\\White\\white_border_wide_once.pfx", 5.0).ActivateOnCreate().FixedOrientationDefault().ScaleWith(C.eiWelaRange).FixedHeightGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 74
