# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Colorless\SiegeGolemProjectile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Colorless\SiegeGolemProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(12) / 1000)  # 5

# Projectiles\Colorless\SiegeGolemProjectile.ets:8
func CreateMeta(Entity) -> void:
	var i: int = 0  # 9
	CreateData(Entity)  # 11
	TParticleEffectComponent.new().Create(Entity, "\\Colorless\\siege_golem_projectile.pfx", 1.0).ActivateOnCreate()  # 14
	TPointLightComponent.new().Create(Entity, 704708607, 5.0)  # 16
	for _for_i in range(0, (3) + 1):  # 18
		i = _for_i
		TPositionerRotationComponent.new().CreateGrouped(Entity, [1 + i]).Radius(0.3).RotationSpeed(0.0, 0.0, (3 + i) * PI).Phase(i * 0.2)  # 20
		TVertexTraceComponent.new().CreateGrouped(Entity, [1 + i]).Texture("Effects\\Textures\\CrystalTrace.tga").Color(813760511).Width(0.25).SamplingDistance(0.5).FadeLength(5.0).MaxLength(7.0).TexturePerDistance(4.0).Additive().IsPiece()  # 24

# Projectiles\Colorless\SiegeGolemProjectile.ets:38
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 40
	TPositionerSplineComponent.new().Create(Entity).OrientStartWithTarget().StartTangent(PI / 4, 0.0, 1.5).EndTangent(PI / 8, 0.0, 1.0).BindToSubPosition(C.BIND_ZONE_WEAPON_MUZZLE, [0, 1])  # 54
	TParticleEffectComponent.new().CreateGrouped(Entity, [0], "\\Colorless\\siege_golem_projectile_impact.pfx", 1.1).ActivateAtFireTarget().ActivateOnFireWarhead()  # 60
	TCameraShakerComponent.new().CreateGrouped(Entity, []).PresetRotationMedium().ActivateOnFree()  # 64
	TCameraShakerComponent.new().CreateGrouped(Entity, []).PresetVectorMedium().ActivateOnFree()  # 68
	TSoundComponent.new().Create(Entity, "event:/card/colorless/unit/siege_golem/crystal_artillery_impact").TriggerOnFree()  # 72
