# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Colorless\SmallRangedGolemProjectile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Colorless\SmallRangedGolemProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(28) / 1000)  # 5

# Projectiles\Colorless\SmallRangedGolemProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10
	TMeshComponent.new().Create(Entity, "Units\\Colorless\\SmallRangedGolem\\SmallRangedGolemProjectile.xml").ApplyLegacySizeFactor()  # 13
	Entity.Eventbus.Write(C.eiModelSize, [0.7])  # 15
	TParticleEffectComponent.new().Create(Entity, "\\Colorless\\small_ranged_golem_projectile.pfx", 1.0).ActivateOnCreate()  # 17
	TVertexTraceComponent.new().CreateGrouped(Entity, []).Color(2158405012).Width(0.3).SamplingDistance(0.5).FadeLength(3.0).MaxLength(4.0).TexturePerDistance(4.0)  # 20

# Projectiles\Colorless\SmallRangedGolemProjectile.ets:30
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 32
	TPositionerSplineComponent.new().Create(Entity).BothTangents(PI / 16, 0.0, 1.0).OrientStartWithTarget().BindToSubPosition(C.BIND_ZONE_WEAPON_MUZZLE, [0, 1])  # 46
	TSoundComponent.new().Create(Entity, "event:/card/colorless/unit/small_ranged_golem/attack_impact").TriggerOnFree()  # 51
