# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Colorless\SplinterProjectile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Colorless\SplinterProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(3) / 1000)  # 5
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [0], "Units\\Golems\\GolemsSmallMeleeGolem")  # 6

# Projectiles\Colorless\SplinterProjectile.ets:9
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 11
	TMeshComponent.new().Create(Entity, "Units\\Colorless\\BigMeleeGolem\\Projectile\\Stone.xml").ApplyLegacySizeFactor()  # 14
	TParticleEffectComponent.new().Create(Entity, "\\Colorless\\splinter_projectile_trail.pfx", 1.0).ActivateOnCreate()  # 17
	TVertexTraceComponent.new().CreateGrouped(Entity, []).Texture("Effects\\Textures\\StoneTrace.tga").Color(2164260863).Width(0.65).SamplingDistance(0.25).FadeLength(3.0).MaxLength(4.0).TexturePerDistance(4.0)  # 20

# Projectiles\Colorless\SplinterProjectile.ets:31
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 33
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [0], "Modifiers\\LegendarySpawn.dws").PassIntValue(500).ApplyToProducedUnits()  # 42
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [0], "Modifiers\\Drop.dws").ApplyToProducedUnits()  # 47
	TOrienterAutoRotationComponent.new().Create(Entity).SetSpeed(Vector3(0.006, 0 * 0.0051, 0 * 0.0084))  # 50
	TPositionerSplineComponent.new().Create(Entity).OrientStartWithTarget().StartTangent(PI / 2.4, 0.0, 4.0).EndTangent(PI / 1.8, 0.0, 2.0).BindToSubPosition(C.BIND_ZONE_CENTER, [0, 1])  # 53
	TSoundComponent.new().Create(Entity, "event:/card/colorless/unit/big_melee_golem/splinter_impact").TriggerOnFree()  # 59
