# Generated by tools/transpile_scripts.py from Scripts\Units\Scenario\BossSiegeGolemAttack.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\BuildingTemplate.dws:3
func InitBuildingData(Entity, LimitedLifeTime: bool = false) -> void:
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 12.0)  # 5
	if LimitedLifeTime:  # 8
		Entity.Blackboard.SetValue(C.eiCooldown, [C.GROUP_BUILDING_LIFETIME], 90000)  # 9
	Entity.Blackboard.SetValue(C.eiWelaRange, [C.GROUP_SOUL], 12.0)  # 11

# HelperScripts\BuildingTemplate.dws:23
func InitBuildingMeta(Entity) -> void:
	pass

# HelperScripts\BuildingTemplate.dws:32
func InitBaseBuildingEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 34
	TStatisticsUnitComponent.new().Create(Entity)  # 37
	TPositionComponent.new().Create(Entity)  # 39
	THealthComponent.new().Create(Entity)  # 40
	TArmorComponent.new().Create(Entity)  # 41
	TThinkImpulseTimerComponent.new().Create(Entity)  # 42
	TBrainActionComponent.new().CreateGroupedAll(Entity)  # 43
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, []).Name("BuildingToBasebuilding").TriggerOnDamageDone().CheckUnitPropertyMustHave([C.upBase])  # 45
	TPathfindingComponent.new().Create(Entity)  # 51

# HelperScripts\BuildingTemplate.dws:57
func InitBuildingEntity(Entity, LimitedLifeTime: bool = false) -> void:
	InitBaseBuildingEntity(Entity)  # 59
	if LimitedLifeTime:  # 62
		TWelaHelperBeaconComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME]).TriggerAt([C.upBuildingLimitedTime])  # 64
		TBrainWelaSelftargetGroundComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME])  # 66
		TWelaEffectSuicideComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME])  # 67
	if LimitedLifeTime:  # 71
		TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], false)  # 72

# Units\Scenario\BossSiegeGolemAttack.ets:3
func CreateData(Entity) -> void:
	InitBuildingData(Entity, false)  # 5
	Entity.CollisionRadius = 2.55  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecColorless)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier3, C.upFlying, C.upBuilding, C.upGround, C.upLegendary, C.upNexus, C.upUnhealable, C.upBase, C.upGolem, C.upSpellImmune])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atFortified)  # 9
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 1200.0)  # 10
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 1200.0)  # 11
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reWelaCharge, 0)  # 13
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reWelaCharge, 8 * 60)  # 14
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 9999999.0)  # 17
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [0, 1], "Projectiles\\Colorless\\BossSiegeGolemAttackProjectile")  # 18
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtIgnoreArmor, C.dtTrue])  # 19
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 0.041667)  # 20
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 5000)  # 21
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 933)  # 22
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 1833)  # 23
	Entity.Blackboard.SetValue(C.eiWelaDamage, [2], 1.0)  # 26
	Entity.Blackboard.SetValue(C.eiWelaDamage, [3], 3.0 * 60.0)  # 29

# Units\Scenario\BossSiegeGolemAttack.ets:44
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 46
	InitBuildingMeta(Entity)  # 47

# Units\Scenario\BossSiegeGolemAttack.ets:65
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 67
	InitBuildingEntity(Entity, false)  # 68
	TServerPrimaryTargetComponent.new().Create(Entity)  # 71
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [1]).Preemptive()  # 74
	TWelaReadyResourceCompareComponent.new().CreateGrouped(Entity, [1]).ComparedResource(C.reWelaCharge).CheckFull()  # 76
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [1], true)  # 79
	TWelaTargetingNexusComponent.new().CreateGrouped(Entity, [1]).SetTargetTeamConstraint(C.tcEnemies)  # 80
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [0, 1], C.eiDamageable)  # 82
	TWelaEffectProjectileComponent.new().CreateGrouped(Entity, [1])  # 83
	TThinkImpulseGameTickComponent.new().CreateGrouped(Entity, [2])  # 86
	TBrainWelaSelftargetComponent.new().CreateGrouped(Entity, [2]).ThinksPassively().ThinksLocal()  # 87
	TWelaReadyResourceCompareComponent.new().CreateGrouped(Entity, [2]).ComparedResource(C.reWelaCharge).CheckNotFull()  # 90
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [2])  # 93
	TWarheadSpottyResourceComponent.new().CreateGrouped(Entity, [2]).SetResourceType(C.reWelaCharge)  # 94
	TAutoBrainOnGameEventComponent.new().CreateGrouped(Entity, [3]).SetEvent("GolemTower_Destroyed")  # 98
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [3])  # 100
	TWarheadSpottyResourceComponent.new().CreateGrouped(Entity, [3]).SetResourceType(C.reWelaCharge).ChangesMax().DontFillCap()  # 101
