# Generated by tools/transpile_scripts.py from Scripts\Units\Scenario\GolemLaneTowerLevel1.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\BuildingTemplate.dws:3
func InitBuildingData(Entity, LimitedLifeTime: bool = false) -> void:
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 12.0)  # 5
	if LimitedLifeTime:  # 8
		Entity.Blackboard.SetValue(C.eiCooldown, [C.GROUP_BUILDING_LIFETIME], 90000)  # 9
	Entity.Blackboard.SetValue(C.eiWelaRange, [C.GROUP_SOUL], 12.0)  # 11

# HelperScripts\BuildingTemplate.dws:23
func InitBuildingMeta(Entity) -> void:
	pass

# HelperScripts\BuildingTemplate.dws:32
func InitBaseBuildingEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 34
	TStatisticsUnitComponent.new().Create(Entity)  # 37
	TPositionComponent.new().Create(Entity)  # 39
	THealthComponent.new().Create(Entity)  # 40
	TArmorComponent.new().Create(Entity)  # 41
	TThinkImpulseTimerComponent.new().Create(Entity)  # 42
	TBrainActionComponent.new().CreateGroupedAll(Entity)  # 43
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, []).Name("BuildingToBasebuilding").TriggerOnDamageDone().CheckUnitPropertyMustHave([C.upBase])  # 45
	TPathfindingComponent.new().Create(Entity)  # 51

# HelperScripts\BuildingTemplate.dws:57
func InitBuildingEntity(Entity, LimitedLifeTime: bool = false) -> void:
	InitBaseBuildingEntity(Entity)  # 59
	if LimitedLifeTime:  # 62
		TWelaHelperBeaconComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME]).TriggerAt([C.upBuildingLimitedTime])  # 64
		TBrainWelaSelftargetGroundComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME])  # 66
		TWelaEffectSuicideComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME])  # 67
	if LimitedLifeTime:  # 71
		TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], false)  # 72

# Units\Scenario\GolemLaneTowerLevel1.ets:3
func CreateData(Entity) -> void:
	InitBuildingData(Entity, false)  # 5
	Entity.CollisionRadius = 0.95  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecColorless)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upMonumental, C.upLanetower, C.upTier1, C.upFlying, C.upGround, C.upRanged, C.upBuilding, C.upBase, C.upGolem])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atFortified)  # 10
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 600.0)  # 11
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 600.0)  # 12
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reMana, 15)  # 14
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reMana, 5)  # 15
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [1], C.reMana, 1)  # 18
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 16.0)  # 19
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [0, 1], "Projectiles\\Colorless\\GolemLaneTowerLevel1Projectile")  # 20
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 1000)  # 21
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtTrue, C.dtRanged])  # 22
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 32.0)  # 23
	Entity.Blackboard.SetValue(C.eiWelaDamage, [5], 1.0)  # 26
	Entity.Blackboard.SetValue(C.eiCooldown, [5], 3000)  # 27

# Units\Scenario\GolemLaneTowerLevel1.ets:43
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 45
	InitBuildingMeta(Entity)  # 46

# Units\Scenario\GolemLaneTowerLevel1.ets:78
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 80
	InitBuildingEntity(Entity, false)  # 81
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [1]).Preemptive()  # 84
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [1], true)  # 86
	TWelaReadyCostComponent.new().CreateGrouped(Entity, [1]).SetPayingGroupForType(C.reMana, [])  # 87
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [1]).SetTargetTeamConstraint(C.tcEnemies)  # 89
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).MustNotHave([C.upInvisible, C.upBanished])  # 91
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [0, 1], C.eiDamageable)  # 93
	TWelaEffectPayCostComponent.new().CreateGrouped(Entity, [1]).SetPayingGroupForType(C.reMana, [])  # 94
	TWelaEffectProjectileComponent.new().CreateGrouped(Entity, [1])  # 96
	TAutoBrainOnDeathComponent.new().CreateGrouped(Entity, [3])  # 98
	TWelaEffectGameEventComponent.new().CreateGrouped(Entity, [3]).Event("GolemTower_Destroyed")  # 99
	TWelaHelperInitActiveAfterGameStartComponent.new().CreateGrouped(Entity, [5])  # 103
	TBrainWelaSelftargetComponent.new().CreateGrouped(Entity, [5]).ThinksPassively()  # 104
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [5], false)  # 106
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [5])  # 107
	TWarheadSpottyResourceComponent.new().CreateGrouped(Entity, [5]).SetResourceType(C.reMana)  # 108
	TGameEventEnumeratorComponent.new().CreateGrouped(Entity, [3]).Event("GolemTower_Destroyed")  # 112
