# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Black\FrostspearProjectile.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Black\FrostspearProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(14) / 1000)  # 5

# Projectiles\Black\FrostspearProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10

# Projectiles\Black\FrostspearProjectile.ets:21
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 23
	TMovementComponent.new().Create(Entity)  # 26
	TBrainProjectileComponent.new().CreateGrouped(Entity, [0])  # 27
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [0])  # 29
	TWarheadSpottyDamageComponent.new().CreateGrouped(Entity, [0])  # 30
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [0]).Name("Frostspear").TriggerOnKillDone()  # 31
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [0]).Name("Spell").TriggerOnDamageDone()  # 34
