# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Black\SoulGatherProjectile.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Black\SoulGatherProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(10) / 1000)  # 5

# Projectiles\Black\SoulGatherProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10

# Projectiles\Black\SoulGatherProjectile.ets:35
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 37
	TMovementComponent.new().Create(Entity)  # 40
	TBrainProjectileComponent.new().CreateGrouped(Entity, [0])  # 41
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [0])  # 42
	TWarheadSpottyResourceComponent.new().CreateGrouped(Entity, [0]).SetResourceType(C.reMana)  # 43
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [0]).Name("SoulGatherer").TriggerOnFire().TakeOwnerFromTarget()  # 45
