# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Black\SoulGatherProjectileSpawner.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Black\SoulGatherProjectileSpawner.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiWelaDamage, [0], 1.0)  # 5
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [0], 1)  # 6
	Entity.Blackboard.SetValue(C.eiWelaRange, [0], 12.0)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [0], "Projectiles\\Black\\SoulGatherProjectile")  # 8

# Projectiles\Black\SoulGatherProjectileSpawner.ets:11
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 13

# Projectiles\Black\SoulGatherProjectileSpawner.ets:19
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 21
	TThinkImpulseOnceComponent.new().CreateGrouped(Entity, [0]).WaitOneFrame()  # 24
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [0])  # 27
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [0]).SetTargetTeamConstraint(C.tcAll).SetTargetTeamConstraintPriority(C.tcAllies).PicksRandomTargets()  # 28
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [0]).MustHave([C.upSoulGatherer])  # 32
	TWelaTargetConstraintResourceComponent.new().CreateGrouped(Entity, [0]).CheckResource(C.reMana).CheckNotFull()  # 34
	TWelaEffectProjectileComponent.new().CreateGrouped(Entity, [0])  # 37
	TWelaEffectSuicideComponent.new().CreateGrouped(Entity, [0])  # 38
