# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Black\VoidWraithProjectile.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Black\VoidWraithProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(18) / 1000)  # 5
	Entity.Blackboard.SetValue(C.eiWelaModifier, [1], 2.0)  # 8
	Entity.Blackboard.SetValue(C.eiWelaModifier, [2], 3.0)  # 9

# Projectiles\Black\VoidWraithProjectile.ets:12
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 14

# Projectiles\Black\VoidWraithProjectile.ets:25
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 27
	TMovementComponent.new().Create(Entity)  # 30
	TBrainProjectileComponent.new().CreateGrouped(Entity, [0])  # 31
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [0])  # 33
	TWarheadSpottyDamageComponent.new().CreateGrouped(Entity, [0])  # 34
	TModifierMultiplyDealtDamageComponent.new().CreateGrouped(Entity, [0]).MustNotHave([C.dtSpell]).CheckWelaConstraint().SetValueGroup([1])  # 37
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [1]).MustHaveAny([C.upStunned, C.upBlinded, C.upRooted, C.upGrounded, C.upLifted, C.upBleeding, C.upPetrified]).MustNotHave([C.upFrozen])  # 41
	TModifierMultiplyDealtDamageComponent.new().CreateGrouped(Entity, [0]).MustNotHave([C.dtSpell]).CheckWelaConstraint().SetValueGroup([2])  # 44
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [2]).MustHave([C.upFrozen])  # 48
