# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Black\VoidCauldronBuildingBlastProjectile.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Black\VoidCauldronBuildingBlastProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(12) / 1000)  # 5

# Projectiles\Black\VoidCauldronBuildingBlastProjectile.ets:8
func CreateMeta(Entity) -> void:
	var i: int = 0  # 9
	CreateData(Entity)  # 11

# Projectiles\Black\VoidCauldronBuildingBlastProjectile.ets:37
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 39
	TMovementComponent.new().Create(Entity)  # 42
	TBrainProjectileComponent.new().CreateGrouped(Entity, [0])  # 43
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [0])  # 45
	TWarheadSpottyDamageComponent.new().CreateGrouped(Entity, [0])  # 46
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [0]).Name("Siege").TriggerOnDamageDone()  # 47
