# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Black\VoidGatherProjectile.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Black\VoidGatherProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(10) / 1000)  # 5

# Projectiles\Black\VoidGatherProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10

# Projectiles\Black\VoidGatherProjectile.ets:34
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 36
	TMovementComponent.new().Create(Entity)  # 39
	TBrainProjectileComponent.new().CreateGrouped(Entity, [0])  # 40
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [0])  # 41
	TWarheadSpottyResourceComponent.new().CreateGrouped(Entity, [0]).SetResourceType(C.reMana)  # 42
