# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Green\HeartOfTheForestProjectile.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Green\HeartOfTheForestProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(14) / 1000)  # 5

# Projectiles\Green\HeartOfTheForestProjectile.ets:8
func CreateMeta(Entity) -> void:
	var i: int = 0  # 9
	CreateData(Entity)  # 11

# Projectiles\Green\HeartOfTheForestProjectile.ets:43
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 45
	TMovementComponent.new().Create(Entity)  # 48
	TBrainProjectileComponent.new().CreateGrouped(Entity, [0])  # 49
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [0])  # 50
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [0], "Modifiers\\BlessingStrength.dws")  # 53
