# Generated by tools/transpile_scripts.py from Scripts\Spells\Black\Frostspear.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\Black\Frostspear.dws:1
func Apply(Entity) -> void:
	var Group: int = 0  # 2
	var FinishGroup: int = 0  # 2
	Group = Entity.ReserveFreeGroup()  # 4
	FinishGroup = Entity.ReserveFreeGroup()  # 5
	Entity.Blackboard.SetValue(C.eiCooldown, [Group], 100)  # 6
	Entity.Blackboard.SetValue(C.eiWelaDamage, [Group], 10.0)  # 7
	Entity.Blackboard.SetValue(C.eiWelaRange, [Group], 6.0)  # 8
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [Group], "Projectiles\\Black\\FrostspearProjectile")  # 9
	Entity.Blackboard.SetValue(C.eiDamageType, [Group], [C.dtSpell])  # 10
	TSoundComponent.new().CreateGrouped(Entity, [Group], "event:/card/black/spell/frostspear/attack_fire").TriggerOnFire()  # 39
