# Generated by tools/transpile_scripts.py from Scripts\Spells\Black\PermaFrost.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\Black\PermaFrost.dws:1
func Apply(Entity, SameTeam: bool) -> void:
	var Group: int = 0  # 2
	var ArmorGroup: int = 0  # 2
	Group = Entity.ReserveFreeGroup()  # 4
	ArmorGroup = Entity.ReserveFreeGroup()  # 5
	Entity.Blackboard.SetValue(C.eiWelaDamage, [Group], 300.0)  # 6
	if not SameTeam:  # 8
		Entity.Blackboard.SetValue(C.eiWelaModifier, [Group], -1.0)  # 9
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upBlessed, C.upBlessedHardening])  # 26
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [ArmorGroup]).MustHave([C.upFrozen])  # 28
	TModifierArmorTypeComponent.new().CreateGrouped(Entity, [ArmorGroup]).SetTo(C.atHeavy).ReadyGroup([ArmorGroup])  # 30
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\Black\\blessed_hardening_buff.pfx", 1.0).ActivateNow().ActivateOnCreate().ScaleWith(C.eiCollisionRadius)  # 35
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\Black\\permafrost_cast.pfx", 1.5).ActivateNow().ScaleWith(C.eiCollisionRadius)  # 40
	TParticleEffectComponent.new().CreateGrouped(Entity, [ArmorGroup], "\\Black\\permafrost_buff.pfx", 0.6).ActivateNow().ActivateOnCreate().ScaleWith(C.eiCollisionRadius).BindToSubPositionGroup(C.BIND_ZONE_CENTER, [0, 1]).VisibleWithUnitPropertyMustHave([C.upFrozen])  # 44
