# Generated by tools/transpile_scripts.py from Scripts\Spells\Black\RipOutSoul.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\Black\RipOutSoul.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiCooldown, [0], 500)  # 5
	Entity.Blackboard.SetValue(C.eiWelaRange, [0], 5.5)  # 7
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [0], 20)  # 8
	Entity.Blackboard.SetValue(C.eiWelaDamage, [0], 0.30)  # 9
	Entity.Blackboard.SetValue(C.eiDamageType, [0], [C.dtSpell, C.dtSplash])  # 10

# Spells\Black\RipOutSoul.ets:13
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 15
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [10]).MustHave([C.upUnit]).MustNotHave([C.upLegendary, C.upSpellImmune])  # 18
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [11], C.eiDamageable)  # 23
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [11]).MustNotHave([C.upImmuneToBanished, C.upImmuneToStateEffects])  # 24
	TWelaTargetConstraintBooleanComponent.new().CreateGrouped(Entity, [0]).GroupA([10]).GroupB([11]).OperatorAnd()  # 27
	TTextureRangeIndicatorComponent.new().CreateGrouped(Entity, [0]).SetTexture("SpelltargetGround.png")  # 33
	TRangeIndicatorHighlightEntitiesComponent.new().CreateGrouped(Entity, [0]).Valid([10]).Invalid([11])  # 35

# Spells\Black\RipOutSoul.ets:41
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 43
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [0], "Modifiers\\Banished.dws")  # 78
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/card/black/spell/rip_out_soul/cast").TriggerOnCreate()  # 81
	TParticleEffectComponent.new().CreateGrouped(Entity, [0], "\\Black\\rip_out_soul_cast.pfx", 5.0).ActivateOnCreate().ScaleWith(C.eiWelaRange)  # 84
	TCameraShakerComponent.new().CreateGrouped(Entity, []).Delay(500).PresetRotationMedium().ActivateOnCreate()  # 88
	TCameraShakerComponent.new().CreateGrouped(Entity, []).Delay(500).PresetVectorMedium().ActivateOnCreate()  # 93
	TParticleEffectComponent.new().CreateGrouped(Entity, [0], "\\Black\\rip_out_soul_fire.pfx", 1.0).ActivateOnFire().ActivateAtFireTarget()  # 98
	TParticleEffectComponent.new().CreateGrouped(Entity, [0], "\\Black\\black_border_wide_once.pfx", 5.0).ActivateOnCreate().FixedOrientationDefault().ScaleWith(C.eiWelaRange).FixedHeightGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 102
