# Generated by tools/transpile_scripts.py from Scripts\Scenarios\Mutators\Gigantic.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Scenarios\Mutators\Gigantic.dws:3
func Apply(Entity, Game) -> void:
	var EffectGroup: int = 0  # 4
	EffectGroup = Entity.ReserveFreeGroup()  # 6
	Entity.Blackboard.SetValue(C.eiWelaChance, [EffectGroup], 0.20)  # 8
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [EffectGroup], "Scenarios\\Mutators\\GiganticBuff.dws")  # 18
