# Generated by tools/transpile_scripts.py from Scripts\Units\Golems\GolemsBossGolem.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 12
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapUnitIcon.png")  # 13

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TPathfindingComponent.new().Create(Entity)  # 45
	TOrienterMovementComponent.new().Create(Entity)  # 48
	TOrienterTargetComponent.new().CreateGrouped(Entity, [0, 1])  # 49
	TOrienterSmoothRotateComponent.new().Create(Entity).SetAngleSpeed(0.008)  # 50
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 53
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 54
	TShowOnMinimapComponent.new().Create(Entity)  # 56

# Units\Golems\GolemsBossGolem.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 1.5  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecColorless)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upFlying, C.upGround, C.upMonumental, C.upUnit, C.upMelee, C.upLegendary, C.upTier3, C.upGolem])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atFortified)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 1900.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 1900.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetValue(C.eiWelaRange, [1, 2], 0.5 + 1.0)  # 14 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiDamageType, [1, 2], [C.dtMelee, C.dtSplash])  # 15
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1, 2], 370.0)  # 16 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiCooldown, [1, 2], 2800)  # 17 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [1, 2], 5.0)  # 18
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffectCone, [1, 2], 3.141 * 0.9)  # 19
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 1600)  # 20
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 2533)  # 21
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [2], 1166)  # 24
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [2], 2333)  # 25
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [3], 4.5)  # 28
	Entity.Blackboard.SetValue(C.eiWelaDamage, [3], 100.0)  # 29
	Entity.Blackboard.SetValue(C.eiDamageType, [3], [C.dtAbility, C.dtSplash])  # 30
	Entity.Blackboard.SetValue(C.eiCooldown, [3], 500)  # 31
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [], "Legendary")  # 34
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [], "Monumental")  # 35
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "Splash")  # 36
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [3], "DebutAsteroid").PassInteger("damage_amount", 100, "damage")  # 37

# Units\Golems\GolemsBossGolem.ets:42
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 44
	InitUnitMeta(Entity)  # 45
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(0, 0, 0), Vector3(0, 4, 0), 2.0)  # 48
	TMeshComponent.new().CreateGrouped(Entity, [0, 1], ("Units\\Colorless\\BossGolem" + Entity.SkinFileSuffix()) + "\\BossGolem.xml").ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_WALK, 233, 289).CreateNewAnimation(C.ANIMATION_ATTACK, 81, 156).CreateNewAnimation(C.ANIMATION_ATTACK2, 157, 232).CreateNewAnimation(C.ANIMATION_ATTACK_AIR, 290, 359).CreateNewAnimation(C.ANIMATION_ATTACK_AIR2, 360, 429).CreateNewAnimation(C.ANIMATION_STAND, 0, 79).IgnoreScalingForAnimations().BindZoneToBone(C.BIND_ZONE_WEAPON, "BossGolemRPalm").BindZoneToBone(C.BIND_ZONE_CENTER, "BossGolemRibcage").BindZoneToBone(C.BIND_ZONE_HEAD, "BossGolemHead")  # 50
	if Entity.SkinID == C.SKIN_GROUP_TOURNAMENT:  # 63
		TMeshEffectMetal.new().Create().ShowAsColor(C.ecWhite).AssignToEntity(Entity)  # 65
	TAnimationComponent.new().CreateGrouped(Entity, [0, 1, 2]).HasAntiAirAttack().AlternatingAttack()  # 70
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [1.3], [0])  # 73

# Units\Golems\GolemsBossGolem.ets:77
func CreateEntity(Entity) -> void:
	var PositionX: Array = []  # 78
	var PositionY: Array = []  # 78
	var PositionZ: Array = []  # 78
	var Time: Array = []  # 79
	var i: int = 0  # 80
	var color: int = 0  # 81
	CreateMeta(Entity)  # 83
	InitUnitEntity(Entity)  # 84
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [], "Modifiers\\LegendarySpawn.dws").PassIntValue(1600).ApplyToSelfAtCreate()  # 141
	TUnitPropertyComponent.new().CreateGrouped(Entity, [], [C.upHasLegendaryUnit]).GivePropertyOwner()  # 145
	TSoundComponent.new().CreateGrouped(Entity, [1, 2], "event:/card/colorless/unit/boss_golem/attack_fire").TriggerOnPreFire().StopOnFree()  # 149
	TAnimatorComponent.new().CreateGrouped(Entity, [0, 1]).Duration(1500).HideUntil(1400).SizeKeypoints([0.0, 0.0, 1.0]).SizeTimes([0, 1300, 1500])  # 155
	TMeshEffectComponent.new().CreateGrouped(Entity, []).TargetGroup([0, 1]).SetEffect(TMeshEffectGlow.new().Create(2000).AddKey(0, 0.1).AddKey(1300, 0.2).AddKey(1500, 0.1).AddKey(2000, 0.0))  # 161
	PositionX = [20.0, 0.0, 0.0]  # 171
	PositionY = [100.0, 0.8, 0.8]  # 172
	PositionZ = [-20.0, 0.0, 0.0]  # 173
	Time = [0, 350, 800]  # 174
	for _for_i in range(1, (60) + 1):  # 176
		i = _for_i
		PositionX = PositionX + [L.Random() * sin(PI * (1 - ((0.4 * i) / 60)))]  # 178
		PositionY = PositionY + [0.8 + (L.Random() * sin(PI * (1 - ((0.4 * i) / 60))))]  # 179
		PositionZ = PositionZ + [L.Random() * sin(PI * (1 - ((0.4 * i) / 60)))]  # 180
		Time = Time + [800 + (i * 10)]  # 181
	TAnimatorComponent.new().CreateGrouped(Entity, [9]).Duration(1500).HideAfter(1400).PositionKeypointsX(PositionX).PositionKeypointsY(PositionY).PositionKeypointsZ(PositionZ).PositionTimes(Time).FreeGroupAfter()  # 185
	TMeshComponent.new().CreateGrouped(Entity, [9], ("Units\\Colorless\\BossGolem" + Entity.SkinFileSuffix()) + "\\Asteroid\\Stone.xml").ApplyLegacySizeFactor().FixedOrientationAngle(PI / 4, ((-PI) * 1.3) / 4, 0.0).IsPiece()  # 194
	if Entity.SkinID == C.SKIN_GROUP_TOURNAMENT:  # 199
		TMeshEffectMetal.new().Create().ShowAsColor(C.ecWhite).AssignToEntity(Entity)  # 201
	if Entity.SkinID == C.SKIN_GROUP_INFLAMED:  # 206
		color = 4290264614  # 208
		TMeshEffectComponent.new().CreateGrouped(Entity, []).TargetGroup([9]).SetEffect(TMeshEffectGlow.new().Create(2000).FixedColorIdentity(C.ecRed).AddKey(0, 0.0).AddKey(800, 0.0).AddKey(1400, 0.2))  # 209
	else:
		color = 2164260863  # 221
		TMeshEffectComponent.new().CreateGrouped(Entity, []).TargetGroup([9]).SetEffect(TMeshEffectGlow.new().Create(2000).AddKey(0, 0.0).AddKey(800, 0.0).AddKey(1400, 0.2))  # 222
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [5.0], [9])  # 232
	TVertexTraceComponent.new().CreateGrouped(Entity, [9]).Texture("Effects\\Textures\\StoneTrace.tga").Color(color).Width(0.85).SamplingDistance(0.5).FadeLength(20.0).MaxLength(24.0).TexturePerDistance(4.0).FadeWidening(-0.1).RollUpSpeed(44.0).DeactivateAfterTime(1000).Additive().BindToSubPositionGroup(C.BIND_ZONE_CENTER, [9])  # 234
	TParticleEffectComponent.new().CreateGrouped(Entity, [9], ("\\Colorless\\boss_golem" + Entity.SkinFileSuffix()) + "_spawn_trail.pfx", 7.0).ActivateOnCreate().Delay(50).BindToSubPositionGroup(C.BIND_ZONE_CENTER, [9])  # 248
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/card/colorless/unit/boss_golem/spawn").TriggerOnCreate()  # 253
	TParticleEffectComponent.new().CreateGrouped(Entity, [9], ("\\Colorless\\boss_golem" + Entity.SkinFileSuffix()) + "_spawn.pfx", 1.0).ActivateOnCreate().Delay(1300).IgnoreModelSize().IgnoreSize()  # 256
	TParticleEffectComponent.new().CreateGrouped(Entity, [3], ("\\Colorless\\boss_golem" + Entity.SkinFileSuffix()) + "_spawn_impact.pfx", 4.0).ActivateOnCreate().Delay(310).ScaleWith(C.eiWelaAreaOfEffect).IgnoreSize()  # 262
	TParticleEffectComponent.new().CreateGrouped(Entity, [3], "\\Colorless\\colorless_border_wide_once.pfx", 5.0).ActivateOnCreate().Delay(350).FixedOrientationDefault().ScaleWith(C.eiWelaAreaOfEffect).FixedHeightGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 268
	TCameraShakerComponent.new().Create(Entity).VectorShaker(0.0, -1.0, 0.0).Strength(1.1).Duration(700).Waves(5).ActivateOnCreate().Delay(350)  # 276
	TCameraShakerComponent.new().Create(Entity).RotationShaker(0.0, 0.0, 0.01).Strength(1.1).Duration(400).Waves(2).ActivateOnCreate().Delay(350)  # 284
