# Generated by tools/transpile_scripts.py from Scripts\Units\Golems\GolemsSiegeGolem.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 12
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapUnitIcon.png")  # 13

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TPathfindingComponent.new().Create(Entity)  # 45
	TOrienterMovementComponent.new().Create(Entity)  # 48
	TOrienterTargetComponent.new().CreateGrouped(Entity, [0, 1])  # 49
	TOrienterSmoothRotateComponent.new().Create(Entity).SetAngleSpeed(0.008)  # 50
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 53
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 54
	TShowOnMinimapComponent.new().Create(Entity)  # 56

# Units\Golems\GolemsSiegeGolem.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.9  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecColorless)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier2, C.upUnit, C.upGround, C.upMelee, C.upGolem])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atMedium)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 270.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 270.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reWelaCharge, 0)  # 13
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reWelaCharge, 16)  # 14
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [1], C.reWelaCharge, 1)  # 17
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtMelee, C.dtSiege])  # 18
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 68.0)  # 19 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiWelaRange, [1], 0.5 + 1.0)  # 20 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 2300)  # 21 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 633)  # 22
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 1033)  # 23
	Entity.Blackboard.SetValue(C.eiWelaRange, [2], 20.0)  # 26
	Entity.Blackboard.SetValue(C.eiWelaDamage, [2], 1.0)  # 27
	Entity.Blackboard.SetValue(C.eiCooldown, [2], 500)  # 28
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [3], C.reWelaCharge, 16)  # 31
	Entity.Blackboard.SetValue(C.eiWelaRange, [3], 21.0)  # 32
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [3], "Projectiles\\Colorless\\SiegeGolemProjectile")  # 33
	Entity.Blackboard.SetValue(C.eiDamageType, [3], [C.dtRanged, C.dtSiege])  # 34
	Entity.Blackboard.SetValue(C.eiWelaDamage, [3], 50.0)  # 35
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [3], 250)  # 36
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [3], 833)  # 37
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [4], C.reWelaCharge, 1)  # 40
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "Siege")  # 43
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [2], "CrystalArtillery").PassInteger("damage_amount", 50, "damage").PassInteger("charge_duration", 8)  # 44
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaAttack, 2)  # 48
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaDefense, 5)  # 49
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaUtility, 3)  # 50

# Units\Golems\GolemsSiegeGolem.ets:54
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 56
	InitUnitMeta(Entity)  # 57
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(0, 0, 0.1), Vector3(0, 0.9, 0.1), 1.3)  # 60
	TMeshComponent.new().CreateGrouped(Entity, [0, 1], "Units\\Colorless\\SiegeGolem\\SiegeGolem.xml").ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_STAND, 19, 79).CreateNewAnimation(C.ANIMATION_ATTACK, 206, 236).CreateNewAnimation(C.ANIMATION_ATTACK2, 181, 205).CreateNewAnimation(C.ANIMATION_WALK, 0, 18).IgnoreScalingForAnimations().BindZoneToBone(C.BIND_ZONE_WEAPON, "SiegeGolemPelvis").BindZoneToBone(C.BIND_ZONE_WEAPON_MUZZLE, "SiegeGolemPelvis").BoneSwapXZ(C.BIND_ZONE_WEAPON_MUZZLE)  # 62
	TOrienterTargetComponent.new().CreateGrouped(Entity, [0, 1, 2, 3])  # 73
	TAnimationComponent.new().CreateGrouped(Entity, [0, 1, 3]).SecondAttackGroup([3])  # 75
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [1.3], [0])  # 77
	TMeshComponent.new().CreateGrouped(Entity, [2], "Units\\Colorless\\SharedCrystal\\Crystal.xml").IgnoreScalingForAnimations().ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_STAND, 0, 100).FixedOrientationDefault().BindToSubPositionGroup("BoneC", [0, 1])  # 79
	TMeshEffectComponent.new().CreateGrouped(Entity, [2]).SetEffect(TMeshEffectMatcap.new().Create().SetTexture(C.PATH_GRAPHICS_EFFECTS_TEXTURES + "MatcapCrystalNeutral.png"))  # 86
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [1.7], [2])  # 92

# Units\Golems\GolemsSiegeGolem.ets:96
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 98
	InitUnitEntity(Entity)  # 99
	TResourceDisplayProgressBarComponent.new().Create(Entity).ShowResource(C.reWelaCharge).HideIfEmpty()  # 169
	TSoundComponent.new().CreateGrouped(Entity, [1], "event:/card/colorless/unit/siege_golem/attack_fire").TriggerOnPreFire().StopOnFree()  # 173
	TParticleEffectComponent.new().CreateGrouped(Entity, [2], "\\Colorless\\siege_golem_artillery_charge.pfx", 1.5).ActivateOnFire().BindToSubPositionGroup(C.BIND_ZONE_WEAPON_MUZZLE, [0, 1])  # 177
	TSoundComponent.new().CreateGrouped(Entity, [1, 2, 3, 4], "event:/card/colorless/unit/siege_golem/crystal_artillery_charge").IsLoop().TriggerOnFire().StopGroup([1, 3, 4]).StopOnFire().StopOnFree()  # 181
	TParticleEffectComponent.new().CreateGrouped(Entity, [3], "\\Colorless\\siege_golem_artillery_cast.pfx", 1.0).ActivateOnFire().BindToSubPositionGroup(C.BIND_ZONE_WEAPON_MUZZLE, [0, 1])  # 188
	TCameraShakerComponent.new().CreateGrouped(Entity, [3]).PresetRotationLight().ActivateOnFire()  # 192
	TCameraShakerComponent.new().CreateGrouped(Entity, [3]).PresetVectorLight().ActivateOnFire()  # 196
	TSoundComponent.new().CreateGrouped(Entity, [3], "event:/card/colorless/unit/siege_golem/crystal_artillery_fire").TriggerOnFire()  # 200
