# Generated by tools/transpile_scripts.py from Scripts\Units\Golems\GolemsMeleeGolemTower.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\BuildingTemplate.dws:3
func InitBuildingData(Entity, LimitedLifeTime: bool = false) -> void:
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 12.0)  # 5
	if LimitedLifeTime:  # 8
		Entity.Blackboard.SetValue(C.eiCooldown, [C.GROUP_BUILDING_LIFETIME], 90000)  # 9
	Entity.Blackboard.SetValue(C.eiWelaRange, [C.GROUP_SOUL], 12.0)  # 11
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 14
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapBuildingIcon.png")  # 15
	if LimitedLifeTime:  # 17
		TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], "TimedLifeBuilding").PassInteger("duration", 90)  # 18

# HelperScripts\BuildingTemplate.dws:23
func InitBuildingMeta(Entity) -> void:
	pass

# HelperScripts\BuildingTemplate.dws:32
func InitBaseBuildingEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 34
	TPathfindingComponent.new().Create(Entity)  # 51

# HelperScripts\BuildingTemplate.dws:57
func InitBuildingEntity(Entity, LimitedLifeTime: bool = false) -> void:
	InitBaseBuildingEntity(Entity)  # 59
	if LimitedLifeTime:  # 71
		TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], false)  # 72
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 75
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 76
	TShowOnMinimapComponent.new().Create(Entity)  # 78
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/env/building/shared/hit").TriggerOnLoseHealth()  # 79
	if LimitedLifeTime:  # 82
		TIndicatorCooldownCircleComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME]).SetTexture(C.PATH_GRAPHICS_EFFECTS_TEXTURES + "ProgressCircle.tga").SetRadius(1.5).ScaleWith(C.eiCollisionRadius).SetThickness(0.1).SetLinearBlend().Color(1627389951).Invert()  # 84

# Units\Golems\GolemsMeleeGolemTower.ets:3
func CreateData(Entity) -> void:
	InitBuildingData(Entity, true)  # 5
	Entity.CollisionRadius = 0.75  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecColorless)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier2, C.upGround, C.upBuilding, C.upMelee, C.upGolem])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atFortified)  # 10 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 770.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 770.0)  # 12 {@UBL_Health}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtMelee])  # 15
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 110.0)  # 16 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 666)  # 17
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 1033)  # 18
	Entity.Blackboard.SetValue(C.eiWelaRange, [1, 2], 0.5 + 1.0)  # 20 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiCooldown, [1, 2], 1700)  # 21 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiDamageType, [2], [C.dtMelee, C.dtSplash])  # 23
	Entity.Blackboard.SetValue(C.eiWelaDamage, [2], 0.333 * 110.0)  # 24 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [2], 2.0)  # 25
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffectCone, [2], 3.141)  # 26
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [2], 466)  # 27
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [2], 866)  # 28
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHealthbarOffset, -1.0)  # 31
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [2], "Wipe").PassInteger("health_threshold", 200, "health").PassPercentage("damage_reduction_percentage", 66, "damage")  # 33
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaAttack, 2)  # 37
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaDefense, 5)  # 38
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaUtility, 3)  # 39

# Units\Golems\GolemsMeleeGolemTower.ets:43
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 45
	InitBuildingMeta(Entity)  # 46
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(-0.3, 0, -0.1), Vector3(-0.3, 2.5, -0.1), 1.2)  # 52
	TMeshComponent.new().CreateGrouped(Entity, [0, 1], "Units\\Colorless\\MeleeGolemTower\\MeleeGolemTower.xml").ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_ATTACK, 87, 117).CreateNewAnimation(C.ANIMATION_ATTACK2, 61, 86).CreateNewAnimation(C.ANIMATION_STAND, 0, 60).BindZoneToBone(C.BIND_ZONE_CENTER, "MeleeGolemTowerPelvis").BindZoneToBone(C.BIND_ZONE_HEAD, "MeleeGolemTowerHead").BindZoneToBone(C.BIND_ZONE_WEAPON, "MeleeGolemTowerLDigit31")  # 54
	TAnimationComponent.new().CreateGrouped(Entity, [0, 1, 2]).SecondAttackGroup([2])  # 63
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [0.55], [0])  # 65
	TTextureRangeIndicatorComponent.new().CreateGrouped(Entity, [1]).SetTexture("SpelltargetShootingRange.png").ShowWeaponRange()  # 67

# Units\Golems\GolemsMeleeGolemTower.ets:73
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 75
	InitBuildingEntity(Entity, true)  # 76
	TSoundComponent.new().CreateGrouped(Entity, [1], "event:/card/colorless/building/melee_golem_tower/attack_fire").TriggerOnPreFire().StopOnFree()  # 116
	TSoundComponent.new().CreateGrouped(Entity, [2], "event:/card/colorless/building/melee_golem_tower/wipe_fire").TriggerOnPreFire().StopOnFree()  # 120
	TOrienterTargetComponent.new().CreateGrouped(Entity, [1, 2])  # 124
