# Generated by tools/transpile_scripts.py from Scripts\Units\Golems\GolemsBigGolemTower.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\BuildingTemplate.dws:3
func InitBuildingData(Entity, LimitedLifeTime: bool = false) -> void:
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 12.0)  # 5
	if LimitedLifeTime:  # 8
		Entity.Blackboard.SetValue(C.eiCooldown, [C.GROUP_BUILDING_LIFETIME], 90000)  # 9
	Entity.Blackboard.SetValue(C.eiWelaRange, [C.GROUP_SOUL], 12.0)  # 11
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 14
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapBuildingIcon.png")  # 15
	if LimitedLifeTime:  # 17
		TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], "TimedLifeBuilding").PassInteger("duration", 90)  # 18

# HelperScripts\BuildingTemplate.dws:23
func InitBuildingMeta(Entity) -> void:
	pass

# HelperScripts\BuildingTemplate.dws:32
func InitBaseBuildingEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 34
	TPathfindingComponent.new().Create(Entity)  # 51

# HelperScripts\BuildingTemplate.dws:57
func InitBuildingEntity(Entity, LimitedLifeTime: bool = false) -> void:
	InitBaseBuildingEntity(Entity)  # 59
	if LimitedLifeTime:  # 71
		TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], false)  # 72
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 75
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 76
	TShowOnMinimapComponent.new().Create(Entity)  # 78
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/env/building/shared/hit").TriggerOnLoseHealth()  # 79
	if LimitedLifeTime:  # 82
		TIndicatorCooldownCircleComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME]).SetTexture(C.PATH_GRAPHICS_EFFECTS_TEXTURES + "ProgressCircle.tga").SetRadius(1.5).ScaleWith(C.eiCollisionRadius).SetThickness(0.1).SetLinearBlend().Color(1627389951).Invert()  # 84

# Units\Golems\GolemsBigGolemTower.ets:3
func CreateData(Entity) -> void:
	InitBuildingData(Entity, true)  # 5
	Entity.CollisionRadius = 0.85  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecColorless)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier3, C.upGround, C.upBuilding, C.upRanged, C.upGolem])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atFortified)  # 10 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 570.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 570.0)  # 12 {@UBL_Health}
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 11.0)  # 15 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [1], 2)  # 16
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [0, 1], "Projectiles\\Colorless\\BigGolemTowerProjectile")  # 17
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 1700)  # 18 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtRanged])  # 19
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 68.0)  # 20 {@UBL_Damage}
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "MultiShot2").PassInteger("target_count", 2)  # 23
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaAttack, 3)  # 26
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaDefense, 7)  # 27
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaUtility, 0)  # 28

# Units\Golems\GolemsBigGolemTower.ets:32
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 34
	InitBuildingMeta(Entity)  # 35
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(0, 0, 0), Vector3(0, 3.0, 0), 0.95)  # 38
	TMeshComponent.new().CreateGrouped(Entity, [0, 1], "Units\\Colorless\\BigGolemTower\\BigGolemTower.xml").ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_STAND, 0, 100).BoneOffset(C.BIND_ZONE_TOP, 0.0, 0.9, -0.1).BindZoneToBone(C.BIND_ZONE_HEAD, "head").BoneOffset(C.BIND_ZONE_HEAD, 0.0, 1.5, 0.0).BindZoneToBone(C.BIND_ZONE_WEAPON, "BoneC").BindZoneToBone(C.BIND_ZONE_WEAPON_MUZZLE, "BoneC")  # 40
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [0.6], [0])  # 49
	TMeshComponent.new().CreateGrouped(Entity, [2], "Units\\Colorless\\SharedCrystal\\Crystal.xml").IgnoreScalingForAnimations().ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_STAND, 0, 100).FixedOrientationDefault().BindToSubPositionGroup("BoneC", [0, 1])  # 51
	TMeshEffectComponent.new().CreateGrouped(Entity, [2]).SetEffect(TMeshEffectMatcap.new().Create().SetTexture(C.PATH_GRAPHICS_EFFECTS_TEXTURES + "MatcapCrystalNeutral.png"))  # 58
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [1.7], [2])  # 64
	TTextureRangeIndicatorComponent.new().CreateGrouped(Entity, [1]).SetTexture("SpelltargetShootingRange.png")  # 66

# Units\Golems\GolemsBigGolemTower.ets:71
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 73
	InitBuildingEntity(Entity, true)  # 74
	TParticleEffectComponent.new().CreateGrouped(Entity, [1], "\\Colorless\\big_golem_tower_attack.pfx", 0.4).ActivateOnFire().BindToSubPositionGroup(C.BIND_ZONE_WEAPON_MUZZLE, [0, 1])  # 89
	TSoundComponent.new().CreateGrouped(Entity, [1], "event:/card/colorless/building/big_golem_tower/attack_fire").TriggerOnFire()  # 93
