# Generated by tools/transpile_scripts.py from Scripts\Scenarios\AttackDuoScenarioMedium.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Scenarios\AttackDuoScenarioMedium.dws:3
func Apply(Entity, Game) -> void:
	var ScenarioDirector = null  # 6
	ScenarioDirector = Game.ScenarioDirector  # 10
	ScenarioDirector.EnableMirroring()  # 12
	ScenarioDirector.SpawnUnit(-48.0, -23.0, "Units\\Scenario\\GolemLaneTowerLevel1_WithLaneNode.ets")  # 14
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(-52.07, -22.78, "Units\\Colorless\\MeleeGolemTower.ets")  # 15
	ScenarioDirector.SpawnGuards(-53, -23, ["SmallMeleeGolem", "SmallFlyingGolem", "SmallFlyingGolem"], [], 0)  # 16
	ScenarioDirector.SpawnUnit(0.0, -23.0, "Units\\Scenario\\GolemLaneTowerLevel1_WithLaneNode.ets")  # 19
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(-2.0, -22.78, "Units\\Colorless\\MeleeGolemTower.ets")  # 20
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(-2.0, -28.94, "Units\\Colorless\\SmallGolemTower.ets")  # 21
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(-2.0, -18.46, "Units\\Colorless\\SmallGolemTower.ets")  # 22
	ScenarioDirector.SpawnGuards(-5, -23, ["MediumMeleeGolem"], ["SmallMeleeGolem", "SmallRangedGolem", "SmallFlyingGolem"], 600)  # 23
	ScenarioDirector.SpawnUnit(48.0, -23.0, "\\Units\\Scenario\\GolemLaneTowerLevel2_WithLaneNode.ets")  # 26
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(44.00, -19.63, "\\Units\\Colorless\\MeleeGolemTower.ets")  # 27
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(44.00, -26.88, "\\Units\\Colorless\\MeleeGolemTower.ets")  # 28
	ScenarioDirector.SpawnGuards(43, -23, ["MediumMeleeGolem", "MediumMeleeGolem", "SmallRangedGolem"], ["SmallMeleeGolem", "MediumMeleeGolem", "SmallRangedGolem", "SmallFlyingGolem"], 700)  # 29
	ScenarioDirector.DisableMirroring()  # 32
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(76.00, 0.0, "Units\\Colorless\\BigGolemTower.ets")  # 35
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(80.00, 0.0, "Units\\Colorless\\BigGolemTower.ets")  # 36
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(78.00, -2.0, "Units\\Colorless\\SmallGolemTower.ets")  # 37
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(78.00, 2.0, "Units\\Colorless\\SmallGolemTower.ets")  # 38
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(85.00, -9.0, "Units\\Colorless\\SmallGolemTower.ets")  # 39
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(85.00, 9.0, "Units\\Colorless\\SmallGolemTower.ets")  # 40
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(87.00, -11.0, "Units\\Colorless\\BigGolemTower.ets")  # 41
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(87.00, 11.0, "Units\\Colorless\\BigGolemTower.ets")  # 42
	ScenarioDirector.SpawnGuards(87 - 4, (-23) + 23, ["MediumMeleeGolem", "BigMeleeGolem", "BigMeleeGolem", "MediumMeleeGolem", "SmallFlyingGolem", "SmallRangedGolem", "BigCasterGolem", "BigCasterGolem", "SmallRangedGolem", "SmallFlyingGolem"], [], 0)  # 43
	ScenarioDirector.ChangeGoldIncome(0, 0).ChangeWood(0, 5400).ChangeWoodIncome(0, 15).ChangeUnitSpawnerSubset(0, ["SmallMeleeGolem", "SmallRangedGolem", "SmallFlyingGolem"]).RegisterBossWave("FirstBossWave", ["MediumMeleeGolem"], ["SmallMeleeGolem", "SmallRangedGolem"]).SpawnRandomBossWave(1 * 60, 350).UnregisterBossWaveAtTime((1 * 60) + 5, "FirstBossWave").RegisterBossWaveAtTime((2 * 60) + 55, "Siege_1", ["SmallMeleeGolem", "SmallMeleeGolem", "SiegeGolem"], ["SiegeGolem", "SmallMeleeGolem"]).RegisterBossWaveAtTime((2 * 60) + 55, "Siege_2", ["MediumMeleeGolem", "SiegeGolem"], ["SiegeGolem", "SmallMeleeGolem"]).SpawnRandomBossWave(3 * 60, 450).AddUnitsToSpawnerSubset(5 * 60, ["MediumMeleeGolem"]).SpawnRandomBossWave(5 * 60, 550).ChangeWoodIncome(5 * 60, 12).RegisterBossWaveAtTime((6 * 60) + 55, "Damage", ["MediumMeleeGolem", "BigCasterGolem", "SmallCasterGolem", "SmallCasterGolem"], ["SmallMeleeGolem", "SmallRangedGolem"]).SpawnRandomBossWave(7 * 60, 650).ChangeWoodIncome(7 * 60, 9).SpawnRandomBossWave(10 * 60, 750).ChangeWoodIncome(12 * 60, 0)  # 45
