# Generated by tools/transpile_scripts.py from Scripts\Scenarios\AttackDuoScenarioVeryEasy.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Scenarios\AttackDuoScenarioVeryEasy.dws:3
func Apply(Entity, Game) -> void:
	var ScenarioDirector = null  # 6
	ScenarioDirector = Game.ScenarioDirector  # 10
	ScenarioDirector.EnableMirroring()  # 12
	ScenarioDirector.SpawnUnit(-48.0, -23.0, "Units\\Scenario\\GolemLaneTowerLevel1_WithLaneNode.ets")  # 14
	ScenarioDirector.SpawnGuards(-53, -23, ["SmallMeleeGolem", "SmallRangedGolem"], [], 0)  # 15
	ScenarioDirector.SpawnUnit(0.0, -23.0, "Units\\Scenario\\GolemLaneTowerLevel1_WithLaneNode.ets")  # 18
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(-2.00, -23.00, "Units\\Colorless\\MeleeGolemTower.ets")  # 19
	ScenarioDirector.SpawnGuards(-5, -23, [], ["SmallMeleeGolem", "SmallRangedGolem"], 200)  # 20
	ScenarioDirector.SpawnUnit(48.0, -23.0, "\\Units\\Scenario\\GolemLaneTowerLevel1_WithLaneNode.ets")  # 23
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(44.06, -28.94, "Units\\Colorless\\SmallGolemTower.ets")  # 24
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(44.06, -18.46, "Units\\Colorless\\SmallGolemTower.ets")  # 25
	ScenarioDirector.SpawnGuards(43, -23, ["SmallMeleeGolem", "SmallRangedGolem"], ["SmallMeleeGolem", "SmallRangedGolem"], 300)  # 26
	ScenarioDirector.DisableMirroring()  # 28
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(78.00, -2.0, "Units\\Colorless\\SmallGolemTower.ets")  # 31
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(78.00, 2.0, "Units\\Colorless\\SmallGolemTower.ets")  # 32
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(85.00, -9.0, "Units\\Colorless\\SmallGolemTower.ets")  # 33
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(85.00, 9.0, "Units\\Colorless\\SmallGolemTower.ets")  # 34
	ScenarioDirector.SpawnGuards(87 - 4, (-23) + 23, ["MediumMeleeGolem", "MediumMeleeGolem", "SmallMeleeGolem", "SmallMeleeGolem", "SmallRangedGolem", "SmallRangedGolem", "SmallRangedGolem"], [], 0)  # 35
	ScenarioDirector.ChangeGoldIncome(0, 0).ChangeWood(0, 1000).ChangeWoodIncome(0, 8).ChangeUnitSpawnerSubset(0, ["SmallMeleeGolem", "SmallRangedGolem"]).RegisterBossWave("FirstBossWave", ["SmallMeleeGolem"], ["SmallMeleeGolem", "SmallRangedGolem"]).SpawnRandomBossWave(1 * 60, 200).UnregisterBossWaveAtTime((1 * 60) + 5, "FirstBossWave").RegisterBossWaveAtTime((2 * 60) + 55, "Simple_1", ["SmallMeleeGolem", "SmallRangedGolem"], ["SmallMeleeGolem", "SmallRangedGolem"]).RegisterBossWaveAtTime((2 * 60) + 55, "Simple_2", ["MediumMeleeGolem"], ["SmallMeleeGolem", "SmallRangedGolem"]).SpawnRandomBossWave(3 * 60, 250).SpawnRandomBossWave(5 * 60, 250).ChangeWoodIncome(5 * 60, 5).SpawnRandomBossWave(7 * 60, 300).ChangeWoodIncome(7 * 60, 2).SpawnRandomBossWave(10 * 60, 350).ChangeWoodIncome(12 * 60, 0)  # 37
