# Generated by tools/transpile_scripts.py from Scripts\Scenarios\AttackDuoScenarioEasy.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Scenarios\AttackDuoScenarioEasy.dws:3
func Apply(Entity, Game) -> void:
	var ScenarioDirector = null  # 6
	ScenarioDirector = Game.ScenarioDirector  # 10
	ScenarioDirector.EnableMirroring()  # 12
	ScenarioDirector.SpawnUnit(-48.0, -23.0, "Units\\Scenario\\GolemLaneTowerLevel1_WithLaneNode.ets")  # 14
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(-52.07, -22.78, "Units\\Colorless\\MeleeGolemTower.ets")  # 15
	ScenarioDirector.SpawnGuards(-53, -23, ["SmallMeleeGolem", "SmallRangedGolem"], [], 300)  # 16
	ScenarioDirector.SpawnUnit(0.0, -23.0, "Units\\Scenario\\GolemLaneTowerLevel1_WithLaneNode.ets")  # 19
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(-2.0, -28.94, "Units\\Colorless\\SmallGolemTower.ets")  # 20
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(-2.0, -18.46, "Units\\Colorless\\SmallGolemTower.ets")  # 21
	ScenarioDirector.SpawnGuards(-5, -23, [], ["SmallMeleeGolem", "SmallRangedGolem"], 400)  # 22
	ScenarioDirector.SpawnUnit(48.0, -23.0, "\\Units\\Scenario\\GolemLaneTowerLevel2_WithLaneNode.ets")  # 25
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(44.06, -16.63, "\\Units\\Colorless\\MeleeGolemTower.ets")  # 26
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(43.96, -29.88, "\\Units\\Colorless\\MeleeGolemTower.ets")  # 27
	ScenarioDirector.SpawnGuards(43, -23, ["MediumMeleeGolem", "MediumMeleeGolem", "SmallRangedGolem"], ["SmallMeleeGolem", "SmallRangedGolem"], 500)  # 28
	ScenarioDirector.DisableMirroring()  # 30
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(80.00, 0.0, "Units\\Colorless\\BigGolemTower.ets")  # 33
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(78.00, -2.0, "Units\\Colorless\\SmallGolemTower.ets")  # 34
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(78.00, 2.0, "Units\\Colorless\\SmallGolemTower.ets")  # 35
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(85.00, -9.0, "Units\\Colorless\\SmallGolemTower.ets")  # 36
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(85.00, 9.0, "Units\\Colorless\\SmallGolemTower.ets")  # 37
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(87.00, -11.0, "Units\\Colorless\\SmallGolemTower.ets")  # 38
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(87.00, 11.0, "Units\\Colorless\\SmallGolemTower.ets")  # 39
	ScenarioDirector.SpawnGuards(87 - 4, (-23) + 23, ["MediumMeleeGolem", "MediumMeleeGolem", "MediumMeleeGolem", "SmallMeleeGolem", "SmallMeleeGolem", "SmallRangedGolem", "SmallRangedGolem", "SmallRangedGolem", "SmallRangedGolem"], [], 0)  # 40
	ScenarioDirector.ChangeGoldIncome(0, 0).ChangeWood(0, 3300).ChangeWoodIncome(0, 10).ChangeUnitSpawnerSubset(0, ["SmallMeleeGolem", "SmallRangedGolem"]).RegisterBossWave("FirstBossWave", ["MediumMeleeGolem"], ["SmallMeleeGolem", "SmallRangedGolem"]).SpawnRandomBossWave(1 * 60, 350).UnregisterBossWaveAtTime((1 * 60) + 5, "FirstBossWave").RegisterBossWaveAtTime((2 * 60) + 55, "Siege_1", ["SmallMeleeGolem", "SmallMeleeGolem", "SiegeGolem"], ["SiegeGolem", "SmallMeleeGolem"]).RegisterBossWaveAtTime((2 * 60) + 55, "Siege_2", ["MediumMeleeGolem", "SiegeGolem"], ["SiegeGolem", "SmallMeleeGolem"]).SpawnRandomBossWave(3 * 60, 350).AddUnitsToSpawnerSubset(5 * 60, ["MediumMeleeGolem"]).SpawnRandomBossWave(5 * 60, 450).ChangeWoodIncome(5 * 60, 6).SpawnRandomBossWave(7 * 60, 550).ChangeWoodIncome(7 * 60, 3).SpawnRandomBossWave(10 * 60, 650).ChangeWoodIncome(12 * 60, 0)  # 42
