# Generated by tools/transpile_scripts.py from Scripts\Scenarios\AttackScenarioVeryHard.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Scenarios\AttackScenarioVeryHard.dws:3
func Apply(Entity, Game) -> void:
	var ScenarioDirector = null  # 6
	ScenarioDirector = Game.ScenarioDirector  # 10
	ScenarioDirector.SpawnUnit(-48.0, -23.0, "Units\\Scenario\\GolemLaneTowerLevel1_WithLaneNode.ets")  # 14
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(-52.07, -19.63, "Units\\Colorless\\MeleeGolemTower.ets")  # 15
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(-52.07, -26.88, "Units\\Colorless\\MeleeGolemTower.ets")  # 16
	ScenarioDirector.SpawnGuards(-53, -23, ["MediumMeleeGolem", "SmallRangedGolem", "BigFlyingGolem", "SmallRangedGolem"], ["MediumMeleeGolem", "SmallMeleeGolem"], 200)  # 17
	ScenarioDirector.SpawnUnit(0.0, -23.0, "Units\\Scenario\\GolemLaneTowerLevel2_WithLaneNode.ets")  # 20
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(-2.0, -22.78, "Units\\Colorless\\MeleeGolemTower.ets")  # 21
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(-2.0, -28.94, "Units\\Colorless\\BigGolemTower.ets")  # 22
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(-2.0, -18.46, "Units\\Colorless\\BigGolemTower.ets")  # 23
	ScenarioDirector.SpawnGuards(-5, -23, ["BigMeleeGolem", "BigFlyingGolem", "SmallCasterGolem"], ["MediumMeleeGolem", "SmallFlyingGolem"], 900)  # 24
	ScenarioDirector.SpawnUnit(48.0, -23.0, "\\Units\\Scenario\\GolemLaneTowerLevel3_WithLaneNode.ets")  # 27
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(44.00, -19.63, "Units\\Colorless\\BigGolemTower.ets")  # 28
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(44.00, -26.88, "Units\\Colorless\\BigGolemTower.ets")  # 29
	ScenarioDirector.SpawnGuards(43, -23, ["BigMeleeGolem", "SmallRangedGolem", "BigCasterGolem", "SmallCasterGolem"], ["MediumMeleeGolem", "BigFlyingGolem", "SmallRangedGolem"], 900)  # 30
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(89.53, -18.92, "Units\\Colorless\\BigGolemTower.ets")  # 36
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(89.56, -27.00, "Units\\Colorless\\BigGolemTower.ets")  # 37
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(85.66, -28.90, "Units\\Colorless\\BigGolemTower.ets")  # 38
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(85.86, -17.12, "Units\\Colorless\\BigGolemTower.ets")  # 39
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(85.72, -22.81, "Units\\Colorless\\BossGolem.ets")  # 40
	ScenarioDirector.SpawnGuards(87, -23, ["SmallFlyingGolem", "BigFlyingGolem", "BigFlyingGolem", "SmallFlyingGolem"], [], 0)  # 41
	ScenarioDirector.ChangeGoldIncome(0, 0).ChangeWood(0, 4300).ChangeWoodIncome(0, 21).ChangeUnitSpawnerSubset(0, ["SmallMeleeGolem", "SmallRangedGolem", "SmallCasterGolem", "MediumMeleeGolem", "BigFlyingGolem"]).RegisterBossWave("FirstBossWave", ["MediumMeleeGolem", "BigFlyingGolem"], ["SmallMeleeGolem", "SmallRangedGolem", "SmallCasterGolem"]).SpawnRandomBossWave(1 * 60, 600).UnregisterBossWaveAtTime((1 * 60) + 5, "FirstBossWave").RegisterBossWaveAtTime((2 * 60) + 55, "Siege_1", ["BigMeleeGolem", "BigFlyingGolem", "SiegeGolem", "SmallCasterGolem"], ["SiegeGolem", "SmallMeleeGolem"]).RegisterBossWaveAtTime((2 * 60) + 55, "Siege_2", ["BigMeleeGolem", "MediumMeleeGolem", "MediumMeleeGolem", "SiegeGolem", "SmallCasterGolem"], ["SiegeGolem", "SmallMeleeGolem"]).SpawnRandomBossWave(3 * 60, 900).AddUnitsToSpawnerSubset(5 * 60, ["BigMeleeGolem", "BigCasterGolem"]).ChangeWoodIncome(5 * 60, 16).SpawnRandomBossWave(5 * 60, 1000).UnregisterBossWaveAtTime((6 * 60) + 55, "Siege_1").UnregisterBossWaveAtTime((6 * 60) + 55, "Siege_2").RegisterBossWaveAtTime((6 * 60) + 55, "Damage", ["MediumMeleeGolem", "BigCasterGolem", "SmallCasterGolem", "SmallCasterGolem"], ["SmallMeleeGolem", "SmallRangedGolem"]).RegisterBossWaveAtTime((6 * 60) + 55, "Flying", ["MediumMeleeGolem", "MediumMeleeGolem", "BigFlyingGolem"], ["SmallMeleeGolem", "SmallFlyingGolem"]).RegisterBossWaveAtTime((6 * 60) + 55, "Breaker", ["BigMeleeGolem", "SiegeGolem", "SiegeGolem"], ["MediumMeleeGolem", "SmallCasterGolem"]).ChangeWoodIncome(7 * 60, 12).SpawnRandomBossWave(7 * 60, 1100).SpawnRandomBossWave(10 * 60, 1200).ChangeWoodIncome(12 * 60, 0)  # 43
