# Generated by tools/transpile_scripts.py from Scripts\Scenarios\SandboxAttackDuoScenarioVeryEasy.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Scenarios\SandboxAttackDuoScenarioVeryEasy.dws:3
func Apply(Entity, Game) -> void:
	var ScenarioDirector = null  # 6
	ScenarioDirector = Game.ScenarioDirector  # 10
	ScenarioDirector.EnableMirroring()  # 12
	ScenarioDirector.SpawnUnit(-48.0, -23.0, "Units\\Scenario\\GolemLaneTowerLevel1_WithLaneNode.ets")  # 14
	ScenarioDirector.SpawnGuards(-53, -23, ["SmallMeleeGolem", "SmallRangedGolem"], [], 0)  # 15
	ScenarioDirector.SpawnUnit(0.0, -23.0, "Units\\Scenario\\GolemLaneTowerLevel1_WithLaneNode.ets")  # 18
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(-2.00, -23.00, "\\Units\\Colorless\\MeleeGolemTower.ets")  # 19
	ScenarioDirector.SpawnGuards(-5, -23, [], ["SmallMeleeGolem", "SmallRangedGolem"], 200)  # 20
	ScenarioDirector.SpawnUnit(48.0, -23.0, "\\Units\\Scenario\\GolemLaneTowerLevel1_WithLaneNode.ets")  # 23
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(44.06, -28.94, "Units\\Colorless\\SmallGolemTower.ets")  # 24
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(44.06, -18.46, "Units\\Colorless\\SmallGolemTower.ets")  # 25
	ScenarioDirector.SpawnGuards(43, -23, ["SmallMeleeGolem", "SmallRangedGolem"], ["SmallMeleeGolem", "SmallRangedGolem"], 100)  # 26
	ScenarioDirector.DisableMirroring()  # 28
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(85.66 - 4, (-28.90) + 23.0, "Units\\Colorless\\SmallGolemTower.ets")  # 31
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(85.86 - 4, (-17.12) + 23.0, "Units\\Colorless\\SmallGolemTower.ets")  # 32
	ScenarioDirector.SpawnGuards(87 - 4, (-23) + 23, ["MediumMeleeGolem", "SmallMeleeGolem", "SmallRangedGolem"], [], 0)  # 33
