# Generated by tools/transpile_scripts.py from Scripts\Scenarios\SandboxAttackDuoScenarioEasy.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Scenarios\SandboxAttackDuoScenarioEasy.dws:3
func Apply(Entity, Game) -> void:
	var ScenarioDirector = null  # 6
	ScenarioDirector = Game.ScenarioDirector  # 10
	ScenarioDirector.EnableMirroring()  # 12
	ScenarioDirector.SpawnUnit(-48.0, -23.0, "Units\\Scenario\\GolemLaneTowerLevel1_WithLaneNode.ets")  # 14
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(-52.07, -22.78, "Units\\Colorless\\MeleeGolemTower.ets")  # 15
	ScenarioDirector.SpawnGuards(-53, -23, ["SmallMeleeGolem", "SmallRangedGolem"], [], 300)  # 16
	ScenarioDirector.SpawnUnit(0.0, -23.0, "Units\\Scenario\\GolemLaneTowerLevel1_WithLaneNode.ets")  # 19
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(-2.0, -28.94, "Units\\Colorless\\SmallGolemTower.ets")  # 20
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(-2.0, -18.46, "Units\\Colorless\\SmallGolemTower.ets")  # 21
	ScenarioDirector.SpawnGuards(-5, -23, [], ["SmallMeleeGolem", "SmallRangedGolem"], 400)  # 22
	ScenarioDirector.SpawnUnit(48.0, -23.0, "\\Units\\Scenario\\GolemLaneTowerLevel2_WithLaneNode.ets")  # 25
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(44.06, -16.63, "\\Units\\Colorless\\MeleeGolemTower.ets")  # 26
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(43.96, -29.88, "\\Units\\Colorless\\MeleeGolemTower.ets")  # 27
	ScenarioDirector.SpawnGuards(43, -23, ["MediumMeleeGolem", "MediumMeleeGolem", "SmallRangedGolem"], ["SmallMeleeGolem", "SmallRangedGolem"], 500)  # 28
	ScenarioDirector.DisableMirroring()  # 30
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(89.53 - 4, (-18.92) + 23.0, "Units\\Colorless\\SmallGolemTower.ets")  # 33
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(89.56 - 4, (-27.00) + 23.0, "Units\\Colorless\\SmallGolemTower.ets")  # 34
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(85.66 - 4, (-28.90) + 23.0, "Units\\Colorless\\SmallGolemTower.ets")  # 35
	ScenarioDirector.SpawnUnitWithoutLimitedLifetime(85.86 - 4, (-17.12) + 23.0, "Units\\Colorless\\SmallGolemTower.ets")  # 36
	ScenarioDirector.SpawnGuards(87 - 4, (-23) + 23, ["MediumMeleeGolem", "MediumMeleeGolem", "SmallRangedGolem"], [], 0)  # 37
