# Generated by tools/transpile_scripts.py from Scripts\Units\Green\Groundbreaker.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TStatisticsUnitComponent.new().Create(Entity)  # 27
	THealthComponent.new().Create(Entity)  # 29
	TArmorComponent.new().Create(Entity)  # 30
	TMovementComponent.new().Create(Entity)  # 31
	TThinkImpulseTimerComponent.new().Create(Entity)  # 32
	TBrainFollowLaneComponent.new().Create(Entity)  # 33
	TBrainActionComponent.new().CreateGroupedAll(Entity)  # 34
	TAutoBrainOnDeathComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).FireAtGround()  # 37
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).MustNotHave([C.upSoulless])  # 39
	TWelaEffectFactoryComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).PassCardValues()  # 41
	TPathfindingComponent.new().Create(Entity)  # 45

# Units\Green\Groundbreaker.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.75  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecGreen)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier3, C.upUnit, C.upGround, C.upMelee])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atUnarmored)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 345.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 345.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetValue(C.eiWelaRange, [1], 1.0)  # 14 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtMelee])  # 15
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 150.0)  # 16 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 1700)  # 17 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 500)  # 18
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 1500)  # 19
	Entity.Blackboard.SetValue(C.eiWelaModifier, [2], 1.5)  # 22
	Entity.Blackboard.SetValue(C.eiWelaModifier, [3], 2.0)  # 23
	Entity.Blackboard.SetValue(C.eiWelaRange, [4, 5], 1.0)  # 26
	Entity.Blackboard.SetValue(C.eiDamageType, [5], [C.dtSplash, C.dtAbility])  # 28
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [5], 3.0)  # 29
	Entity.Blackboard.SetValue(C.eiWelaDamage, [5], 120.0)  # 30
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [5], 133)  # 31
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [5], 1233)  # 32
	Entity.Blackboard.SetValue(C.eiWelaModifier, [6], 0.40)  # 35

# Units\Green\Groundbreaker.ets:56
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 58
	InitUnitMeta(Entity)  # 59
	TUnitPropertyComponent.new().CreateGrouped(Entity, [5], [C.upInvincible, C.upBurrowed])  # 88

# Units\Green\Groundbreaker.ets:91
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 93
	InitUnitEntity(Entity)  # 94
	TBrainApproachComponent.new().CreateGrouped(Entity, [4])  # 98
	TWelaTargetingRadialAttentionComponent.new().CreateGrouped(Entity, [4]).SetTargetTeamConstraint(C.tcEnemies)  # 99
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [5]).Preemptive()  # 103
	TAutoBrainOnUnitPropertyComponent.new().CreateGrouped(Entity, [5]).TriggerOn([C.upFlying])  # 105
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [5]).SetTargetTeamConstraint(C.tcEnemies)  # 107
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [4, 5], C.eiDamageable)  # 109
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [4, 5]).MustHave([C.upGround]).MustNotHave([C.upBanished])  # 110
	TWelaTargetConstraintEnemiesComponent.new().CreateGrouped(Entity, [4, 5])  # 113
	TWelaEffectRedirecterComponent.new().CreateGrouped(Entity, [5]).RedirectToGround()  # 114
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [5])  # 116
	TWarheadSplashDamageComponent.new().CreateGrouped(Entity, [5])  # 117
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [5]).Name("DebutRupture").Name("Splash").TriggerOnKillDone().TriggerOnFire()  # 118
	TWelaEffectRemoveAfterUseComponent.new().CreateGrouped(Entity, [5]).TargetGroup([4, 5])  # 123
	TBrainApproachComponent.new().CreateGrouped(Entity, [0])  # 127
	TWelaTargetingRadialAttentionComponent.new().CreateGrouped(Entity, [0]).SetTargetTeamConstraint(C.tcEnemies)  # 128
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [1]).Preemptive()  # 132
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [1], true)  # 134
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [1]).SetTargetTeamConstraint(C.tcEnemies)  # 135
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [0, 1], C.eiDamageable)  # 137
	TWelaTargetConstraintCompareUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).BothMustHaveAny([C.upGround, C.upFlying])  # 138
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).MustNotHave([C.upInvisible, C.upBanished])  # 140
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [1])  # 142
	TWarheadSpottyDamageComponent.new().CreateGrouped(Entity, [1])  # 143
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [1]).Name("Melee").TriggerOnDie().TriggerOnKillDone()  # 144
	TModifierMultiplyDealtDamageComponent.new().CreateGrouped(Entity, [1]).MustNotHave([C.dtSpell]).CheckWelaConstraint().SetValueGroup([2])  # 150
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [2]).MustHaveAny([C.upFrozen, C.upStunned, C.upBlinded, C.upGrounded, C.upLifted, C.upBleeding, C.upPetrified]).MustNotHave([C.upRooted])  # 154
	TModifierMultiplyDealtDamageComponent.new().CreateGrouped(Entity, [1]).MustNotHave([C.dtSpell]).CheckWelaConstraint().SetValueGroup([3])  # 157
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [3]).MustHave([C.upRooted])  # 161
	TBuffTakenDamageMultiplierComponent.new().CreateGrouped(Entity, [6]).DodgeDamage().DamageTypeMustNotHave([C.dtSpell, C.dtDoT, C.dtSplash])  # 164
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [6]).Name("Evade").TriggerOnFire()  # 167
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [6]).Name("EvadedThreeTimes").CheckNth(3).TriggerOnFire()  # 170
