# Generated by tools/transpile_scripts.py from Scripts\Units\Green\Sapling.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TStatisticsUnitComponent.new().Create(Entity)  # 27
	THealthComponent.new().Create(Entity)  # 29
	TArmorComponent.new().Create(Entity)  # 30
	TMovementComponent.new().Create(Entity)  # 31
	TThinkImpulseTimerComponent.new().Create(Entity)  # 32
	TBrainFollowLaneComponent.new().Create(Entity)  # 33
	TBrainActionComponent.new().CreateGroupedAll(Entity)  # 34
	TAutoBrainOnDeathComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).FireAtGround()  # 37
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).MustNotHave([C.upSoulless])  # 39
	TWelaEffectFactoryComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).PassCardValues()  # 41
	TPathfindingComponent.new().Create(Entity)  # 45

# Units\Green\Sapling.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.3  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecGreen)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier1, C.upUnit, C.upGround, C.upMelee, C.upSapling, C.upSoulless])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atUnarmored)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 2.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 2.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetValue(C.eiWelaRange, [1], 0.5)  # 14
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtMelee])  # 15
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 4.0)  # 16 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 1500)  # 17 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 266)  # 18
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 766)  # 19
	Entity.Blackboard.SetValue(C.eiCooldown, [9], 17000)  # 22

# Units\Green\Sapling.ets:37
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 39
	InitUnitMeta(Entity)  # 40

# Units\Green\Sapling.ets:61
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 63
	InitUnitEntity(Entity)  # 64
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, []).Name("SaplingByBaseBuilding").CheckDamageType(C.dtTrue).TriggerOnTakeDamage()  # 67
	TBrainApproachComponent.new().CreateGrouped(Entity, [0])  # 72
	TWelaTargetingRadialAttentionComponent.new().CreateGrouped(Entity, [0]).SetTargetTeamConstraint(C.tcEnemies)  # 73
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [1]).Preemptive()  # 77
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [1], true)  # 79
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [1]).SetTargetTeamConstraint(C.tcEnemies)  # 80
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [0, 1], C.eiDamageable)  # 82
	TWelaTargetConstraintCompareUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).BothMustHaveAny([C.upGround, C.upFlying])  # 83
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).MustNotHave([C.upInvisible, C.upBanished])  # 85
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [1])  # 87
	TWarheadSpottyDamageComponent.new().CreateGrouped(Entity, [1])  # 88
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [1]).Name("Melee").TriggerOnDie().TriggerOnKillDone()  # 89
	TWelaEffectSuicideComponent.new().CreateGrouped(Entity, [9])  # 95
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [9], false)  # 96
	TBrainWelaSelftargetGroundComponent.new().CreateGrouped(Entity, [9])  # 97
	TAutoBrainOnUnitPropertyComponent.new().CreateGrouped(Entity, [10]).TriggerOn([C.upBlessed])  # 99
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [10]).Name("Flourish").TriggerOnFire()  # 101
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [10])  # 104
	TWelaEffectRemoveAfterUseComponent.new().CreateGrouped(Entity, [10]).TargetGroup([9, 10])  # 105
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [10], "Modifiers\\BlessingSapling.dws")  # 109
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [], "Modifiers\\LegendarySpawn.dws").PassIntValue(200).ApplyToSelfAtCreate()  # 110
