# Generated by tools/transpile_scripts.py from Scripts\Units\Green\Woodwalker.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TStatisticsUnitComponent.new().Create(Entity)  # 27
	THealthComponent.new().Create(Entity)  # 29
	TArmorComponent.new().Create(Entity)  # 30
	TMovementComponent.new().Create(Entity)  # 31
	TThinkImpulseTimerComponent.new().Create(Entity)  # 32
	TBrainFollowLaneComponent.new().Create(Entity)  # 33
	TBrainActionComponent.new().CreateGroupedAll(Entity)  # 34
	TAutoBrainOnDeathComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).FireAtGround()  # 37
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).MustNotHave([C.upSoulless])  # 39
	TWelaEffectFactoryComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).PassCardValues()  # 41
	TPathfindingComponent.new().Create(Entity)  # 45

# Units\Green\Woodwalker.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.45  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecGreen)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier2, C.upUnit, C.upGround, C.upRanged])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atUnarmored)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 85.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 85.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reMana, 4)  # 12
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reMana, 16)  # 13
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 8.0)  # 16 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [1], "Projectiles\\Green\\WoodwalkerProjectile")  # 17
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 2800)  # 18 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtRanged])  # 19
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 99.0)  # 20 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 350)  # 21
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 1166)  # 22
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [2], C.reMana, 4)  # 25
	Entity.Blackboard.SetValue(C.eiWelaRange, [2], 12.0)  # 26
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [2], "Units\\Green\\Sapling")  # 27
	Entity.Blackboard.SetValue(C.eiWelaCount, [2], 2)  # 28
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [2], 800)  # 29
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [2], 1700)  # 30
	Entity.Blackboard.SetValue(C.eiWelaDamage, [3], 1.0)  # 33
	Entity.Blackboard.SetValue(C.eiCooldown, [3], 3000)  # 34

# Units\Green\Woodwalker.ets:52
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 54
	InitUnitMeta(Entity)  # 55

# Units\Green\Woodwalker.ets:77
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 79
	InitUnitEntity(Entity)  # 80
	TBrainWelaSelftargetComponent.new().CreateGrouped(Entity, [2]).Blocking()  # 84
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [2]).MustNotHave([C.upSilenced])  # 86
	TWelaReadyCostComponent.new().CreateGrouped(Entity, [2]).SetPayingGroupForType(C.reMana, [])  # 88
	TWelaEffectFactoryComponent.new().CreateGrouped(Entity, [2]).SpreadSpawns()  # 90
	TWelaEffectPayCostComponent.new().CreateGrouped(Entity, [2]).SetPayingGroupForType(C.reMana, [])  # 92
	TWelaEffectActivationAbilityComponent.new().CreateGrouped(Entity, [2]).SetCheckGroup([]).CheckNotFull(C.reMana).SetsActive().SetActivationGroup([3])  # 94
	TBrainApproachComponent.new().CreateGrouped(Entity, [0])  # 100
	TWelaTargetingRadialAttentionComponent.new().CreateGrouped(Entity, [0]).SetTargetTeamConstraint(C.tcEnemies)  # 101
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [1]).Preemptive()  # 105
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [1], true)  # 107
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [1]).SetTargetTeamConstraint(C.tcEnemies)  # 108
	TWelaEffectProjectileComponent.new().CreateGrouped(Entity, [1])  # 110
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).MustNotHave([C.upInvisible, C.upBanished])  # 111
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [0, 1], C.eiDamageable)  # 113
	TBrainWelaSelftargetComponent.new().CreateGrouped(Entity, [3]).ThinksPassively()  # 116
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [3], false)  # 118
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [3])  # 119
	TWarheadSpottyResourceComponent.new().CreateGrouped(Entity, [3]).SetResourceType(C.reMana).TargetGroup([])  # 120
	TWelaEffectActivationAbilityComponent.new().CreateGrouped(Entity, [3]).SetCheckGroup([]).TriggerOnReachResourceCap(C.reMana)  # 123
