# Generated by tools/transpile_scripts.py from Scripts\Spells\Black\Frostspear.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\Black\Frostspear.dws:1
func Apply(Entity) -> void:
	var Group: int = 0  # 2
	var FinishGroup: int = 0  # 2
	Group = Entity.ReserveFreeGroup()  # 4
	FinishGroup = Entity.ReserveFreeGroup()  # 5
	Entity.Blackboard.SetValue(C.eiCooldown, [Group], 100)  # 6
	Entity.Blackboard.SetValue(C.eiWelaDamage, [Group], 10.0)  # 7
	Entity.Blackboard.SetValue(C.eiWelaRange, [Group], 6.0)  # 8
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [Group], "Projectiles\\Black\\FrostspearProjectile")  # 9
	Entity.Blackboard.SetValue(C.eiDamageType, [Group], [C.dtSpell])  # 10
	TThinkImpulseTimerCooldownComponent.new().CreateGrouped(Entity, [Group, FinishGroup]).TimerIsReady()  # 13
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [Group]).DisableTargetLock().ThinksLocal().ThinksPassively()  # 15
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [Group]).IgnoreOwnCollisionradius().SetTargetTeamConstraint(C.tcAllies).PicksRandomTargets()  # 19
	TWelaTargetConstraintNotSelfComponent.new().CreateGrouped(Entity, [Group])  # 23
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [Group]).MustNotHave([C.upInvisible, C.upBanished, C.upSpellImmune])  # 24
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [Group], C.eiDamageable)  # 26
	TWelaEffectProjectileComponent.new().CreateGrouped(Entity, [Group])  # 27
	TBrainWelaTargetlessComponent.new().CreateGrouped(Entity, [FinishGroup]).ThinksLocal().ThinksPassively()  # 29
	TWelaReadyNthComponent.new().CreateGrouped(Entity, [FinishGroup]).Nth(12)  # 32
	TWelaEffectRemoveAfterUseComponent.new().CreateGrouped(Entity, [FinishGroup]).TargetGroup([Group, FinishGroup])  # 34
