# Generated by tools/transpile_scripts.py from Scripts\Spells\Black\RipOutSoul.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\Black\RipOutSoul.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiCooldown, [0], 500)  # 5
	Entity.Blackboard.SetValue(C.eiWelaRange, [0], 5.5)  # 7
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [0], 20)  # 8
	Entity.Blackboard.SetValue(C.eiWelaDamage, [0], 0.30)  # 9
	Entity.Blackboard.SetValue(C.eiDamageType, [0], [C.dtSpell, C.dtSplash])  # 10

# Spells\Black\RipOutSoul.ets:13
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 15
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [10]).MustHave([C.upUnit]).MustNotHave([C.upLegendary, C.upSpellImmune])  # 18
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [11], C.eiDamageable)  # 23
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [11]).MustNotHave([C.upImmuneToBanished, C.upImmuneToStateEffects])  # 24
	TWelaTargetConstraintBooleanComponent.new().CreateGrouped(Entity, [0]).GroupA([10]).GroupB([11]).OperatorAnd()  # 27

# Spells\Black\RipOutSoul.ets:41
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 43
	TThinkImpulseTimerCooldownComponent.new().CreateGrouped(Entity, [0, 1, 3])  # 47
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [0])  # 50
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [0]).SetTargetTeamConstraint(C.tcAll)  # 51
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [0])  # 53
	TWarheadSpottyDamageComponent.new().CreateGrouped(Entity, [0]).PercentageOfMaxHealth()  # 54
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [0]).Name("RipOutSoul").TriggerOnFire().TriggerOnKillDone().TriggerGlobalOnKillDone()  # 56
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [0]).Name("Spell").TriggerOnDamageDone()  # 61
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [0]).Name("Banished").TriggerOnFire()  # 65
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [0]).Name("BanishedMelee").CheckUnitPropertyMustHave([C.upMelee]).TriggerOnFire()  # 68
	TBrainWelaTargetlessComponent.new().CreateGrouped(Entity, [3])  # 74
	TWelaEffectSuicideComponent.new().CreateGrouped(Entity, [3])  # 75
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [0], "Modifiers\\Banished.dws")  # 78
