# Generated by tools/transpile_scripts.py from Scripts\Scenarios\PerformanceTest.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Scenarios\PerformanceTest.dws:3
func Apply(Entity, Game) -> void:
	pass
