# Generated by tools/transpile_scripts.py from Scripts\Projectiles\White\HomelandProjectile.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\White\HomelandProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(22) / 1000)  # 5

# Projectiles\White\HomelandProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10

# Projectiles\White\HomelandProjectile.ets:35
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 37
	TMovementComponent.new().Create(Entity)  # 40
	TBrainProjectileComponent.new().CreateGrouped(Entity, [0])  # 41
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [0])  # 42
