# Generated by tools/transpile_scripts.py from Scripts\Projectiles\White\LotharWallOfLightProjectile.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\White\LotharWallOfLightProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(30) / 1000)  # 5

# Projectiles\White\LotharWallOfLightProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10

# Projectiles\White\LotharWallOfLightProjectile.ets:36
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 38
	TMovementComponent.new().Create(Entity)  # 41
	TBrainProjectileComponent.new().CreateGrouped(Entity, [0])  # 42
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [0]).MustHave([C.upUnit]).MustNotHave([C.upBase])  # 43
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [0])  # 46
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [0], "Modifiers\\Shieldblock.dws")  # 50
