# Generated by tools/transpile_scripts.py from Scripts\Projectiles\White\PatronSaintProjectile.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\White\PatronSaintProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(20) / 1000)  # 5
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [1], 3.0)  # 7
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 60.0)  # 8
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtFlatHeal, C.dtSplash])  # 9

# Projectiles\White\PatronSaintProjectile.ets:12
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 14

# Projectiles\White\PatronSaintProjectile.ets:41
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 43
	TMovementComponent.new().Create(Entity)  # 46
	TBrainProjectileComponent.new().CreateGrouped(Entity, [0]).NoTargetChecks()  # 47
	TWelaEffectFireComponent.new().CreateGrouped(Entity, [0]).TargetGroup([1]).RedirectToGround()  # 50
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [0])  # 54
	TWarheadSplashDamageComponent.new().CreateGrouped(Entity, [0])  # 55
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [0]).Name("Splash").TriggerOnKillDone()  # 56
	TWelaTargetConstraintEnemiesComponent.new().CreateGrouped(Entity, [0])  # 59
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [0], C.eiDamageable)  # 60
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [0]).MustNotHave([C.upBanished])  # 61
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [1])  # 64
	TWarheadSplashHealComponent.new().CreateGrouped(Entity, [1])  # 65
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [1]).MustHave([C.upUnit]).MustNotHave([C.upUnhealable, C.upBase, C.upBanished])  # 66
	TWelaTargetConstraintAlliesComponent.new().CreateGrouped(Entity, [1])  # 69
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [1]).Name("FlatHeal").TriggerOnHealDone()  # 70
