# Generated by tools/transpile_scripts.py from Scripts\Units\Black\Tyrus.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TStatisticsUnitComponent.new().Create(Entity)  # 27
	THealthComponent.new().Create(Entity)  # 29
	TArmorComponent.new().Create(Entity)  # 30
	TMovementComponent.new().Create(Entity)  # 31
	TThinkImpulseTimerComponent.new().Create(Entity)  # 32
	TBrainFollowLaneComponent.new().Create(Entity)  # 33
	TBrainActionComponent.new().CreateGroupedAll(Entity)  # 34
	TAutoBrainOnDeathComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).FireAtGround()  # 37
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).MustNotHave([C.upSoulless])  # 39
	TWelaEffectFactoryComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).PassCardValues()  # 41
	TPathfindingComponent.new().Create(Entity)  # 45

# Units\Black\Tyrus.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.9  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecBlack)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier3, C.upUnit, C.upGround, C.upMelee, C.upLegendary, C.upSoulGatherer])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atMedium)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 390.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 390.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reMana, 20)  # 13
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reMana, 0)  # 14
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 1.0)  # 17 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtMelee])  # 18
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 65.0)  # 19 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 1000)  # 20 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 366)  # 21
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 800)  # 22
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [2], C.reMana, 1)  # 25
	Entity.Blackboard.SetValue(C.eiWelaDamage, [2], 5.0)  # 26
	Entity.Blackboard.SetValue(C.eiWelaModifier, [2], 0.0)  # 27
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [3], 1)  # 30
	Entity.Blackboard.SetValue(C.eiCooldown, [3], 3000)  # 31
	Entity.Blackboard.SetValue(C.eiWelaRange, [3], 5.0)  # 32
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [3], "Projectiles\\Black\\VoidGatherProjectile")  # 33
	Entity.Blackboard.SetValue(C.eiWelaDamage, [3], 1.0)  # 34
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [5], 200)  # 37
	Entity.Blackboard.SetValue(C.eiWelaRange, [5], 9.0)  # 38
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [5], "Projectiles\\Black\\VoidGatherProjectileTyrus")  # 39
	Entity.Blackboard.SetValue(C.eiWelaDamage, [5], 1.0)  # 40

# Units\Black\Tyrus.ets:66
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 68
	InitUnitMeta(Entity)  # 69
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [5]).MustHave([C.upUnit]).MustNotHave([C.upBase, C.upLegendary, C.upImmuneToBanished, C.upImmuneToStateEffects])  # 71
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [5], C.eiDamageable)  # 74

# Units\Black\Tyrus.ets:99
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 101
	InitUnitEntity(Entity)  # 102
	TBrainApproachComponent.new().CreateGrouped(Entity, [0])  # 105
	TWelaTargetingRadialAttentionComponent.new().CreateGrouped(Entity, [0]).SetTargetTeamConstraint(C.tcEnemies)  # 106
	TAutoBrainOnTakeDamageComponent.new().CreateGrouped(Entity, [2]).ModifiesAmount().FireSelfInGroup([2]).ThinksPassively()  # 110
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [2]).MustNotHave([C.upSilenced])  # 114
	TWelaReadyCostComponent.new().CreateGrouped(Entity, [2]).SetPayingGroupForType(C.reMana, [])  # 116
	TWelaTriggerCheckTakeDamageThresholdComponent.new().CreateGrouped(Entity, [2])  # 118
	TWelaEffectPayCostComponent.new().CreateGrouped(Entity, [2]).SetPayingGroupForType(C.reMana, [])  # 119
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [2]).Name("SoulGathererSoulArmor").Name("SoulConsumed").TriggerOnFire()  # 121
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [3])  # 127
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [3], false)  # 128
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [3]).SetTargetTeamConstraintPriority(C.tcEnemies).PicksRandomTargets()  # 129
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [3]).MustHave([C.upUnit]).MustNotHave([C.upBase, C.upLegendary, C.upImmuneToBanished, C.upImmuneToStateEffects, C.upInvisible])  # 132
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [3], C.eiDamageable)  # 135
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [3])  # 137
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [3]).Name("Banished").TriggerOnFire()  # 138
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [3]).Name("BanishedMelee").CheckUnitPropertyMustHave([C.upMelee]).TriggerOnFire()  # 141
	TWelaEffectProjectileComponent.new().CreateGrouped(Entity, [3]).Reverse()  # 145
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [5]).ThinksPassively()  # 149
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [5]).SetTargetTeamConstraintPriority(C.tcEnemies).PicksRandomTargets()  # 151
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [5])  # 155
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [5]).Name("Banished").Name("PowerfulDebutSoulVortex").TriggerOnFire()  # 156
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [5]).Name("BanishedMelee").CheckUnitPropertyMustHave([C.upMelee]).TriggerOnFire()  # 160
	TWelaEffectProjectileComponent.new().CreateGrouped(Entity, [5]).Reverse()  # 164
	TWelaEffectRemoveAfterUseComponent.new().CreateGrouped(Entity, [5])  # 166
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [1]).Preemptive()  # 169
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [1], true)  # 171
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [1]).SetTargetTeamConstraint(C.tcEnemies)  # 172
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [0, 1], C.eiDamageable)  # 174
	TWelaTargetConstraintCompareUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).BothMustHaveAny([C.upGround, C.upFlying])  # 175
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).MustNotHave([C.upInvisible])  # 177
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [1])  # 179
	TWarheadSpottyDamageComponent.new().CreateGrouped(Entity, [1])  # 180
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [1]).Name("Melee").TriggerOnDie().TriggerOnKillDone()  # 181
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [3], "Modifiers\\Banished.dws")  # 188
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [5], "Modifiers\\Banished.dws")  # 189
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [], "Modifiers\\LegendarySpawn.dws").PassIntValue(3300).ApplyToSelfAtCreate()  # 191
	TUnitPropertyComponent.new().CreateGrouped(Entity, [], [C.upHasLegendaryUnit]).GivePropertyOwner()  # 195
