# Generated by tools/transpile_scripts.py from Scripts\Units\Black\VoidSkeleton.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TStatisticsUnitComponent.new().Create(Entity)  # 27
	THealthComponent.new().Create(Entity)  # 29
	TArmorComponent.new().Create(Entity)  # 30
	TMovementComponent.new().Create(Entity)  # 31
	TThinkImpulseTimerComponent.new().Create(Entity)  # 32
	TBrainFollowLaneComponent.new().Create(Entity)  # 33
	TBrainActionComponent.new().CreateGroupedAll(Entity)  # 34
	TAutoBrainOnDeathComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).FireAtGround()  # 37
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).MustNotHave([C.upSoulless])  # 39
	TWelaEffectFactoryComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).PassCardValues()  # 41
	TPathfindingComponent.new().Create(Entity)  # 45

# Units\Black\VoidSkeleton.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.45  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecBlack)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier1, C.upUnit, C.upGround, C.upMelee, C.upHasUndying, C.upSoulGatherer])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atUnarmored)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 105.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 105.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reMana, 1)  # 13
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reMana, 0)  # 14
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 1.0)  # 17 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtMelee])  # 18
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 16.0)  # 19 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 1700)  # 20 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 266)  # 21
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 933)  # 22
	Entity.Blackboard.SetValue(C.eiWelaModifier, [2], 1.5)  # 25
	Entity.Blackboard.SetValue(C.eiWelaModifier, [3], 2.0)  # 26
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [4], C.reMana, 1)  # 29

# Units\Black\VoidSkeleton.ets:48
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 50
	InitUnitMeta(Entity)  # 51

# Units\Black\VoidSkeleton.ets:77
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 79
	InitUnitEntity(Entity)  # 80
	TBrainApproachComponent.new().CreateGrouped(Entity, [0])  # 83
	TWelaTargetingRadialAttentionComponent.new().CreateGrouped(Entity, [0]).SetTargetTeamConstraint(C.tcEnemies)  # 84
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [1]).Preemptive()  # 87
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [1], true)  # 89
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [1]).SetTargetTeamConstraint(C.tcEnemies)  # 90
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [0, 1], C.eiDamageable)  # 92
	TWelaTargetConstraintCompareUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).BothMustHaveAny([C.upGround, C.upFlying])  # 93
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).MustNotHave([C.upInvisible, C.upBanished])  # 95
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [1])  # 97
	TWarheadSpottyDamageComponent.new().CreateGrouped(Entity, [1])  # 98
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [1]).Name("Melee").TriggerOnDie().TriggerOnKillDone()  # 99
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [1]).Name("RelentlessFrozen").CheckUnitPropertyMustHave([C.upFrozen]).TriggerOnKillDone()  # 103
	TModifierMultiplyDealtDamageComponent.new().CreateGrouped(Entity, [1]).MustNotHave([C.dtSpell]).CheckWelaConstraint().SetValueGroup([2])  # 109
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [2]).MustHaveAny([C.upStunned, C.upBlinded, C.upRooted, C.upGrounded, C.upLifted, C.upBleeding, C.upPetrified]).MustNotHave([C.upFrozen])  # 113
	TModifierMultiplyDealtDamageComponent.new().CreateGrouped(Entity, [1]).MustNotHave([C.dtSpell]).CheckWelaConstraint().SetValueGroup([3])  # 116
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [3]).MustHave([C.upFrozen])  # 120
	TAutoBrainPreventDeathComponent.new().CreateGrouped(Entity, [4])  # 124
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [4]).MustNotHave([C.upSilenced, C.upRescued])  # 125
	TWelaReadyCostComponent.new().CreateGrouped(Entity, [4]).SetPayingGroup([])  # 127
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [4]).Name("SoulConsumed").TriggerOnFire()  # 129
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [4])  # 132
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [4]).Name("SoulgathererUndying").TriggerOnFire()  # 133
	TWelaEffectRemoveAfterUseComponent.new().CreateGrouped(Entity, [4]).TargetGroup([4])  # 136
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [4], "Modifiers\\Undying.dws")  # 141
