# Generated by tools/transpile_scripts.py from Scripts\Spells\Blue\EnergyRift.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\Blue\EnergyRift.dws:1
func Apply(Entity) -> void:
	var Group: int = 0  # 2
	var FireGroup: int = 0  # 2
	Group = Entity.ReserveFreeGroup()  # 4
	Entity.Blackboard.SetValue(C.eiCooldown, [Group], 30000)  # 5
	FireGroup = Entity.ReserveFreeGroup()  # 6
	Entity.Blackboard.SetValue(C.eiCooldown, [FireGroup], 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaDamage, [FireGroup], 24.0)  # 8
	Entity.Blackboard.SetValue(C.eiWelaRange, [FireGroup], 14.0)  # 9
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [FireGroup], "Projectiles\\Blue\\EnergyRiftProjectile")  # 10
	Entity.Blackboard.SetValue(C.eiDamageType, [FireGroup], [C.dtSpell])  # 11
	TBrainWelaSelftargetComponent.new().CreateGrouped(Entity, [Group]).ThinksPassively()  # 15
	TAutoBrainBuffComponent.new().CreateGrouped(Entity, [Group], [C.btPositive])  # 17
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [Group], false)  # 18
	TWelaEffectRemoveAfterUseComponent.new().CreateGrouped(Entity, [Group]).TargetGroup([Group, FireGroup])  # 19
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [FireGroup]).ThinksPassively()  # 22
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [FireGroup], true)  # 24
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [FireGroup]).SetTargetTeamConstraint(C.tcEnemies).PicksRandomTargets()  # 25
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [FireGroup]).MustNotHave([C.upInvisible, C.upBanished, C.upSpellImmune])  # 28
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [FireGroup], C.eiDamageable)  # 30
	TWelaEffectProjectileComponent.new().CreateGrouped(Entity, [FireGroup])  # 31
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upHasEnergyRift])  # 34
