# Generated by tools/transpile_scripts.py from Scripts\Spells\Blue\OrbitalStrikeBombardement.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\Blue\OrbitalStrikeBombardement.dws:3
func Apply(Entity) -> void:
	var EffectGroup: int = 0  # 4
	EffectGroup = Entity.ReserveFreeGroup()  # 6
	Entity.Blackboard.SetValue(C.eiCooldown, [EffectGroup], 174)  # 7
	Entity.Blackboard.SetValue(C.eiWelaDamage, [EffectGroup], 11.0)  # 8
	Entity.Blackboard.SetValue(C.eiDamageType, [EffectGroup], [C.dtSpell, C.dtSplash])  # 9
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [EffectGroup], 2.0)  # 10
	TThinkImpulseTimerCooldownComponent.new().CreateGrouped(Entity, [EffectGroup])  # 13
	TBrainWelaSelftargetComponent.new().CreateGrouped(Entity, [EffectGroup]).ThinksPassively()  # 14
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [EffectGroup], false)  # 16
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [EffectGroup]).MustHaveAny([C.upUnit, C.upBuilding]).MustNotHave([C.upBanished, C.upSpellImmune])  # 17
	TWelaTargetConstraintAlliesComponent.new().CreateGrouped(Entity, [EffectGroup])  # 20
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [EffectGroup], C.eiDamageable)  # 21
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [EffectGroup])  # 22
	TWarheadSplashDamageComponent.new().CreateGrouped(Entity, [EffectGroup])  # 23
	TWelaEffectRemoveAfterUseComponent.new().CreateGrouped(Entity, [EffectGroup])  # 25
