# Generated by tools/transpile_scripts.py from Scripts\Spells\Blue\OrbitalStrike.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\Blue\OrbitalStrike.dws:3
func Apply(Entity) -> void:
	var BombardementGroup: int = 0  # 4
	var SelfDamageGroup: int = 0  # 4
	var DurationGroup: int = 0  # 4
	BombardementGroup = Entity.ReserveFreeGroup()  # 6
	DurationGroup = Entity.ReserveFreeGroup()  # 7
	SelfDamageGroup = Entity.ReserveFreeGroup()  # 8
	Entity.Blackboard.SetValue(C.eiCooldown, [DurationGroup], 15000)  # 9
	Entity.Blackboard.SetValue(C.eiCooldown, [SelfDamageGroup], 500)  # 11
	Entity.Blackboard.SetValue(C.eiWelaDamage, [SelfDamageGroup], 13.0)  # 12
	Entity.Blackboard.SetValue(C.eiDamageType, [SelfDamageGroup], [C.dtSpell])  # 13
	Entity.Blackboard.SetValue(C.eiWelaRange, [BombardementGroup], 6.0)  # 15
	Entity.Blackboard.SetValue(C.eiCooldown, [BombardementGroup], 200)  # 16
	TBrainWelaSelftargetComponent.new().CreateGrouped(Entity, [DurationGroup]).ThinksPassively()  # 20
	TAutoBrainBuffComponent.new().CreateGrouped(Entity, [DurationGroup], [C.btDivine])  # 22
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [DurationGroup], false)  # 23
	TWelaEffectRemoveAfterUseComponent.new().CreateGrouped(Entity, [DurationGroup]).TargetGroup([DurationGroup, BombardementGroup, SelfDamageGroup])  # 24
	TBrainWelaSelftargetComponent.new().CreateGrouped(Entity, [SelfDamageGroup]).ThinksPassively()  # 27
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [SelfDamageGroup], true)  # 29
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [SelfDamageGroup])  # 30
	TWarheadSpottyDamageComponent.new().CreateGrouped(Entity, [SelfDamageGroup])  # 31
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [SelfDamageGroup]).Name("Spell").TriggerOnDamageDone()  # 32
	TThinkImpulseImmediateComponent.new().CreateGrouped(Entity, [BombardementGroup])  # 37
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [BombardementGroup]).DisableTargetLock().ThinksPassively()  # 38
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [BombardementGroup], false).Cooldown(1000).Once()  # 41
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [BombardementGroup], true)  # 44
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [BombardementGroup]).SetTargetTeamConstraint(C.tcAllies).PicksRandomTargets()  # 45
	TWelaTargetConstraintAlliesComponent.new().CreateGrouped(Entity, [BombardementGroup])  # 48
	TWelaTargetConstraintNotSelfComponent.new().CreateGrouped(Entity, [BombardementGroup])  # 49
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [BombardementGroup]).MustHaveAny([C.upUnit, C.upBuilding]).MustNotHave([C.upInvisible, C.upBanished, C.upSpellImmune])  # 50
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [BombardementGroup], C.eiDamageable)  # 53
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [BombardementGroup])  # 55
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [BombardementGroup], "Spells\\Blue\\OrbitalStrikeBombardement.dws")  # 58
