# Generated by tools/transpile_scripts.py from Scripts\Units\Golems\GolemsBigGolemTower.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\BuildingTemplate.dws:3
func InitBuildingData(Entity, LimitedLifeTime: bool = false) -> void:
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 12.0)  # 5
	if LimitedLifeTime:  # 8
		Entity.Blackboard.SetValue(C.eiCooldown, [C.GROUP_BUILDING_LIFETIME], 90000)  # 9
	Entity.Blackboard.SetValue(C.eiWelaRange, [C.GROUP_SOUL], 12.0)  # 11

# HelperScripts\BuildingTemplate.dws:23
func InitBuildingMeta(Entity) -> void:
	pass

# HelperScripts\BuildingTemplate.dws:32
func InitBaseBuildingEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 34
	TStatisticsUnitComponent.new().Create(Entity)  # 37
	TPositionComponent.new().Create(Entity)  # 39
	THealthComponent.new().Create(Entity)  # 40
	TArmorComponent.new().Create(Entity)  # 41
	TThinkImpulseTimerComponent.new().Create(Entity)  # 42
	TBrainActionComponent.new().CreateGroupedAll(Entity)  # 43
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, []).Name("BuildingToBasebuilding").TriggerOnDamageDone().CheckUnitPropertyMustHave([C.upBase])  # 45
	TPathfindingComponent.new().Create(Entity)  # 51

# HelperScripts\BuildingTemplate.dws:57
func InitBuildingEntity(Entity, LimitedLifeTime: bool = false) -> void:
	InitBaseBuildingEntity(Entity)  # 59
	if LimitedLifeTime:  # 62
		TWelaHelperBeaconComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME]).TriggerAt([C.upBuildingLimitedTime])  # 64
		TBrainWelaSelftargetGroundComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME])  # 66
		TWelaEffectSuicideComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME])  # 67
	if LimitedLifeTime:  # 71
		TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], false)  # 72

# Units\Golems\GolemsBigGolemTower.ets:3
func CreateData(Entity) -> void:
	InitBuildingData(Entity, true)  # 5
	Entity.CollisionRadius = 0.85  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecColorless)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier3, C.upGround, C.upBuilding, C.upRanged, C.upGolem])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atFortified)  # 10 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 570.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 570.0)  # 12 {@UBL_Health}
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 11.0)  # 15 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [1], 2)  # 16
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [0, 1], "Projectiles\\Colorless\\BigGolemTowerProjectile")  # 17
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 1700)  # 18 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtRanged])  # 19
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 68.0)  # 20 {@UBL_Damage}

# Units\Golems\GolemsBigGolemTower.ets:32
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 34
	InitBuildingMeta(Entity)  # 35

# Units\Golems\GolemsBigGolemTower.ets:71
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 73
	InitBuildingEntity(Entity, true)  # 74
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [1]).Preemptive()  # 77
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [1], true)  # 79
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [1]).SetTargetTeamConstraint(C.tcEnemies)  # 80
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).MustNotHave([C.upInvisible, C.upBanished])  # 82
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [0, 1], C.eiDamageable)  # 84
	TWelaEffectProjectileComponent.new().CreateGrouped(Entity, [1])  # 85
