# Generated by tools/transpile_scripts.py from Scripts\Modifiers\BlessingEnergy.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\BlessingEnergy.dws:3
func Apply(Entity) -> void:
	var EnergyRegenerationGroup: int = 0  # 4
	var EnergyGroup: int = 0  # 4
	var Group: int = 0  # 4
	Group = Entity.ReserveFreeGroup()  # 6
	EnergyGroup = Entity.ReserveFreeGroup()  # 7
	EnergyRegenerationGroup = Entity.ReserveFreeGroup()  # 8
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [EnergyRegenerationGroup], C.reWelaCharge, 4)  # 9
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [EnergyRegenerationGroup], C.reWelaCharge, 4)  # 10
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [EnergyRegenerationGroup], C.reWelaCharge, 1)  # 11
	Entity.Blackboard.SetValue(C.eiWelaDamage, [EnergyRegenerationGroup], 1.0)  # 12
	Entity.Blackboard.SetValue(C.eiCooldown, [EnergyRegenerationGroup], 3000)  # 13
	Entity.Blackboard.SetValue(C.eiWelaDamage, [EnergyGroup], 2.0)  # 14
	TAutoBrainBuffComponent.new().CreateGrouped(Entity, [Group], [C.btPositive])  # 17
	TWelaEffectRemoveAfterUseComponent.new().CreateGrouped(Entity, [Group]).TargetGroup([Group, EnergyRegenerationGroup, EnergyGroup])  # 18
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [Group]).Name("Enchanted").Name("FluxField").TriggerOnTakeDamage()  # 21
	TModifierResourceComponent.new().CreateGrouped(Entity, [EnergyGroup]).DontFillCap().Resource(C.reMana).ApplyNow()  # 27
	TBrainWelaSelftargetComponent.new().CreateGrouped(Entity, [EnergyRegenerationGroup]).ThinksPassively()  # 33
	TWelaReadyResourceCompareComponent.new().CreateGrouped(Entity, [EnergyRegenerationGroup]).ComparedResource(C.reMana).CheckNotFull()  # 35
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [EnergyRegenerationGroup], false)  # 38
	TWelaReadyCostComponent.new().CreateGrouped(Entity, [EnergyRegenerationGroup]).SetPayingGroup([EnergyRegenerationGroup])  # 39
	TWelaEffectPayCostComponent.new().CreateGrouped(Entity, [EnergyRegenerationGroup]).SetPayingGroup([EnergyRegenerationGroup])  # 41
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [EnergyRegenerationGroup])  # 43
	TWarheadSpottyResourceComponent.new().CreateGrouped(Entity, [EnergyRegenerationGroup]).SetResourceType(C.reMana).TargetGroup([])  # 44
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upBlessed, C.upBlessedEnergy])  # 49
