# Generated by tools/transpile_scripts.py from Scripts\Modifiers\BlessingStrengthIncoming.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\BlessingStrengthIncoming.dws:3
func Apply(Entity) -> void:
	var Group: int = 0  # 4
	Group = Entity.ReserveFreeGroup()  # 6
	TAutoBrainBuffComponent.new().CreateGrouped(Entity, [Group], [C.btPositive])  # 9
	TWelaEffectRemoveAfterUseComponent.new().CreateGrouped(Entity, [Group]).TargetGroup([Group])  # 10
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upBlessedStrength])  # 14
