# Generated by tools/transpile_scripts.py from Scripts\Modifiers\Death.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\Death.dws:3
func Apply(Entity) -> void:
	pass
