# Generated by tools/transpile_scripts.py from Scripts\Modifiers\Grounded.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\Grounded.dws:3
func Apply(Entity):
	var Result: int = 0
	var GROUND_DURATION: int = 15000  # 4
	var Group: int = 0  # 5
	var ImmuneGroup: int = 0  # 5
	Group = Entity.ReserveFreeGroup()  # 7
	Result = Group  # 8
	ImmuneGroup = Entity.ReserveFreeGroup()  # 9
	Entity.Blackboard.SetValue(C.eiCooldown, [Group], GROUND_DURATION)  # 10
	Entity.Blackboard.SetValue(C.eiCooldown, [ImmuneGroup], GROUND_DURATION + 10000)  # 11
	Entity.Eventbus.Trigger(C.eiStand, [])  # 15
	TBrainWelaSelftargetComponent.new().CreateGrouped(Entity, [Group]).ThinksPassively()  # 17
	TAutoBrainBuffComponent.new().CreateGrouped(Entity, [Group], [C.btNegative, C.btState])  # 19
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [Group], false)  # 20
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [Group])  # 21
	TWelaEffectRemoveAfterUseComponent.new().CreateGrouped(Entity, [Group]).TargetGroup([Group])  # 22
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [Group]).Name("Grounded").TriggerOnKilled()  # 24
	TBrainWelaSelftargetComponent.new().CreateGrouped(Entity, [ImmuneGroup]).ThinksPassively()  # 29
	TAutoBrainBuffComponent.new().CreateGrouped(Entity, [ImmuneGroup], [C.btDivine])  # 31
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [ImmuneGroup], false)  # 32
	TWelaEffectRemoveAfterUseComponent.new().CreateGrouped(Entity, [ImmuneGroup])  # 33
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upFlying]).Remove()  # 36
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upGround])  # 38
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upHasStateEffect, C.upGrounded])  # 39
	TUnitPropertyComponent.new().CreateGrouped(Entity, [ImmuneGroup], [C.upImmuneToGrounded])  # 40
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [Group], "Modifiers\\GroundedEnds.dws")  # 42
	return Result

# Modifiers\Grounded.dws:58
func ApplyGreen(Entity) -> void:
	var Group: int = 0  # 59
	Group = Apply(Entity)  # 61

# Modifiers\Grounded.dws:76
func ApplyBlue(Entity) -> void:
	var Group: int = 0  # 77
	Group = Apply(Entity)  # 79
