# Generated by tools/transpile_scripts.py from Scripts\Modifiers\ImmuneToGuarded.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\ImmuneToGuarded.dws:3
func Apply(Entity) -> void:
	var Group: int = 0  # 4
	Group = Entity.ReserveFreeGroup()  # 6
	Entity.Blackboard.SetValue(C.eiCooldown, [Group], 60000)  # 7
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upImmuneToGuarded])  # 10
	TBrainWelaSelftargetComponent.new().CreateGrouped(Entity, [Group])  # 12
	TAutoBrainBuffComponent.new().CreateGrouped(Entity, [Group], [C.btDivine])  # 13
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [Group], false)  # 14
	TWelaEffectRemoveAfterUseComponent.new().CreateGrouped(Entity, [Group])  # 15
