# Generated by tools/transpile_scripts.py from Scripts\Modifiers\ImmuneToPotion.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\ImmuneToPotion.dws:3
func Apply(Entity) -> void:
	var Group: int = 0  # 4
	Group = Entity.ReserveFreeGroup()  # 6
	TAutoBrainBuffComponent.new().CreateGrouped(Entity, [Group], [C.btDivine])  # 9
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upHasDrunkPotion])  # 12
