# Generated by tools/transpile_scripts.py from Scripts\Modifiers\Lifted.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\Lifted.dws:3
func Apply(Entity) -> void:
	var LIFT_DURATION: int = 15000  # 4
	var Group: int = 0  # 5
	var EffectEndGroup: int = 0  # 5
	var ImmuneGroup: int = 0  # 5
	Group = Entity.ReserveFreeGroup()  # 7
	EffectEndGroup = Entity.ReserveFreeGroup()  # 8
	ImmuneGroup = Entity.ReserveFreeGroup()  # 9
	Entity.Blackboard.SetValue(C.eiCooldown, [Group], LIFT_DURATION)  # 10
	Entity.Blackboard.SetValue(C.eiCooldown, [ImmuneGroup], LIFT_DURATION + 10000)  # 11
	Entity.Eventbus.Trigger(C.eiStand, [])  # 15
	TBrainWelaSelftargetComponent.new().CreateGrouped(Entity, [Group]).ThinksPassively()  # 17
	TAutoBrainBuffComponent.new().CreateGrouped(Entity, [Group], [C.btNegative, C.btState])  # 19
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [Group], false)  # 20
	TWelaEffectFireComponent.new().CreateGrouped(Entity, [Group]).TargetGroup([EffectEndGroup])  # 21
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [Group])  # 23
	TWelaEffectRemoveAfterUseComponent.new().CreateGrouped(Entity, [Group]).TargetGroup([Group])  # 24
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [Group]).Name("Lifted").TriggerOnKilled()  # 26
	TBrainWelaSelftargetComponent.new().CreateGrouped(Entity, [ImmuneGroup]).ThinksPassively()  # 31
	TAutoBrainBuffComponent.new().CreateGrouped(Entity, [ImmuneGroup], [C.btDivine])  # 33
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [ImmuneGroup], false)  # 34
	TWelaEffectRemoveAfterUseComponent.new().CreateGrouped(Entity, [ImmuneGroup]).TargetGroup([EffectEndGroup, ImmuneGroup])  # 35
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upGround]).Remove()  # 39
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upFlying])  # 41
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upHasStateEffect, C.upLifted])  # 42
	TUnitPropertyComponent.new().CreateGrouped(Entity, [ImmuneGroup], [C.upImmuneToLifted])  # 43
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [Group], "Modifiers\\LiftedEnds.dws")  # 45
