# Generated by tools/transpile_scripts.py from Scripts\Modifiers\ProjectileReflectorProjectile.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\ProjectileReflectorProjectile.dws:3
func Apply(Entity) -> void:
	var Group: int = 0  # 4
	Group = Entity.ReserveFreeGroup()  # 6
	Entity.Blackboard.SetValue(C.eiWelaModifier, [Group], 0.4)  # 7
	TModifierWelaDamageComponent.new().CreateGrouped(Entity, [0]).Multiply().SetValueGroup([Group])  # 10
	TModifierDamageTypeComponent.new().CreateGrouped(Entity, [0]).Add([C.dtReflected])  # 15
