# Generated by tools/transpile_scripts.py from Scripts\Modifiers\SummoningSickness.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\SummoningSickness.dws:3
func Apply(Entity, Duration: int) -> void:
	var Group: int = 0  # 4
	Group = Entity.ReserveFreeGroup()  # 6
	Entity.Blackboard.SetValue(C.eiCooldown, [Group], Duration)  # 7
	TThinkImpulseTimerComponent.new().CreateGrouped(Entity, [Group])  # 10
	TBrainWelaSelftargetComponent.new().CreateGrouped(Entity, [Group]).ThinksPassively()  # 12
	TAutoBrainBuffComponent.new().CreateGrouped(Entity, [Group], [C.btSummoningSickness])  # 14
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [Group], false)  # 15
	TWelaEffectRemoveAfterUseComponent.new().CreateGrouped(Entity, [Group])  # 16
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upSummoningSickness])  # 19
