# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Neutral\LanetowerBaseProjectile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Neutral\LanetowerBaseProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(20) / 1000)  # 5
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtTrue, C.dtRanged, C.dtSplash])  # 7
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1, 2], L.f([25.0, 25.0, 30.0, 30.0, 30.0], Entity.CardLeague()))  # 8

# Projectiles\Neutral\LanetowerBaseProjectile.ets:11
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 13
	TParticleEffectComponent.new().Create(Entity, "\\Neutral\\tower_projectile.pfx", 8.0).ActivateOnCreate()  # 16
	TPointLightComponent.new().Create(Entity, 704708607, 0.0).SetLightShape(Vector3(2, 10, 0))  # 18

# Projectiles\Neutral\LanetowerBaseProjectile.ets:23
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 25
	TPositionerSplineComponent.new().Create(Entity).BothTangents(PI / 16, 0.0, 1.0).OrientStartWithTarget().BindToSubPosition(C.BIND_ZONE_WEAPON_MUZZLE, [2])  # 40
	TSoundComponent.new().Create(Entity, "event:/env/building/lane_tower/attack_impact").TriggerOnFree()  # 45
	TParticleEffectComponent.new().CreateGrouped(Entity, [1], "\\Neutral\\neutral_border_once.pfx", 5.0).ActivateOnFireWarhead().FixedOrientationDefault().ScaleWith(C.eiWelaAreaOfEffect).FixedOffsetGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 48
