# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Neutral\LaneTowerAntiNexusProjectile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Neutral\LaneTowerAntiNexusProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(40) / 1000)  # 5

# Projectiles\Neutral\LaneTowerAntiNexusProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10
	TParticleEffectComponent.new().Create(Entity, "\\Neutral\\tower_projectile.pfx", 6.0).ActivateOnCreate()  # 13
	TParticleEffectComponent.new().Create(Entity, "\\Neutral\\tower_nexus_shot_projectile.pfx", 8.5).ActivateOnCreate()  # 15
	TPointLightComponent.new().Create(Entity, 704708607, 0.0).SetLightShape(Vector3(4, 10, 0))  # 17

# Projectiles\Neutral\LaneTowerAntiNexusProjectile.ets:22
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 24
	TPositionerSplineComponent.new().Create(Entity).BothTangents(((PI / 2) * 7) / 8, 0.0, 1.0).OrientStartWithTarget().BindToSubPosition(C.BIND_ZONE_WEAPON_MUZZLE, [2])  # 36
	TSoundComponent.new().Create(Entity, "event:/env/building/lane_tower/nexus_buster_impact").TriggerOnFree()  # 41
	TCameraShakerComponent.new().CreateGrouped(Entity, []).RotationShaker(0.005, 0.005, 0.02).Duration(500).Waves(8).ActivateOnFree().Global()  # 44
	TCameraShakerComponent.new().CreateGrouped(Entity, []).VectorShaker(0.0, -1.0, 0.0).Strength(0.2).Duration(500).Waves(4).ActivateOnFree().Global()  # 51
