# Generated by tools/transpile_scripts.py from Scripts\Units\Black\VoidBane.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 12
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapUnitIcon.png")  # 13

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TPathfindingComponent.new().Create(Entity)  # 45
	TOrienterMovementComponent.new().Create(Entity)  # 48
	TOrienterTargetComponent.new().CreateGrouped(Entity, [0, 1])  # 49
	TOrienterSmoothRotateComponent.new().Create(Entity).SetAngleSpeed(0.008)  # 50
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 53
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 54
	TShowOnMinimapComponent.new().Create(Entity)  # 56

# Units\Black\VoidBane.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.7  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecBlack)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier1, C.upUnit, C.upGround, C.upMelee, C.upSoulGatherer, C.upHasDeathRattle])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atUnarmored)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 190.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 190.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reMana, 14)  # 13
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reMana, 0)  # 14
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 0.5 + 1.0)  # 17 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtMelee, C.dtSplash])  # 18
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 27.0)  # 19 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 2300)  # 20 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [1], 2.5)  # 21
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffectCone, [1], 3.141 * 0.9)  # 22
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 333)  # 23
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 1133)  # 24
	Entity.Blackboard.SetValue(C.eiWelaDamage, [2], 15.0)  # 27
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [3], 0)  # 30
	Entity.Blackboard.SetValue(C.eiWelaModifier, [3], 1)  # 31
	Entity.Blackboard.SetValue(C.eiWelaRange, [3], 8.0)  # 32
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [3], "Projectiles\\Black\\SoulDonorProjectileVoidBane")  # 33
	Entity.Blackboard.SetValue(C.eiWelaDamage, [3], 1.0)  # 34
	Entity.Blackboard.SetValue(C.eiDamageType, [3], [C.dtIrredirectable])  # 35
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "Cleave")  # 38
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [], "SoulGatherer").PassInteger("energy_amount", 1, "energy")  # 39
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [2], "SoulGathererReaper").PassInteger("energy_amount", 1, "energy").PassInteger("health_amount", 15, "health")  # 41
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [3], "DeathRattleSoulDonor")  # 44
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaAttack, 4)  # 46
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaDefense, 6)  # 47
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaUtility, 2)  # 48

# Units\Black\VoidBane.ets:52
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 54
	InitUnitMeta(Entity)  # 55
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(-0.2, 0, 0), Vector3(-0.2, 1.8, 0), 0.90)  # 58
	TMeshComponent.new().CreateGrouped(Entity, [0, 1], ("Units\\Black\\VoidBane" + Entity.SkinFileSuffix()) + "\\VoidBane.xml").ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_WALK, 0, 60).CreateNewAnimation(C.ANIMATION_ATTACK, 60, 93).CreateNewAnimation(C.ANIMATION_STAND, 94, 154).IgnoreScalingForAnimations().BindZoneToBone(C.BIND_ZONE_CENTER, "VoidbaneSpine3").BindZoneToBone(C.BIND_ZONE_HEAD, "VoidbaneHead").BindZoneToBone(C.BIND_ZONE_WEAPON, "VoidbaneWeaponBlade").BoneSwapXY(C.BIND_ZONE_WEAPON).BoneInvertY(C.BIND_ZONE_WEAPON)  # 60
	if Entity.SkinID == C.SKIN_GROUP_CRUSADER:  # 72
		TMeshEffectMetal.new().Create().ShowAsColor(C.ecWhite).AssignToEntity(Entity)  # 74
	TAnimationComponent.new().CreateGrouped(Entity, [0, 1])  # 79
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [1.4], [0])  # 80

# Units\Black\VoidBane.ets:84
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 86
	InitUnitEntity(Entity)  # 87
	TResourceDisplayIntegerProgressBarComponent.new().Create(Entity).ShowResource(C.reMana).HideIfEmpty()  # 147
	TVertexTraceComponent.new().CreateGrouped(Entity, [1]).Texture(("Units\\Black\\VoidBane" + Entity.SkinFileSuffix()) + "\\ScytheTrace.tga").Color(2701131775).Width(1.0).SamplingDistance(0.2).FadeLength(3.0).MaxLength(6.0).TexturePerDistance(4.0).RollUpSpeed(10.0).ActivateOnFire().DeactivateAfterTime(233).DeactivateOnMoveTo().BindToSubPositionGroup(C.BIND_ZONE_WEAPON, [0, 1])  # 151
	TSoundComponent.new().CreateGrouped(Entity, [1], "event:/card/black/unit/voidbane/attack_fire").TriggerOnPreFire().StopOnFree()  # 165
	TParticleEffectComponent.new().CreateGrouped(Entity, [2], "\\Black\\void_bane_reaper.pfx", 1.0).ActivateOnFire().BindToSubPositionGroup(C.BIND_ZONE_CENTER, [0, 1])  # 169
	TSoundComponent.new().CreateGrouped(Entity, [2], "event:/card/black/unit/voidbane/reaper_trigger").TriggerOnFire()  # 173
	TParticleEffectComponent.new().CreateGrouped(Entity, [3], "\\Black\\void_bane_soul_donor.pfx", 1.2).ActivateOnFire().BindToSubPositionGroup(C.BIND_ZONE_CENTER, [0, 1])  # 176
	TSoundComponent.new().CreateGrouped(Entity, [3], "event:/card/black/unit/voidbane/death_cry_trigger").TriggerOnFire()  # 180
	TCameraShakerComponent.new().CreateGrouped(Entity, [3]).PresetRotationLight().ActivateOnFire()  # 183
	TCameraShakerComponent.new().CreateGrouped(Entity, [3]).PresetVectorLight().ActivateOnFire()  # 187
	TSoundComponent.new().CreateGrouped(Entity, [3], "event:/card/shared/effect/energy_donor").TriggerOnFire()  # 191
