# Generated by tools/transpile_scripts.py from Scripts\Units\Black\VoidBaneDrop.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\CardTemplate.dws:3
func GetCardBaseCost(Tier: int, League: int, Level: int, IsLegendary: bool, IsSpell: bool, IsSpawner: bool):
	var Result: float = 0.0
	Result = 100.0  # 5
	if Tier == 2:  # 7
		Result = Result + 50  # 8
	elif Tier == 3:  # 9
		Result = Result + 100  # 10
	if IsLegendary:  # 12
		Result = Result + 100  # 13
	if IsSpell:  # 15
		Result = Result - 20  # 16
	if IsSpawner:  # 18
		Result = Result * L.i([8, 10, 12], Tier)  # 19
	return Result

# HelperScripts\CardTemplate.dws:22
func GetCardBaseChargeCooldown(Tier: int, League: int, Level: int, IsLegendary: bool, IsSpell: bool, IsSpawner: bool):
	var Result: int = 0
	Result = L.ii([[37000, 36250, 35500, 34750, 34000], [34000, 33250, 32500, 31750, 31000], [31000, 30250, 29500, 28750, 28000], [28000, 27250, 26500, 25750, 25000], [25000, 24250, 23500, 22750, 22000]], League, Level)  # 24
	if Tier == 2:  # 31
		Result = L.Div((Result * 3), 2)  # 32
	elif Tier == 3:  # 33
		Result = Result * 2  # 34
	if IsLegendary:  # 36
		Result = L.Div((Result * 5), 2)  # 37
	if IsSpawner:  # 39
		Result = Result * L.i([6, 7, 8], Tier)  # 40
	return Result

# HelperScripts\CardTemplate.dws:43
func InitCardData(Entity, Group: Array, ChargeGroup: Array, IsLegendary: bool, IsSpawner: bool, IsSpell: bool, Tier: int) -> void:
	var ChargeCount: int = 0  # 44
	var Cooldown: int = 0  # 44
	var Cost: float = 0.0  # 45
	Cost = GetCardBaseCost(Tier, Entity.CardLeague(Group), Entity.CardLevel(Group), IsLegendary, IsSpell, IsSpawner)  # 47
	Cooldown = GetCardBaseChargeCooldown(Tier, Entity.CardLeague(Group), Entity.CardLevel(Group), IsLegendary, IsSpell, IsSpawner)  # 48
	if Tier == 1:  # 50
		ChargeCount = L.i([1, 2, 3, 4, 5], Entity.CardLeague(Group))  # 51
	elif Tier == 2:  # 52
		ChargeCount = L.i([1, 1, 2, 3, 4], Entity.CardLeague(Group))  # 53
	elif Tier == 3:  # 54
		ChargeCount = L.i([1, 1, 1, 2, 3], Entity.CardLeague(Group))  # 55
	if IsLegendary:  # 57
		ChargeCount = L.i([1, 1, 1, 1, 2], Entity.CardLeague(Group))  # 58
	if IsSpawner:  # 60
		Entity.Blackboard.SetIndexedValue(C.eiResourceCost, Group, C.reWood, Cost)  # 62
		Entity.Blackboard.SetIndexedValue(C.eiResourceCost, Group, C.reTier, 1)  # 63
	else:
		Entity.Blackboard.SetIndexedValue(C.eiResourceCost, Group, C.reGold, Cost)  # 67
		Entity.Blackboard.SetIndexedValue(C.eiResourceCost, Group, C.reTier, Tier)  # 68
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, Group, C.reCharge, 1)  # 70
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, Group, C.reCharge, ChargeCount)  # 71
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, Group, C.reCharge, ChargeCount)  # 72
	Entity.Blackboard.SetValue(C.eiCooldown, ChargeGroup, Cooldown)  # 73
	if IsLegendary:  # 75
		TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, Group).ChecksCommander().MustNotHave([C.upHasLegendaryUnit])  # 77

# HelperScripts\DropTemplate.dws:3
func InitDropData(Entity, IsLegendary: bool, Tier: int) -> void:
	InitCardData(Entity, [], [], IsLegendary, false, false, Tier)  # 5
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upDrop])  # 14
	TWelaEventRedirecter.new().CreateGrouped(Entity, [C.GROUP_DROP_SPAWNER])  # 17

# HelperScripts\DropTemplate.dws:21
func InitDropMeta(Entity) -> void:
	TProductionPreviewComponent.new().CreateGrouped(Entity, [C.GROUP_DROP_SPAWNER])  # 24
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [C.GROUP_DROP_SPAWNER], 3.0)  # 25
	TTextureRangeIndicatorComponent.new().CreateGrouped(Entity, [C.GROUP_DROP_SPAWNER])  # 26

# HelperScripts\DropTemplate.dws:30
func InitDropEntity(Entity, HasOwnSpawnEffect: bool = false) -> void:
	var SoundKey: String = ""  # 32
	var ColorIdentity: int = 0  # 33
	if not HasOwnSpawnEffect:  # 45
		TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [C.GROUP_DROP_SPAWNER], "Modifiers\\SummoningSickness.dws").ApplyToProducedUnits().PassIntValue(1000)  # 46
	if not HasOwnSpawnEffect:  # 51
		TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [C.GROUP_DROP_SPAWNER], "Modifiers\\Drop.dws").ApplyToProducedUnits()  # 53
		ColorIdentity = Entity.ColorIdentity([C.GROUP_DROP_SPAWNER])  # 56
		if ColorIdentity == C.ecGreen:  # 57
			if Entity.ReadCollisionRadius([C.GROUP_DROP_SPAWNER]) > 0.7:  # 59
				SoundKey = "event:/card/green/drop_big"  # 60
			else:
				SoundKey = "event:/card/green/drop_small"  # 62
		elif ColorIdentity == C.ecBlack:  # 64
			SoundKey = "event:/card/black/drop"  # 65
		elif ColorIdentity == C.ecBlue:  # 66
			SoundKey = "event:/card/blue/drop"  # 67
		elif ColorIdentity == C.ecColorless:  # 68
			SoundKey = "event:/card/colorless/drop"  # 69
		else:
			SoundKey = "event:/card/white/drop"  # 71
		TSoundComponent.new().CreateGrouped(Entity, [C.GROUP_DROP_SPAWNER], SoundKey).TriggerOnFire()  # 72
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [C.GROUP_DROP_SPAWNER], "Modifiers\\Death.dws").ApplyToProducedUnits()  # 76

# Units\Black\VoidBaneDrop.ets:3
func CreateData(Entity) -> void:
	InitDropData(Entity, false, 1)  # 5 {@UBL_Tier}
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_DROP_SPAWNER], "Units\\Black\\VoidBane")  # 7
	Entity.Blackboard.SetValue(C.eiWelaCount, [C.GROUP_DROP_SPAWNER], 1)  # 8 {@UBL_SquadSize}

# Units\Black\VoidBaneDrop.ets:11
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 13
	InitDropMeta(Entity)  # 14

# Units\Black\VoidBaneDrop.ets:20
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 22
	InitDropEntity(Entity)  # 23
