# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Blue\AmmoFactoryProjectile.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Blue\AmmoFactoryProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(10) / 1000)  # 5

# Projectiles\Blue\AmmoFactoryProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10

# Projectiles\Blue\AmmoFactoryProjectile.ets:36
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 38
	TMovementComponent.new().Create(Entity)  # 41
	TBrainProjectileComponent.new().CreateGrouped(Entity, [0])  # 42
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [0])  # 43
	TWarheadSpottyResourceComponent.new().CreateGrouped(Entity, [0]).SetResourceType(C.reMana)  # 44
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [0]).Name("SoulDonor").TriggerOnFire()  # 46
