# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Blue\InductionerProjectile.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Blue\InductionerProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(44) / 1000)  # 5

# Projectiles\Blue\InductionerProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10

# Projectiles\Blue\InductionerProjectile.ets:34
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 36
	TMovementComponent.new().Create(Entity)  # 39
	TBrainProjectileComponent.new().CreateGrouped(Entity, [0]).NoTargetChecks()  # 40
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [0])  # 42
	TWarheadSpottyDamageComponent.new().CreateGrouped(Entity, [0])  # 43
