# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Blue\MissileTowerMissile.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")

var InheritsFromPreceding: String = "Projectiles\\Blue\\Missile.ets"  # Projectiles\Blue\MissileTowerMissile.ets:3

# Projectiles\Blue\MissileTowerMissile.ets:5
func CreateData(Entity) -> void:
	pass

# Projectiles\Blue\MissileTowerMissile.ets:9
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 11

# Projectiles\Blue\MissileTowerMissile.ets:19
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 21
