# Generated by tools/transpile_scripts.py from Scripts\Modifiers\BlessingHealth.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\BlessingHealth.dws:3
func Apply(Entity) -> void:
	var HealthGroup: int = 0  # 4
	var Group: int = 0  # 4
	Group = Entity.ReserveFreeGroup()  # 6
	HealthGroup = Entity.ReserveFreeGroup()  # 7
	Entity.Blackboard.SetValue(C.eiWelaDamage, [HealthGroup], 0.3)  # 8
	Entity.Blackboard.SetValue(C.eiWelaModifier, [HealthGroup], 50.0)  # 9
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upBlessed, C.upBlessedHealth])  # 29
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\Green\\blessing_health_buff.pfx", 3.0).ActivateNow().ActivateOnCreate().ScaleWith(C.eiCollisionRadius)  # 32
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\Green\\blessing_health_apply.pfx", 1.1).ActivateNow().FixedHeightGround().FixedOrientationDefault().ScaleWith(C.eiCollisionRadius)  # 37
	TVisualModificatorSizeComponent.new().CreateGrouped(Entity, [0, 1, 2, 3, 4, 5, 6, 7, 8, Group]).Keypoints([1.0, 0.9, 1.25, 1.1]).KeypointsY([1.0, 1.4, 1.0, 1.1]).TimeKeys([0, 100, 250, 300]).Duration(300)  # 43
	TMeshEffectTint.new().Create(300, 4293722053).AddKey(0, 0.0).AddKey(100, 1.0).AddKey(300, 0.0).AssignToEntity(Entity)  # 49
