# Generated by tools/transpile_scripts.py from Scripts\Modifiers\BlessingArmor.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\BlessingArmor.dws:3
func Apply(Entity) -> void:
	var Group: int = 0  # 4
	Group = Entity.ReserveFreeGroup()  # 6
	Entity.Blackboard.SetValue(C.eiWelaModifier, [Group], 1)  # 7
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upBlessed, C.upBlessedArmor])  # 18
	TModifierArmorTypeComponent.new().CreateGrouped(Entity, [Group]).Increase()  # 20
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\White\\blessed_armor_buff.pfx", 0.6).ActivateNow().ActivateOnCreate().FixedOrientationDefault().ScaleWith(C.eiCollisionRadius).BindToSubPositionGroup(C.BIND_ZONE_CENTER, [0, 1])  # 24
