# Generated by tools/transpile_scripts.py from Scripts\Modifiers\Blind.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\Blind.dws:3
func Apply(Entity) -> void:
	var BLIND_DURATION: int = 12000  # 4
	var BLIND_IMMUNITY_DURATION: int = 10000  # 5
	var Group: int = 0  # 6
	var BlindGroup: int = 0  # 6
	var ImmuneGroup: int = 0  # 6
	Group = Entity.ReserveFreeGroup()  # 8
	BlindGroup = Entity.ReserveFreeGroup()  # 9
	ImmuneGroup = Entity.ReserveFreeGroup()  # 10
	Entity.Blackboard.SetValue(C.eiCooldown, [Group], BLIND_DURATION)  # 11
	Entity.Blackboard.SetValue(C.eiCooldown, [ImmuneGroup], BLIND_DURATION + BLIND_IMMUNITY_DURATION)  # 12
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group, BlindGroup], [C.upHasStateEffect, C.upBlinded])  # 39
	TUnitPropertyComponent.new().CreateGrouped(Entity, [ImmuneGroup], [C.upImmuneToBlinded])  # 40
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\Shared\\Blinded.pfx", 2.0).ActivateNow().ActivateOnCreate().ScaleWith(C.eiCollisionRadius).BindToSubPositionGroup(C.BIND_ZONE_HEAD, [0, 1])  # 43
	TParticleEffectComponent.new().CreateGrouped(Entity, [BlindGroup], "\\Shared\\Miss.pfx", 3.0).ActivateOnFire().BindToSubPositionGroup(C.BIND_ZONE_TOP, [0, 1])  # 49
