# Generated by tools/transpile_scripts.py from Scripts\Modifiers\CrystalPowerFireSpark.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\CrystalPowerFireSpark.dws:3
func Apply(Entity) -> void:
	var Group: int = 0  # 4
	Group = Entity.ReserveFreeGroup()  # 6
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [Group], "Modifiers\\CrystalPowerSpark.dws").PassValueFromEvent(C.eiTeamID).PassValueFromEvent(C.eiFront)  # 14
