# Generated by tools/transpile_scripts.py from Scripts\Modifiers\Grounded.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\Grounded.dws:3
func Apply(Entity):
	var Result: int = 0
	var GROUND_DURATION: int = 15000  # 4
	var Group: int = 0  # 5
	var ImmuneGroup: int = 0  # 5
	Group = Entity.ReserveFreeGroup()  # 7
	Result = Group  # 8
	ImmuneGroup = Entity.ReserveFreeGroup()  # 9
	Entity.Blackboard.SetValue(C.eiCooldown, [Group], GROUND_DURATION)  # 10
	Entity.Blackboard.SetValue(C.eiCooldown, [ImmuneGroup], GROUND_DURATION + 10000)  # 11
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upFlying]).Remove()  # 36
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upGround])  # 38
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upHasStateEffect, C.upGrounded])  # 39
	TUnitPropertyComponent.new().CreateGrouped(Entity, [ImmuneGroup], [C.upImmuneToGrounded])  # 40
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [Group], "Modifiers\\GroundedEnds.dws")  # 42
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\Shared\\grounded.pfx", 1.0).ActivateNow().ScaleWith(C.eiCollisionRadius).FixedHeightGround().FixedOrientationDefault()  # 45
	TPositionerOffsetComponent.new().CreateGrouped(Entity, [Group]).TargetGroup([]).Offset(0.0, -C.FLYING_HEIGHT, 0.0).Transition(500)  # 51
	return Result

# Modifiers\Grounded.dws:58
func ApplyGreen(Entity) -> void:
	var Group: int = 0  # 59
	Group = Apply(Entity)  # 61
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\Green\\spore_grounded.pfx", 0.7).ActivateNow().ActivateOnCreate().ScaleWith(C.eiCollisionRadius).BindToSubPositionGroup(C.BIND_ZONE_CENTER, [0, 1]).FixedOrientationDefault()  # 64
	TSoundComponent.new().CreateGrouped(Entity, [Group], "event:/card/green/effect/grounded").TriggerNow()  # 71

# Modifiers\Grounded.dws:76
func ApplyBlue(Entity) -> void:
	var Group: int = 0  # 77
	Group = Apply(Entity)  # 79
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\Blue\\inverse_gravity_grounded.pfx", 0.6).ActivateNow().ActivateOnCreate().ScaleWith(C.eiCollisionRadius).BindToSubPositionGroup(C.BIND_ZONE_CENTER, [0, 1]).FixedOrientationDefault()  # 82
	TSoundComponent.new().CreateGrouped(Entity, [Group], "event:/card/blue/effect/grounded").TriggerNow()  # 89
