# Generated by tools/transpile_scripts.py from Scripts\Modifiers\Invincibility.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\Invincibility.dws:3
func ApplyRaw(Entity):
	var Result: int = 0
	Result = Entity.ReserveFreeGroup()  # 5
	Entity.Blackboard.SetValue(C.eiCooldown, [Result], 2000)  # 6
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Result], [C.upInvincible])  # 17
	return Result

# Modifiers\Invincibility.dws:23
func Apply(Entity) -> void:
	var Group: int = 0  # 24
	Group = ApplyRaw(Entity)  # 26
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\White\\Invincible.pfx", 0.3).ActivateNow().ActivateOnCreate().ScaleWith(C.eiCollisionRadius).BindToSubPositionGroup(C.BIND_ZONE_CENTER, [0, 1])  # 29
	TMeshEffectComponent.new().CreateGrouped(Entity, [Group]).TargetGroup([]).SetEffect(TMeshEffectGlow.new().Create(2000).FixedColorIdentity(C.ecWhite).AddKey(0, 0.1).AddKey(2000 - 500, 0.1).AddKey(2000, 0.0))  # 35
	TSoundComponent.new().CreateGrouped(Entity, [Group], "event:/card/white/effect/invincible").TriggerNow()  # 45

# Modifiers\Invincibility.dws:50
func ApplyBlue(Entity) -> void:
	var Group: int = 0  # 51
	Group = ApplyRaw(Entity)  # 53
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\Blue\\Invincible.pfx", 0.3).ActivateNow().ActivateOnCreate().ScaleWith(C.eiCollisionRadius).BindToSubPositionGroup(C.BIND_ZONE_CENTER, [0, 1])  # 56
	TMeshEffectComponent.new().CreateGrouped(Entity, [Group]).TargetGroup([]).SetEffect(TMeshEffectGlow.new().Create(2000).FixedColorIdentity(C.ecBlue).AddKey(0, 0.1).AddKey(2000 - 500, 0.1).AddKey(2000, 0.0))  # 62
	TSoundComponent.new().CreateGrouped(Entity, [Group], "event:/card/blue/effect/invincible").TriggerNow()  # 72
