# Generated by tools/transpile_scripts.py from Scripts\Modifiers\LiftedEnds.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\LiftedEnds.dws:3
func Apply(Entity) -> void:
	var Group: int = 0  # 4
	Group = Entity.ReserveFreeGroup()  # 6
	Entity.Blackboard.SetValue(C.eiCooldown, [Group], 500)  # 7
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upImmobilized])  # 17
	TPositionerOffsetComponent.new().CreateGrouped(Entity, [Group]).OverrideY().TargetGroup([]).Offset(0.0, C.FLYING_HEIGHT, 0.0)  # 20
	TPositionerOffsetComponent.new().CreateGrouped(Entity, [Group]).TargetGroup([]).Offset(0.0, -C.FLYING_HEIGHT, 0.0).Transition(500)  # 24
