# Generated by tools/transpile_scripts.py from Scripts\Modifiers\Lifted.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\Lifted.dws:3
func Apply(Entity) -> void:
	var LIFT_DURATION: int = 15000  # 4
	var Group: int = 0  # 5
	var EffectEndGroup: int = 0  # 5
	var ImmuneGroup: int = 0  # 5
	Group = Entity.ReserveFreeGroup()  # 7
	EffectEndGroup = Entity.ReserveFreeGroup()  # 8
	ImmuneGroup = Entity.ReserveFreeGroup()  # 9
	Entity.Blackboard.SetValue(C.eiCooldown, [Group], LIFT_DURATION)  # 10
	Entity.Blackboard.SetValue(C.eiCooldown, [ImmuneGroup], LIFT_DURATION + 10000)  # 11
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upGround]).Remove()  # 39
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upFlying])  # 41
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upHasStateEffect, C.upLifted])  # 42
	TUnitPropertyComponent.new().CreateGrouped(Entity, [ImmuneGroup], [C.upImmuneToLifted])  # 43
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [Group], "Modifiers\\LiftedEnds.dws")  # 45
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\Shared\\lifted.pfx", 1.0).ActivateNow().ScaleWith(C.eiCollisionRadius).FixedHeightGround().FixedOrientationDefault()  # 48
	TParticleEffectComponent.new().CreateGrouped(Entity, [EffectEndGroup], "\\Blue\\inverse_gravity_lifted.pfx", 0.6).ActivateNow().ActivateOnCreate().DeactivateOnFire().ScaleWith(C.eiCollisionRadius).BindToSubPositionGroup(C.BIND_ZONE_CENTER, [0, 1]).FixedOrientationDefault()  # 54
	TPositionerRotationComponent.new().CreateGrouped(Entity, [Group]).TargetGroup([]).Radius(0.05).RotationSpeed(0.0, 0.0, 0.75 * PI).Factor(0.0, 1.0, 0.0).Phase(L.Random()).FadeIn(500)  # 62
	TPositionerRotationComponent.new().CreateGrouped(Entity, [Group]).TargetGroup([]).Radius(0.025).RotationSpeed(0.45 * PI, 0.55 * PI, 0.65 * PI).Factor(1.0, 0.0, 1.0).Phase(L.Random()).FadeIn(500)  # 70
	TPositionerOffsetComponent.new().CreateGrouped(Entity, [Group]).TargetGroup([]).Offset(0.0, C.FLYING_HEIGHT, 0.0).Transition(500)  # 78
	TSoundComponent.new().CreateGrouped(Entity, [Group], "event:/card/blue/effect/lifted").TriggerNow()  # 83
