# Generated by tools/transpile_scripts.py from Scripts\Modifiers\Petrified.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\Petrified.dws:3
func Apply(Entity) -> void:
	var Group: int = 0  # 4
	var ImmuneGroup: int = 0  # 4
	var HoTGroup: int = 0  # 4
	Group = Entity.ReserveFreeGroup()  # 6
	ImmuneGroup = Entity.ReserveFreeGroup()  # 7
	HoTGroup = Entity.ReserveFreeGroup()  # 8
	Entity.Blackboard.SetValue(C.eiCooldown, [Group], 12000)  # 9
	Entity.Blackboard.SetValue(C.eiCooldown, [ImmuneGroup], 12000 + 10000)  # 10
	Entity.Blackboard.SetValue(C.eiCooldown, [HoTGroup], 1000)  # 11
	Entity.Blackboard.SetValue(C.eiWelaDamage, [HoTGroup], 10.0)  # 12
	Entity.Blackboard.SetValue(C.eiDamageType, [HoTGroup], [C.dtHoT, C.dtOverheal])  # 13
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upHasStateEffect, C.upPetrified])  # 52
	TUnitPropertyComponent.new().CreateGrouped(Entity, [ImmuneGroup], [C.upImmuneToPetrified])  # 53
	TParticleEffectComponent.new().CreateGrouped(Entity, [HoTGroup], "\\Colorless\\petrify_heal.pfx", 1.25).ActivateOnFire().ScaleWith(C.eiCollisionRadius).BindToSubPositionGroup(C.BIND_ZONE_CENTER, [0, 1])  # 56
	TMeshEffectComponent.new().CreateGrouped(Entity, [Group]).TargetGroup([]).SetEffect(TMeshEffectStone.new().Create(12000).AddKey(0, 0.0).AddKey(500, 1.0).AddKey(12000 - 250, 1.0).AddKey(12000, 0.0))  # 61
