# Generated by tools/transpile_scripts.py from Scripts\Modifiers\Spawner.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\Spawner.dws:3
func Apply(Entity) -> void:
	TParticleEffectComponent.new().CreateGrouped(Entity, [0], "\\Shared\\SpawnerImpact.pfx", 2.4).Delay(160).ActivateNow()  # 11
	TAnimatorComponent.new().CreateGrouped(Entity, []).Duration(300).SizeKeypointsXZ([1.0, 1.0, 1.0]).SizeKeypointsY([3.0, 0.3, 1.0]).SizeTimes([0, 160, 300]).PositionKeypointsY([3.0, 0.0, 0.0]).PositionTimes([0, 160, 300])  # 15
	TMeshEffectGlow.new().Create(350).AddKey(0, 1.0).AddKey(300, 0.0).AssignToEntity(Entity)  # 23
	TPositionerOffsetComponent.new().CreateGrouped(Entity, []).Offset(0.0, 0.2, 0.0)  # 28
