# Generated by tools/transpile_scripts.py from Scripts\Modifiers\TimedLife.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Modifiers\TimedLife.dws:3
func Apply(Entity) -> void:
	var Group: int = 0  # 4
	var ReleaseGroup: int = 0  # 4
	Group = Entity.ReserveFreeGroup()  # 6
	ReleaseGroup = Entity.ReserveFreeGroup()  # 7
	Entity.Blackboard.SetValue(C.eiCooldown, [Group], 17000)  # 8
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [Group], false)  # 22
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [Group], "TimedLife").PassInteger("duration", 17)  # 25
	TIndicatorCooldownCircleComponent.new().CreateGrouped(Entity, [Group]).SetTexture(C.PATH_GRAPHICS_EFFECTS_TEXTURES + "ProgressCircle.tga").SetRadius(1.5).ScaleWith(C.eiCollisionRadius).SetThickness(0.1).SetLinearBlend().Color(1627389951).Invert()  # 28
