# Generated by tools/transpile_scripts.py from Scripts\Effects\SporeField.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Effects\SporeField.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiWelaRange, [1], 4.0)  # 5
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [1], 200)  # 6
	Entity.Blackboard.SetValue(C.eiLinkPattern, [1], "Links\\HealthRegenerationAura")  # 7
	Entity.Blackboard.SetValue(C.eiCooldown, [3], 10000)  # 9
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [4], 200)  # 11
	Entity.Blackboard.SetValue(C.eiWelaRange, [4], 4.0)  # 12

# Effects\SporeField.ets:15
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 17

# Effects\SporeField.ets:23
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 25
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [4], "Modifiers\\Grounded.dws").Methodname("ApplyGreen")  # 64
	TParticleEffectComponent.new().CreateGrouped(Entity, [1], "\\Green\\spore_field.pfx", 5.0).ActivateOnCreate().ScaleWith(C.eiWelaRange)  # 68
	TParticleEffectComponent.new().CreateGrouped(Entity, [1], "\\Green\\spore_death.pfx", 5.0).ActivateOnCreate().ScaleWith(C.eiWelaRange)  # 72
	TParticleEffectComponent.new().CreateGrouped(Entity, [1], "\\Green\\green_border.pfx", 5.0).ActivateOnCreate().IgnoreModelSize().ScaleWith(C.eiWelaRange).FixedOrientationDefault().FixedHeightGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 76
	TSoundComponent.new().CreateGrouped(Entity, [4], "event:/card/shared/effect/grounded").TriggerOnFire()  # 84
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/card/green/unit/spore/heal_field_loop").TriggerOnCreate().StopOnFree()  # 87
