# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Colorless\SmallCasterGolemProjectile.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Colorless\SmallCasterGolemProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(14) / 1000)  # 5

# Projectiles\Colorless\SmallCasterGolemProjectile.ets:8
func CreateMeta(Entity) -> void:
	var i: int = 0  # 9
	CreateData(Entity)  # 11

# Projectiles\Colorless\SmallCasterGolemProjectile.ets:38
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 40
	TMovementComponent.new().Create(Entity)  # 43
	TBrainProjectileComponent.new().CreateGrouped(Entity, [0])  # 44
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [0])  # 46
	TWarheadSpottyDamageComponent.new().CreateGrouped(Entity, [0])  # 47
