# Generated by tools/transpile_scripts.py from Scripts\Environment\AtmoBeach.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Environment\AtmoBeach.ets:1
func CreateMeta(Entity) -> void:
	pass

# Environment\AtmoBeach.ets:12
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 14
	TSoundComponent.new().Create(Entity, "event:/env/map/atmo_beach").CheckOption(C.coSoundPlayAtmo).IsLoop().TriggerOnCreate().StopOnFree()  # 17
