# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Green\ForestGuardianProjectile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Green\ForestGuardianProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(16) / 1000)  # 5

# Projectiles\Green\ForestGuardianProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10
	TMeshComponent.new().Create(Entity, ("Units\\Green\\ForestGuardian" + Entity.SkinFileSuffix()) + "\\Projectile\\Stone.xml").ApplyLegacySizeFactor()  # 13
	TParticleEffectComponent.new().Create(Entity, ("\\Green\\forest_guardian" + Entity.SkinFileSuffix()) + "_projectile_trail.pfx", 1.0).ActivateOnCreate()  # 16
	TVertexTraceComponent.new().CreateGrouped(Entity, []).Texture("Effects\\Textures\\StoneTrace.tga").Color(2162229216).Width(0.65).SamplingDistance(0.25).FadeLength(3.0).MaxLength(4.0).TexturePerDistance(4.0)  # 19

# Projectiles\Green\ForestGuardianProjectile.ets:30
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 32
	TOrienterAutoRotationComponent.new().Create(Entity).SetSpeed(Vector3(0.006, 0 * 0.0051, 0 * 0.0084))  # 52
	TPositionerSplineComponent.new().Create(Entity).OrientStartWithTarget().StartTangent(PI / 8, 0.0, 1.0).EndTangent(((float(3) / 4) * PI) / 2, 0.0, 1.0).BindToSubPosition(C.BIND_ZONE_WEAPON_MUZZLE, [0, 1])  # 55
	TParticleEffectComponent.new().CreateGrouped(Entity, [0], ("\\Green\\forest_guardian" + Entity.SkinFileSuffix()) + "_projectile_impact.pfx", 7.0).ActivateOnFireWarhead().ScaleWith(C.eiWelaAreaOfEffect).FixedOrientationDefault()  # 61
	TSoundComponent.new().Create(Entity, "event:/card/green/unit/forest_guardian/attack_impact").TriggerOnFree()  # 66
	TParticleEffectComponent.new().CreateGrouped(Entity, [0], "\\Green\\green_border_wide_once.pfx", 5.0).ActivateOnFireWarhead().FixedOrientationDefault().ScaleWith(C.eiWelaAreaOfEffect).FixedOffsetGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 69
	TCameraShakerComponent.new().CreateGrouped(Entity, []).PresetRotationLight().ActivateOnFree()  # 76
	TCameraShakerComponent.new().CreateGrouped(Entity, []).PresetVectorLight().ActivateOnFree()  # 80
