# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Green\RootdudeRootBraidProjectile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Green\RootdudeRootBraidProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(20) / 1000)  # 5

# Projectiles\Green\RootdudeRootBraidProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10
	TParticleEffectComponent.new().Create(Entity, "\\Green\\rootdude_projectile.pfx", 1.0).ActivateOnCreate()  # 13
	TVertexTraceComponent.new().CreateGrouped(Entity, []).Texture("Effects\\Textures\\RootTrail.tga").Color(4294967295).Width(0.8).SamplingDistance(0.5).FadeLength(0.5).MaxLength(5.0).TexturePerDistance(4.0).FixedOrientationDefault().FixedHeightGround()  # 16

# Projectiles\Green\RootdudeRootBraidProjectile.ets:29
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 31
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [0], "Modifiers\\Root.dws")  # 45
