# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Green\ThistleProjectile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Green\ThistleProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(20) / 1000)  # 5

# Projectiles\Green\ThistleProjectile.ets:8
func CreateMeta(Entity) -> void:
	var Color_: int = 0  # 10
	CreateData(Entity)  # 13
	if Entity.SkinID == C.SKIN_GROUP_UNDERWORLD:  # 16
		Color_ = 2163276031  # 17
	elif Entity.SkinID == C.SKIN_GROUP_SCILL:  # 18
		Color_ = 2164260608  # 19
	else:
		Color_ = 2155085568  # 21
	TVertexQuadComponent.new().Create(Entity, ("Units\\Green\\Thistle" + Entity.SkinFileSuffix()) + "\\Projectile\\thistle_projectile.tga", 1.0, 0.25).Color(Color_).CameraOriented().Additive()  # 22
	if Entity.SkinID == C.SKIN_GROUP_UNDERWORLD:  # 27
		Color_ = 284227839  # 28
	elif Entity.SkinID == C.SKIN_GROUP_SCILL:  # 29
		Color_ = 285212416  # 30
	else:
		Color_ = 276037376  # 32
	TVertexTraceComponent.new().CreateGrouped(Entity, []).Texture("Effects\\Textures\\Trace.tga").Color(Color_).Width(0.15).SamplingDistance(0.5).FadeLength(2.0).MaxLength(14.0).TexturePerDistance(4.0).Additive()  # 33

# Projectiles\Green\ThistleProjectile.ets:45
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 47
	TPositionerSplineComponent.new().Create(Entity).BothTangents(PI / 16, 0.0, 1.0).BindToSubPosition(C.BIND_ZONE_WEAPON_MUZZLE, [0, 1])  # 58
	TOrienterFrontInverterComponent.new().Create(Entity)  # 61
	TSoundComponent.new().Create(Entity, "event:/card/green/unit/thistle/attack_impact").TriggerOnFree()  # 63
