# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Green\WoodwalkerProjectile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Green\WoodwalkerProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(20) / 1000)  # 5

# Projectiles\Green\WoodwalkerProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10
	TPointLightComponent.new().Create(Entity, 4286638379, 2.0)  # 13
	TVertexQuadComponent.new().Create(Entity, "Effects\\Textures\\GreenLensFlare.tga", 2.6, 1.3).ScreenSpace().Additive().Color(2701131775)  # 15
	TVertexTraceComponent.new().CreateGrouped(Entity, []).Texture("Effects\\Textures\\NatureTrace.tga").Color(2701131775).Width(0.36).SamplingDistance(0.5).FadeLength(3.0).MaxLength(3.0).TexturePerDistance(4.0).FadeWidening(-0.09).Additive()  # 20
	TParticleEffectComponent.new().Create(Entity, "\\Green\\woodwalker_projectile.pfx", 4.0).ActivateOnCreate()  # 31
	Entity.Eventbus.Write(C.eiModelSize, [1.0])  # 33

# Projectiles\Green\WoodwalkerProjectile.ets:37
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 39
	TPositionerSplineComponent.new().Create(Entity).BothTangents(PI / 8, 0.0, 1.0).BindToSubPosition(C.BIND_ZONE_WEAPON_MUZZLE, [0, 1])  # 50
	TSoundComponent.new().Create(Entity, "event:/card/green/unit/woodwalker/attack_impact").TriggerOnFree()  # 54
