# Generated by tools/transpile_scripts.py from Scripts\Spells\Golems\Earthquake.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\Golems\Earthquake.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upLegendary])  # 5
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reWelaCharge, 6)  # 7
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reWelaCharge, 6)  # 8
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [1], C.reWelaCharge, 1)  # 10
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 5000)  # 11
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [1], 8.0)  # 12
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 35.0)  # 13
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtSiege, C.dtSpell, C.dtSplash])  # 14
	Entity.Blackboard.SetValue(C.eiWelaRange, [2], 8.0)  # 16
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [2], 200)  # 17

# Spells\Golems\Earthquake.ets:20
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 22
	TWelaTargetConstraintEnemiesComponent.new().CreateGrouped(Entity, [1])  # 24
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [1], C.eiDamageable)  # 25
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [1]).MustNotHave([C.upBanished, C.upSpellImmune])  # 26
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [1]).MustHave([C.upGround])  # 28
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [2]).MustHave([C.upUnit, C.upGround]).MustNotHave([C.upLegendary, C.upNoAutoAttack, C.upImmuneToStateEffects])  # 31
	TWelaTargetConstraintEnemiesComponent.new().CreateGrouped(Entity, [2])  # 34
	TTextureRangeIndicatorComponent.new().CreateGrouped(Entity, [1]).SetTexture("SpelltargetGround.png")  # 37
	TRangeIndicatorHighlightEntitiesComponent.new().CreateGrouped(Entity, [1])  # 39

# Spells\Golems\Earthquake.ets:43
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 45
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [2], "Modifiers\\Stun.dws")  # 91
	TUnitPropertyComponent.new().CreateGrouped(Entity, [], [C.upHasLegendaryUnit]).GivePropertyOwner()  # 93
	TParticleEffectComponent.new().CreateGrouped(Entity, [1], "\\Colorless\\earthquake_fire.pfx", 6.0).ActivateOnFire().FixedOrientationDefault().FixedHeightGround().ScaleWith(C.eiWelaAreaOfEffect)  # 97
	TParticleEffectComponent.new().CreateGrouped(Entity, [1], "\\Colorless\\earthquake_field.pfx", 6.0).ActivateOnCreate().FixedOrientationDefault().ScaleWith(C.eiWelaAreaOfEffect).FixedHeightGround()  # 103
	TParticleEffectComponent.new().CreateGrouped(Entity, [1], "\\Colorless\\colorless_border_wide.pfx", 5.0).ActivateOnCreate().PlaceAtSavedTarget().FixedOrientationDefault().ScaleWith(C.eiWelaAreaOfEffect).FixedHeightGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 109
	TCameraShakerComponent.new().CreateGrouped(Entity, [1]).PresetVectorStrong().ActivateOnFire()  # 117
	TCameraShakerComponent.new().CreateGrouped(Entity, [1]).PresetRotationStrong().ActivateOnFire()  # 121
	TCameraShakerComponent.new().CreateGrouped(Entity, [1]).VectorShaker(-0.4, -1.0, 0.2).Strength(0.03).Duration(5000).Waves(80).NoFade().ActivateOnFire().StopOnFree()  # 125
	TSoundComponent.new().CreateGrouped(Entity, [1], "event:/card/colorless/spell/earthquake/fire").TriggerOnFire()  # 134
