# Generated by tools/transpile_scripts.py from Scripts\Spells\Golems\Petrify.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\Golems\Petrify.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiWelaRange, [], 4.0)  # 5
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [], 16)  # 6

# Spells\Golems\Petrify.ets:9
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 11
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [1]).MustHaveAny([C.upUnit, C.upBuilding]).MustNotHave([C.upLegendary, C.upBase, C.upSpellImmune])  # 14
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [2]).MustNotHave([C.upImmuneToPetrified, C.upImmuneToStateEffects])  # 19
	TWelaTargetConstraintBooleanComponent.new().CreateGrouped(Entity, []).GroupA([1]).GroupB([2]).OperatorAnd()  # 22
	TTextureRangeIndicatorComponent.new().CreateGrouped(Entity, []).SetTexture("SpelltargetGround.png")  # 28
	TRangeIndicatorHighlightEntitiesComponent.new().CreateGrouped(Entity, []).Valid([1]).Invalid([2])  # 30

# Spells\Golems\Petrify.ets:36
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 38
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [], "Modifiers\\Petrified.dws")  # 54
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/card/colorless/spell/petrify/cast").TriggerOnCreate()  # 57
	TCameraShakerComponent.new().CreateGrouped(Entity, []).PresetRotationLight().ActivateOnCreate()  # 60
	TCameraShakerComponent.new().CreateGrouped(Entity, []).PresetVectorLight().ActivateOnCreate()  # 64
	TParticleEffectComponent.new().CreateGrouped(Entity, [], "\\Colorless\\petrify_cast.pfx", 4.5).ActivateOnCreate().FixedOrientationDefault().ScaleWith(C.eiWelaRange).FixedOffsetGround().IsPiece()  # 68
	TParticleEffectComponent.new().CreateGrouped(Entity, [], "\\Colorless\\colorless_border_wide_once.pfx", 5.0).ActivateOnCreate().FixedOrientationDefault().ScaleWith(C.eiWelaRange).FixedHeightGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 75
