# Generated by tools/transpile_scripts.py from Scripts\Units\Scenario\BossSiegeGolemAttack.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\BuildingTemplate.dws:3
func InitBuildingData(Entity, LimitedLifeTime: bool = false) -> void:
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 12.0)  # 5
	if LimitedLifeTime:  # 8
		Entity.Blackboard.SetValue(C.eiCooldown, [C.GROUP_BUILDING_LIFETIME], 90000)  # 9
	Entity.Blackboard.SetValue(C.eiWelaRange, [C.GROUP_SOUL], 12.0)  # 11
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 14
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapBuildingIcon.png")  # 15
	if LimitedLifeTime:  # 17
		TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], "TimedLifeBuilding").PassInteger("duration", 90)  # 18

# HelperScripts\BuildingTemplate.dws:23
func InitBuildingMeta(Entity) -> void:
	pass

# HelperScripts\BuildingTemplate.dws:32
func InitBaseBuildingEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 34
	TPathfindingComponent.new().Create(Entity)  # 51

# HelperScripts\BuildingTemplate.dws:57
func InitBuildingEntity(Entity, LimitedLifeTime: bool = false) -> void:
	InitBaseBuildingEntity(Entity)  # 59
	if LimitedLifeTime:  # 71
		TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], false)  # 72
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 75
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 76
	TShowOnMinimapComponent.new().Create(Entity)  # 78
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/env/building/shared/hit").TriggerOnLoseHealth()  # 79
	if LimitedLifeTime:  # 82
		TIndicatorCooldownCircleComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME]).SetTexture(C.PATH_GRAPHICS_EFFECTS_TEXTURES + "ProgressCircle.tga").SetRadius(1.5).ScaleWith(C.eiCollisionRadius).SetThickness(0.1).SetLinearBlend().Color(1627389951).Invert()  # 84

# Units\Scenario\BossSiegeGolemAttack.ets:3
func CreateData(Entity) -> void:
	InitBuildingData(Entity, false)  # 5
	Entity.CollisionRadius = 2.55  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecColorless)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier3, C.upFlying, C.upBuilding, C.upGround, C.upLegendary, C.upNexus, C.upUnhealable, C.upBase, C.upGolem, C.upSpellImmune])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atFortified)  # 9
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 1200.0)  # 10
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 1200.0)  # 11
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reWelaCharge, 0)  # 13
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reWelaCharge, 8 * 60)  # 14
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 9999999.0)  # 17
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [0, 1], "Projectiles\\Colorless\\BossSiegeGolemAttackProjectile")  # 18
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtIgnoreArmor, C.dtTrue])  # 19
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 0.041667)  # 20
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 5000)  # 21
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 933)  # 22
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 1833)  # 23
	Entity.Blackboard.SetValue(C.eiWelaDamage, [2], 1.0)  # 26
	Entity.Blackboard.SetValue(C.eiWelaDamage, [3], 3.0 * 60.0)  # 29
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, false)  # 32
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapBossIcon.png")  # 33
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIconSize, 3.0)  # 34
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaAttack, 2)  # 36
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaDefense, 8)  # 37
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaUtility, 0)  # 38
	TTooltipUnitAbilityComponent.new().Create(Entity, "PrimaryTargetPvE")  # 39
	TTooltipUnitAbilityComponent.new().Create(Entity, "SpellImmune")  # 40

# Units\Scenario\BossSiegeGolemAttack.ets:44
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 46
	InitBuildingMeta(Entity)  # 47
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(0, 0, 0), Vector3(0, 3.72, 0), 1.86)  # 50
	TMeshComponent.new().CreateGrouped(Entity, [0, 1], "Units\\Scenario\\AttackBoss\\AttackBoss.xml").ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_STAND, 0, 60).CreateNewAnimation(C.ANIMATION_ATTACK, 118, 172).BindZoneToBone(C.BIND_ZONE_CENTER, "MeleeGolemTowerPelvis").BindZoneToBone(C.BIND_ZONE_HIT_ZONE_AIR, "golem_high").BoneOffset(C.BIND_ZONE_HIT_ZONE_AIR, -2.0, 2.25, 0.0)  # 52
	TAnimationComponent.new().CreateGrouped(Entity, [0, 1])  # 60
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [1.7], [0])  # 61

# Units\Scenario\BossSiegeGolemAttack.ets:65
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 67
	InitBuildingEntity(Entity, false)  # 68
	TSoundComponent.new().CreateGrouped(Entity, [1], "event:/card/colorless/unit/boss_siege_golem/attack_fire").TriggerOnPreFire().StopOnFree()  # 108
	TParticleEffectComponent.new().CreateGrouped(Entity, [0], "\\Neutral\\NexusDie5.pfx", 1.0).ActivateOnLose().IgnoreModelSize().FixedOrientationDefault().SetModelOffset(Vector3(0, 3, 0))  # 112
	TMeshEffectComponent.new().CreateGrouped(Entity, [0]).ActivateOnLose().SetEffect(TMeshEffectGlow.new().Create(10000).AddKey(0, 0.0).AddKey(2800, 0.5).AddKey(3100, 1.0).AddKey(3201, 0.0).AddKey(10000, 0.0))  # 118
	TAnimatorComponent.new().CreateGrouped(Entity, [0]).Duration(30000).ActivateOnLose().HideAfter(3150)  # 129
	TCameraShakerComponent.new().Create(Entity).RotationShaker(0.005, 0.005, 0.02).Duration(1000).Waves(24).ActivateOnLose().Delay(3200)  # 134
	TCameraShakerComponent.new().Create(Entity).VectorShaker(0.0, -1.0, 0.0).Strength(0.3).Duration(1000).Waves(16).ActivateOnLose().Delay(3200)  # 141
	TCameraShakerComponent.new().Create(Entity).RotationShaker(0.001, 0.001, 0.005).Duration(3200).Waves(24).Invert().ActivateOnLose()  # 149
	TCameraShakerComponent.new().Create(Entity).VectorShaker(0.0, -1.0, 0.0).Strength(0.1).Duration(3200).Waves(16).Invert().ActivateOnLose()  # 156
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/env/building/nexus/destroy").TriggerOnLose()  # 164
	TOrienterTargetComponent.new().CreateGrouped(Entity, [1])  # 167
