# Generated by tools/transpile_scripts.py from Scripts\Units\Scenario\TutorialTrigger.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\BuildingTemplate.dws:3
func InitBuildingData(Entity, LimitedLifeTime: bool = false) -> void:
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 12.0)  # 5
	if LimitedLifeTime:  # 8
		Entity.Blackboard.SetValue(C.eiCooldown, [C.GROUP_BUILDING_LIFETIME], 90000)  # 9
	Entity.Blackboard.SetValue(C.eiWelaRange, [C.GROUP_SOUL], 12.0)  # 11
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 14
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapBuildingIcon.png")  # 15
	if LimitedLifeTime:  # 17
		TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], "TimedLifeBuilding").PassInteger("duration", 90)  # 18

# HelperScripts\BuildingTemplate.dws:23
func InitBuildingMeta(Entity) -> void:
	pass

# HelperScripts\BuildingTemplate.dws:32
func InitBaseBuildingEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 34
	TPathfindingComponent.new().Create(Entity)  # 51

# HelperScripts\BuildingTemplate.dws:57
func InitBuildingEntity(Entity, LimitedLifeTime: bool = false) -> void:
	InitBaseBuildingEntity(Entity)  # 59
	if LimitedLifeTime:  # 71
		TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], false)  # 72
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 75
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 76
	TShowOnMinimapComponent.new().Create(Entity)  # 78
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/env/building/shared/hit").TriggerOnLoseHealth()  # 79
	if LimitedLifeTime:  # 82
		TIndicatorCooldownCircleComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME]).SetTexture(C.PATH_GRAPHICS_EFFECTS_TEXTURES + "ProgressCircle.tga").SetRadius(1.5).ScaleWith(C.eiCollisionRadius).SetThickness(0.1).SetLinearBlend().Color(1627389951).Invert()  # 84

# Units\Scenario\TutorialTrigger.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [1], 200)  # 5
	Entity.Blackboard.SetValue(C.eiWelaRange, [1], 16.5)  # 6
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 250)  # 7

# Units\Scenario\TutorialTrigger.ets:13
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 15

# Units\Scenario\TutorialTrigger.ets:24
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 26
