# Generated by tools/transpile_scripts.py from Scripts\Units\Blue\Atlas.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TStatisticsUnitComponent.new().Create(Entity)  # 27
	THealthComponent.new().Create(Entity)  # 29
	TArmorComponent.new().Create(Entity)  # 30
	TMovementComponent.new().Create(Entity)  # 31
	TThinkImpulseTimerComponent.new().Create(Entity)  # 32
	TBrainFollowLaneComponent.new().Create(Entity)  # 33
	TBrainActionComponent.new().CreateGroupedAll(Entity)  # 34
	TAutoBrainOnDeathComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).FireAtGround()  # 37
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).MustNotHave([C.upSoulless])  # 39
	TWelaEffectFactoryComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).PassCardValues()  # 41
	TPathfindingComponent.new().Create(Entity)  # 45

# Units\Blue\Atlas.ets:3
func CreateData(Entity) -> void:
	var CurrentLevel: int = 0  # 4
	var AdjustedHealth: float = 0.0  # 5
	InitUnitData(Entity)  # 7
	Entity.CollisionRadius = 1.0  # 8
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecBlue)  # 9
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier1, C.upUnit, C.upMelee, C.upGround, C.upLegendary])  # 10
	CurrentLevel = Entity.BalanceInt(C.reLevel)  # 12
	if CurrentLevel < 2:  # 13
		Entity.Blackboard.SetValue(C.eiArmorType, [], C.atUnarmored)  # 14
	elif CurrentLevel < 4:  # 15
		Entity.Blackboard.SetValue(C.eiArmorType, [], C.atLight)  # 16
	elif CurrentLevel < 6:  # 17
		Entity.Blackboard.SetValue(C.eiArmorType, [], C.atMedium)  # 18
	else:
		Entity.Blackboard.SetValue(C.eiArmorType, [], C.atHeavy)  # 20
	AdjustedHealth = 155.0  # 22 {@UBL_Health}
	AdjustedHealth = AdjustedHealth + (70.0 * max(0, CurrentLevel - 1))  # 23
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, AdjustedHealth)  # 24
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, AdjustedHealth)  # 25
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reLevel, 10)  # 27
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 1.0)  # 30 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtMelee])  # 31
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 79.0)  # 32 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 1700)  # 33 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 766)  # 34
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 1400)  # 35
	Entity.Blackboard.SetValue(C.eiWelaRange, [3], 6.5)  # 38
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [3], "Projectiles\\Blue\\AtlasActiveArmorProjectile")  # 39
	Entity.Blackboard.SetValue(C.eiDamageType, [3], [C.dtRanged, C.dtAbility])  # 40
	Entity.Blackboard.SetValue(C.eiWelaDamage, [3], 10.0)  # 41
	Entity.Blackboard.SetValue(C.eiDamageType, [4], [C.dtTrue, C.dtIgnoreArmor])  # 44
	Entity.Blackboard.SetValue(C.eiWelaDamage, [4], 10.0)  # 45
	Entity.Blackboard.SetValue(C.eiWelaRange, [5], 12.0)  # 48
	Entity.Blackboard.SetValue(C.eiWelaDamage, [5], 0.1)  # 49

# Units\Blue\Atlas.ets:74
func CreateMeta(Entity) -> void:
	var i: int = 0  # 75
	CreateData(Entity)  # 77
	InitUnitMeta(Entity)  # 78

# Units\Blue\Atlas.ets:130
func CreateEntity(Entity) -> void:
	var i: int = 0  # 131
	var color: int = 0  # 132
	CreateMeta(Entity)  # 134
	InitUnitEntity(Entity)  # 135
	TBrainApproachComponent.new().CreateGrouped(Entity, [0])  # 138
	TWelaTargetingRadialAttentionComponent.new().CreateGrouped(Entity, [0]).SetTargetTeamConstraint(C.tcEnemies)  # 139
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [1]).Preemptive()  # 143
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [1], true)  # 145
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [1]).SetTargetTeamConstraint(C.tcEnemies)  # 146
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [0, 1], C.eiDamageable)  # 148
	TWelaTargetConstraintCompareUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).BothMustHaveAny([C.upGround, C.upFlying])  # 149
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).MustNotHave([C.upInvisible, C.upBanished])  # 151
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [1])  # 153
	TWarheadSpottyDamageComponent.new().CreateGrouped(Entity, [1])  # 154
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [1]).Name("Melee").TriggerOnDie().TriggerOnKillDone()  # 155
	TAutoBrainOnTakeDamageComponent.new().CreateGrouped(Entity, [2]).FireSelfInGroup([2])  # 160
	TWelaTriggerCheckNotSelfComponent.new().CreateGrouped(Entity, [2])  # 162
	TThinkImpulseFireComponent.new().CreateGrouped(Entity, [2]).TargetGroup([3])  # 163
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [3]).DisableTargetLock().ThinksPassively().ThinksLocal()  # 165
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [3]).SetTargetTeamConstraint(C.tcEnemies).PicksRandomTargets()  # 169
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [3]).MustNotHave([C.upInvisible, C.upBanished])  # 172
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [3], C.eiDamageable)  # 174
	TWelaEffectProjectileComponent.new().CreateGrouped(Entity, [3])  # 175
	TWelaEffectFireComponent.new().CreateGrouped(Entity, [3]).TargetGroup([4]).RedirectToSelf()  # 176
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [4])  # 179
	TWarheadSpottyDamageComponent.new().CreateGrouped(Entity, [4])  # 180
	TAutoBrainOnCommanderAbilityUsedComponent.new().CreateGrouped(Entity, [5]).ConstraintOnSameTeamID().ConstraintOnInWelaRange().FireAtSelf()  # 182
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [5])  # 186
	TWarheadSpottyHealComponent.new().CreateGrouped(Entity, [5]).PercentageOfMaxHealth()  # 187
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [5]).Name("Induction").TriggerOnFire()  # 189
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [], "Modifiers\\LegendarySpawn.dws").PassIntValue(2200).ApplyToSelfAtCreate()  # 194
	TUnitPropertyComponent.new().CreateGrouped(Entity, [], [C.upHasLegendaryUnit]).GivePropertyOwner()  # 198
