# Generated by tools/transpile_scripts.py from Scripts\Units\Blue\Bombardier.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TStatisticsUnitComponent.new().Create(Entity)  # 27
	THealthComponent.new().Create(Entity)  # 29
	TArmorComponent.new().Create(Entity)  # 30
	TMovementComponent.new().Create(Entity)  # 31
	TThinkImpulseTimerComponent.new().Create(Entity)  # 32
	TBrainFollowLaneComponent.new().Create(Entity)  # 33
	TBrainActionComponent.new().CreateGroupedAll(Entity)  # 34
	TAutoBrainOnDeathComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).FireAtGround()  # 37
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).MustNotHave([C.upSoulless])  # 39
	TWelaEffectFactoryComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).PassCardValues()  # 41
	TPathfindingComponent.new().Create(Entity)  # 45

# Units\Blue\Bombardier.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.8  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecBlue)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier3, C.upUnit, C.upGround, C.upRanged, C.upImmuneToBlinded])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atLight)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 155.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 155.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reMana, 4)  # 13
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reMana, 4)  # 14
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 9.0)  # 17 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 3600)  # 18 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtRanged, C.dtSplash])  # 19
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 82.0)  # 20 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [1], 18.0)  # 21
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 333)  # 22
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 700)  # 23
	Entity.Blackboard.SetValue(C.eiWelaRange, [2], 9.0)  # 26 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiCooldown, [2], 3600)  # 27 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiDamageType, [2], [C.dtRanged, C.dtSplash])  # 28
	Entity.Blackboard.SetValue(C.eiWelaDamage, [2], 82.0)  # 29 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [2], 23.0)  # 30
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [2], 333)  # 31
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [2], 700)  # 32
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [4], C.reMana, 4)  # 34
	Entity.Blackboard.SetValue(C.eiWelaRange, [4], 20.0)  # 35
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [4], "Projectiles\\Blue\\BombardierProjectile")  # 36
	Entity.Blackboard.SetValue(C.eiDamageType, [4], [C.dtRanged, C.dtAbility])  # 37
	Entity.Blackboard.SetValue(C.eiWelaDamage, [4], 275.0)  # 38
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [4], 1033)  # 39
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [4], 3000)  # 40

# Units\Blue\Bombardier.ets:58
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 60
	InitUnitMeta(Entity)  # 61

# Units\Blue\Bombardier.ets:100
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 102
	InitUnitEntity(Entity)  # 103
	TBrainApproachComponent.new().CreateGrouped(Entity, [0])  # 106
	TWelaTargetingRadialAttentionComponent.new().CreateGrouped(Entity, [0]).SetTargetTeamConstraint(C.tcEnemies)  # 107
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [4]).DisableTargetLock().Blocking()  # 111
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [4]).MustNotHave([C.upSilenced])  # 114
	TWelaReadyCostComponent.new().CreateGrouped(Entity, [4]).SetPayingGroupForType(C.reMana, [])  # 116
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [4]).SetTargetTeamConstraint(C.tcEnemies)  # 118
	TWelaTargetConstraintResourceComponent.new().CreateGrouped(Entity, [4]).CheckResource(C.reHealth).Comparator(C.coGreaterEqual).Reference(300.0).CompareCapToReference()  # 120
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [4]).MustNotHave([C.upInvisible, C.upBanished])  # 125
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [4], C.eiDamageable)  # 127
	TWelaEffectPayCostComponent.new().CreateGrouped(Entity, [4]).SetPayingGroupForType(C.reMana, [])  # 128
	TWelaEffectProjectileComponent.new().CreateGrouped(Entity, [4])  # 130
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [2]).Blocking()  # 133
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [2]).MustHave([C.upRangeAuraBuffed])  # 135
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [2])  # 137
	TWarheadSplashDamageComponent.new().CreateGrouped(Entity, [2]).LineFromOwner(1.0).SetValidateGroup([3])  # 138
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [1]).Preemptive()  # 142
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [1, 2], true)  # 144
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [1, 2]).SetTargetTeamConstraint(C.tcEnemies)  # 145
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1, 2]).MustNotHave([C.upInvisible, C.upBanished])  # 147
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [0, 1, 2, 3], C.eiDamageable)  # 149
	TWelaTargetConstraintEnemiesComponent.new().CreateGrouped(Entity, [0, 1, 2, 3])  # 150
	TWelaTargetConstraintCompareUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1, 2, 3]).BothMustHaveAny([C.upGround, C.upFlying])  # 151
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [1])  # 153
	TWarheadSplashDamageComponent.new().CreateGrouped(Entity, [1]).LineFromOwner(1.0).SetValidateGroup([3])  # 154
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [3]).MustNotHave([C.upBanished])  # 157
