# Generated by tools/transpile_scripts.py from Scripts\Units\Blue\DamperDrone.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TStatisticsUnitComponent.new().Create(Entity)  # 27
	THealthComponent.new().Create(Entity)  # 29
	TArmorComponent.new().Create(Entity)  # 30
	TMovementComponent.new().Create(Entity)  # 31
	TThinkImpulseTimerComponent.new().Create(Entity)  # 32
	TBrainFollowLaneComponent.new().Create(Entity)  # 33
	TBrainActionComponent.new().CreateGroupedAll(Entity)  # 34
	TAutoBrainOnDeathComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).FireAtGround()  # 37
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).MustNotHave([C.upSoulless])  # 39
	TWelaEffectFactoryComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).PassCardValues()  # 41
	TPathfindingComponent.new().Create(Entity)  # 45

# Units\Blue\DamperDrone.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.45  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecBlue)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier1, C.upUnit, C.upMelee, C.upGround])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atLight)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 41.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 41.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reMana, 2)  # 13
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reMana, 0)  # 14
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 1.0)  # 17 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtMelee, C.dtSiege])  # 18
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 11.0)  # 19 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 1500)  # 20 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 400)  # 21
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 900)  # 22
	Entity.Blackboard.SetValue(C.eiWelaModifier, [2], 0.3)  # 25
	Entity.Blackboard.SetValue(C.eiWelaRange, [3], 1.0)  # 28 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiDamageType, [3], [C.dtSiege, C.dtSplash, C.dtAbility])  # 29
	Entity.Blackboard.SetValue(C.eiWelaDamage, [3], 20.0)  # 30
	Entity.Blackboard.SetValue(C.eiWelaModifier, [3], 15.0)  # 31
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [3], 1.5)  # 32

# Units\Blue\DamperDrone.ets:48
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 53
	InitUnitMeta(Entity)  # 54

# Units\Blue\DamperDrone.ets:85
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 87
	InitUnitEntity(Entity)  # 88
	TBrainApproachComponent.new().CreateGrouped(Entity, [0])  # 91
	TWelaTargetingRadialAttentionComponent.new().CreateGrouped(Entity, [0]).SetTargetTeamConstraint(C.tcEnemies)  # 92
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [3]).Blocking()  # 96
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [3]).MustNotHave([C.upSilenced])  # 98
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [3]).SetTargetTeamConstraint(C.tcEnemies)  # 100
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [3, 4], C.eiDamageable)  # 102
	TWelaTargetConstraintCompareUnitPropertyComponent.new().CreateGrouped(Entity, [3, 4]).BothMustHaveAny([C.upGround, C.upFlying])  # 103
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [3]).MustHave([C.upBuilding]).MustNotHave([C.upInvisible, C.upBanished])  # 105
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [3])  # 108
	TWarheadSplashDamageComponent.new().CreateGrouped(Entity, [3]).SetValidateGroup([4])  # 109
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [4]).MustNotHave([C.upBanished])  # 111
	TWelaTargetConstraintEnemiesComponent.new().CreateGrouped(Entity, [4])  # 113
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [3]).Name("BreachingCharge").Name("Siege").Name("Splash").TriggerOnDamageDone().TriggerOnFire()  # 114
	TWelaEffectSuicideComponent.new().CreateGrouped(Entity, [3])  # 120
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [1]).Preemptive()  # 123
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [1], true)  # 125
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [1]).SetTargetTeamConstraint(C.tcEnemies)  # 126
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [0, 1], C.eiDamageable)  # 128
	TWelaTargetConstraintCompareUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).BothMustHaveAny([C.upGround, C.upFlying])  # 129
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).MustNotHave([C.upInvisible, C.upBanished])  # 131
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [1])  # 133
	TWarheadSpottyDamageComponent.new().CreateGrouped(Entity, [1])  # 134
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [1]).Name("Melee").TriggerOnDie().TriggerOnKillDone()  # 135
	TBuffTakenDamageMultiplierComponent.new().CreateGrouped(Entity, [2]).DamageTypeMustHave([C.dtSplash])  # 141
	TModifierWelaDamageComponent.new().CreateGrouped(Entity, [3]).ScaleWithResource(C.reMana).ResourceGroup([])  # 146
