# Generated by tools/transpile_scripts.py from Scripts\Units\Green\Groundbreaker.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 12
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapUnitIcon.png")  # 13

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TPathfindingComponent.new().Create(Entity)  # 45
	TOrienterMovementComponent.new().Create(Entity)  # 48
	TOrienterTargetComponent.new().CreateGrouped(Entity, [0, 1])  # 49
	TOrienterSmoothRotateComponent.new().Create(Entity).SetAngleSpeed(0.008)  # 50
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 53
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 54
	TShowOnMinimapComponent.new().Create(Entity)  # 56

# Units\Green\Groundbreaker.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.75  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecGreen)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier3, C.upUnit, C.upGround, C.upMelee])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atUnarmored)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 345.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 345.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetValue(C.eiWelaRange, [1], 1.0)  # 14 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtMelee])  # 15
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 150.0)  # 16 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 1700)  # 17 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 500)  # 18
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 1500)  # 19
	Entity.Blackboard.SetValue(C.eiWelaModifier, [2], 1.5)  # 22
	Entity.Blackboard.SetValue(C.eiWelaModifier, [3], 2.0)  # 23
	Entity.Blackboard.SetValue(C.eiWelaRange, [4, 5], 1.0)  # 26
	Entity.Blackboard.SetValue(C.eiDamageType, [5], [C.dtSplash, C.dtAbility])  # 28
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [5], 3.0)  # 29
	Entity.Blackboard.SetValue(C.eiWelaDamage, [5], 120.0)  # 30
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [5], 133)  # 31
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [5], 1233)  # 32
	Entity.Blackboard.SetValue(C.eiWelaModifier, [6], 0.40)  # 35
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [], "Haste").Keyword("SummoningSickness")  # 38
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [2, 3], "RelentlessRooted").Keyword("Rooted").Keyword("StateEffect").PassPercentage("primary_damage_amount_percentage", 200, "damage").PassPercentage("secondary_damage_amount_percentage", 150, "damage")  # 40
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [5], "DebutRupture").PassInteger("damage_amount", 120, "damage")  # 45
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [6], "Evasion").PassPercentage("evasion_percentage", 40)  # 47
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaAttack, 7)  # 50
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaDefense, 3)  # 51
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaUtility, 0)  # 52

# Units\Green\Groundbreaker.ets:56
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 58
	InitUnitMeta(Entity)  # 59
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(0, 0, 0), Vector3(0, 1.8, 0), 0.8)  # 62
	TMeshComponent.new().CreateGrouped(Entity, [0], "Units\\Green\\Groundbreaker\\Groundbreaker.xml").ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_STAND, 103, 162).CreateNewAnimation(C.ANIMATION_WALK, 37, 57).CreateNewAnimation(C.ANIMATION_ATTACK, 58, 102).CreateNewAnimation("break_out", 0, 36).CreateNewAnimation("dig_in", 164, 194).IgnoreScalingForAnimations().BindZoneToBone(C.BIND_ZONE_CENTER, "GroundbreakerChest").BindZoneToBone(C.BIND_ZONE_WEAPON, "GroundbreakerMFinger1").BindZoneToBone(C.BIND_ZONE_HEAD, "GroundbreakerHead").BindZoneToBone(C.BIND_ZONE_WEAPON_MUZZLE, "GroundbreakerMFinger1").VisibleWithUnitPropertyMustNotHave([C.upBurrowed])  # 64
	TMeshComponent.new().CreateGrouped(Entity, [5], "Units\\Green\\Groundbreaker\\GroundbreakerEffect.xml").ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_STAND, 0, 48).CreateNewAnimation(C.ANIMATION_WALK, 0, 48).IgnoreScalingForAnimations()  # 78
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [1.9], [0, 5])  # 84
	TAnimationComponent.new().CreateGrouped(Entity, [0, 1])  # 85
	TUnitPropertyComponent.new().CreateGrouped(Entity, [5], [C.upInvincible, C.upBurrowed])  # 88

# Units\Green\Groundbreaker.ets:91
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 93
	InitUnitEntity(Entity)  # 94
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/card/green/unit/groundbreaker/spawn").TriggerOnCreate()  # 177
	TParticleEffectComponent.new().CreateGrouped(Entity, [], "\\Green\\groundbreaker_spawn.pfx", 0.9).ActivateOnCreate().FixedOrientationDefault()  # 180
	TSoundComponent.new().CreateGrouped(Entity, [1], "event:/card/green/unit/groundbreaker/attack_fire").TriggerOnPreFire().StopOnFree()  # 184
	TSoundComponent.new().CreateGrouped(Entity, [5], "event:/card/green/unit/groundbreaker/break_in_fire").TriggerOnPreFire()  # 188
	TParticleEffectComponent.new().CreateGrouped(Entity, [5], "\\Green\\groundbreaker_break.pfx", 2.0).ActivateOnFire().ScaleWith(C.eiWelaAreaOfEffect).FixedOrientationDefault()  # 191
	TParticleEffectComponent.new().CreateGrouped(Entity, [5], "\\Green\\green_border_wide_once.pfx", 5.0).ActivateOnFire().FixedOrientationDefault().ScaleWith(C.eiWelaAreaOfEffect).FixedHeightGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 196
	TAnimatorComponent.new().CreateGrouped(Entity, [5]).Duration(200).PositionKeypointsY([-5.0, 0.2, 0.0]).PositionTimes([0, 160, 200]).SizeKeypoints([0.0, 1.2, 1.0]).SizeTimes([0, 160, 200])  # 203
	TAnimatorComponent.new().CreateGrouped(Entity, [0, 5]).Duration(1000).ActivateOnFire().PlayAnimation(0, "break_out", 0)  # 210
	TCameraShakerComponent.new().CreateGrouped(Entity, [5]).PresetRotationMedium().ActivateOnFire()  # 215
	TCameraShakerComponent.new().CreateGrouped(Entity, [5]).PresetVectorMedium().ActivateOnFire()  # 219
	TParticleEffectComponent.new().CreateGrouped(Entity, [6], "\\Green\\dodge.pfx", 1.5).ActivateOnFire()  # 223
