# Generated by tools/transpile_scripts.py from Scripts\Units\Green\HeartOfTheForest.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 12
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapUnitIcon.png")  # 13

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TPathfindingComponent.new().Create(Entity)  # 45
	TOrienterMovementComponent.new().Create(Entity)  # 48
	TOrienterTargetComponent.new().CreateGrouped(Entity, [0, 1])  # 49
	TOrienterSmoothRotateComponent.new().Create(Entity).SetAngleSpeed(0.008)  # 50
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 53
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 54
	TShowOnMinimapComponent.new().Create(Entity)  # 56

# Units\Green\HeartOfTheForest.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.45  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecGreen)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier1, C.upUnit, C.upGround, C.upNoAutoAttack, C.upSupporter])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atUnarmored)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 60.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 60.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reMana, 3)  # 12
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reMana, 3)  # 13
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0], 10.0)  # 16
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [2, 4], C.reMana, 3)  # 19
	Entity.Blackboard.SetValue(C.eiWelaRange, [2, 4], 6.0)  # 20 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [2], "Projectiles\\Green\\HeartOfTheForestProjectile")  # 21
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [2], 1)  # 22
	Entity.Blackboard.SetValue(C.eiDamageType, [2], [C.dtIrredirectable])  # 23
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [2], 400)  # 24
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [2], 800)  # 25
	Entity.Blackboard.SetValue(C.eiWelaDamage, [5], 1.0)  # 28
	Entity.Blackboard.SetValue(C.eiCooldown, [5], 3000)  # 29
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "Pacifist")  # 32
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [5], "EnergyRegeneration").PassInteger("energy_amount", 1, "energy").PassInteger("cooldown", 3)  # 33
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [2], "EnchantmentStrength").Keyword("Enchanted").PassInteger("energy_cost", 3, "energy").PassInteger("health_bonus", 40, "health").PassInteger("damage_bonus", 8, "damage").PassInteger("damage_bonus_surefire", 5, "damage")  # 36
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaAttack, 0)  # 43
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaDefense, 4)  # 44
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaUtility, 6)  # 45

# Units\Green\HeartOfTheForest.ets:49
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 51
	InitUnitMeta(Entity)  # 52
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(0, 0, 0), Vector3(0, 1.4, 0), 0.65)  # 55
	TMeshComponent.new().CreateGrouped(Entity, [0, 1, 2, 3], "Units\\Green\\HeartOfTheForest\\HeartOfTheForest.xml").ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_WALK, 0, 16).CreateNewAnimation(C.ANIMATION_ATTACK, 18, 41).CreateNewAnimation(C.ANIMATION_STAND, 43, 102).IgnoreScalingForAnimations().BindZoneToBone(C.BIND_ZONE_CENTER, "HOTFHead1").BindZoneToBone(C.BIND_ZONE_WEAPON, "HOTFHead3").BindZoneToBone(C.BIND_ZONE_WEAPON_MUZZLE, "HOTFHead3").BoneSwapXZ(C.BIND_ZONE_WEAPON_MUZZLE).BoneSwapYZ(C.BIND_ZONE_WEAPON_MUZZLE).BindZoneToBone(C.BIND_ZONE_HEAD, "HOTFHead3")  # 57
	TAnimationComponent.new().CreateGrouped(Entity, [0, 1, 2])  # 69
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [1.0], [0])  # 70

# Units\Green\HeartOfTheForest.ets:74
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 76
	InitUnitEntity(Entity)  # 77
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [2], "Modifiers\\BlessingStrengthIncoming.dws")  # 130
	TResourceDisplayIntegerProgressBarComponent.new().Create(Entity).FixedCap(3).ShowResource(C.reMana).HideIfEmpty()  # 133
	TParticleEffectComponent.new().CreateGrouped(Entity, [2], "\\Green\\heart_of_the_forest_attack.pfx", 1.2).ActivateOnFire().BindToSubPositionGroup(C.BIND_ZONE_WEAPON_MUZZLE, [0, 1])  # 138
	TSoundComponent.new().CreateGrouped(Entity, [2], "event:/card/green/unit/heart_of_the_forest/attack_fire").TriggerOnPreFire().StopOnFree()  # 142
