# Generated by tools/transpile_scripts.py from Scripts\Units\Green\Rootling.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 12
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapUnitIcon.png")  # 13

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TPathfindingComponent.new().Create(Entity)  # 45
	TOrienterMovementComponent.new().Create(Entity)  # 48
	TOrienterTargetComponent.new().CreateGrouped(Entity, [0, 1])  # 49
	TOrienterSmoothRotateComponent.new().Create(Entity).SetAngleSpeed(0.008)  # 50
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 53
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 54
	TShowOnMinimapComponent.new().Create(Entity)  # 56

# Units\Green\Rootling.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.45  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecGreen)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier1, C.upUnit, C.upGround, C.upRangedGroundOnly, C.upRanged, C.upImmuneToBlinded, C.upLinkWeapon])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atLight)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 200.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 200.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 5.0)  # 14 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiLinkPattern, [1], "Links/RootlingLink")  # 15
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 1000)  # 16 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtRanged])  # 17
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 12.0)  # 18 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 500)  # 19
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 500)  # 20
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "GroundOnly")  # 23
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "Surefire").Keyword("Blinded")  # 24
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "Root").Keyword("Rooted")  # 26
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "RootNetwork").Keyword("Rooted").PassInteger("damage_amount", 10, "damage")  # 28
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaAttack, 2)  # 32
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaDefense, 3)  # 33
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaUtility, 5)  # 34

# Units\Green\Rootling.ets:38
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 40
	InitUnitMeta(Entity)  # 41
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(0, 0, 0), Vector3(0, 1.0, 0), 0.8)  # 44
	TMeshComponent.new().CreateGrouped(Entity, [0, 1], ("Units\\Green\\Rootling" + Entity.SkinFileSuffix()) + "\\Rootling.xml").ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_WALK, 0, 17).CreateNewAnimation(C.ANIMATION_ATTACK, 18, 32).CreateNewAnimation(C.ANIMATION_ATTACK_LOOP, 32, 54).CreateNewAnimation(C.ANIMATION_STAND, 64, 124).BindZoneToBone(C.BIND_ZONE_CENTER, "RootlingHeadBone001").BoneSwapXY(C.BIND_ZONE_CENTER).BindZoneToBone(C.BIND_ZONE_WEAPON, "RootlingHeadBone003").BindZoneToBone(C.BIND_ZONE_HEAD, "RootlingHeadBone003").HasAttackLoop().SetAnimationSpeed(C.ANIMATION_WALK, 1.69)  # 46
	TAnimationComponent.new().CreateGrouped(Entity, [0, 1]).IsLink()  # 60
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [0.8], [0])  # 62

# Units\Green\Rootling.ets:66
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 68
	InitUnitEntity(Entity)  # 69
