# Generated by tools/transpile_scripts.py from Scripts\Units\Green\Spore.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 12
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapUnitIcon.png")  # 13

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TPathfindingComponent.new().Create(Entity)  # 45
	TOrienterMovementComponent.new().Create(Entity)  # 48
	TOrienterTargetComponent.new().CreateGrouped(Entity, [0, 1])  # 49
	TOrienterSmoothRotateComponent.new().Create(Entity).SetAngleSpeed(0.008)  # 50
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 53
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 54
	TShowOnMinimapComponent.new().Create(Entity)  # 56

# Units\Green\Spore.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.6  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecGreen)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier2, C.upUnit, C.upFlying, C.upRanged, C.upHasDeathRattle])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atUnarmored)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 140.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 140.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 3.0)  # 14 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [0, 1], "Projectiles\\Green\\SporeProjectile")  # 15
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 1500)  # 16 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtRanged])  # 17
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 80.0)  # 18 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 333)  # 19
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 666)  # 20
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [2], "Effects\\SporeField")  # 23
	TTooltipUnitAbilityComponent.new().Create(Entity, "Flying")  # 26
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [2], "DeathRattleSporeField").Keyword("Grounded").PassInteger("heal_amount", 30, "health").PassInteger("duration", 10)  # 27
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaAttack, 3)  # 32
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaDefense, 2)  # 33
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaUtility, 5)  # 34

# Units\Green\Spore.ets:38
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 40
	InitUnitMeta(Entity)  # 41
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(0, -0.8, -0.2), Vector3(0, 0.2, 0.0), 0.6)  # 44
	TPositionerOffsetComponent.new().Create(Entity).Offset(0.0, C.FLYING_HEIGHT + 1.28, 0.0)  # 46
	TMeshComponent.new().CreateGrouped(Entity, [0, 1], "Units\\Green\\Spore\\Spore.xml").ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_WALK, 0, 61).CreateNewAnimation(C.ANIMATION_ATTACK, 62, 81).CreateNewAnimation(C.ANIMATION_ATTACK2, 82, 103).CreateNewAnimation(C.ANIMATION_STAND, 0, 61).BindZoneToBone(C.BIND_ZONE_CENTER, "SporeTry_Tail_1").BindZoneToBone(C.BIND_ZONE_WEAPON, "BallBone").BindZoneToBone(C.BIND_ZONE_WEAPON_MUZZLE, "BallBone").BindZoneToBone(C.BIND_ZONE_HEAD, "SporeTry_BodyBone001").IgnoreScalingForAnimations().SetModelOffset(Vector3(0, -0.1, 0))  # 49
	TAnimationComponent.new().CreateGrouped(Entity, [0, 1])  # 62
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [0.16], [0])  # 63

# Units\Green\Spore.ets:67
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 69
	InitUnitEntity(Entity)  # 70
	TAnimatorComponent.new().CreateGrouped(Entity, []).Duration(1750).PositionKeypointsY([(-C.FLYING_HEIGHT) - 1.05, (-C.FLYING_HEIGHT) - 1.05, 0.0]).PositionTimes([0, 1000, 1750])  # 96
	TSoundComponent.new().CreateGrouped(Entity, [1], "event:/card/green/unit/spore/attack_fire").TriggerOnFire().StopOnFree()  # 101
	TSoundComponent.new().CreateGrouped(Entity, [2], "event:/card/green/unit/spore/heal_field").TriggerOnFire()  # 105
	TCameraShakerComponent.new().CreateGrouped(Entity, [2]).PresetRotationLight().ActivateOnFire()  # 108
	TCameraShakerComponent.new().CreateGrouped(Entity, [2]).PresetVectorLight().ActivateOnFire()  # 112
