# Generated by tools/transpile_scripts.py from Scripts\Units\Green\Woodwalker.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 12
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapUnitIcon.png")  # 13

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TPathfindingComponent.new().Create(Entity)  # 45
	TOrienterMovementComponent.new().Create(Entity)  # 48
	TOrienterTargetComponent.new().CreateGrouped(Entity, [0, 1])  # 49
	TOrienterSmoothRotateComponent.new().Create(Entity).SetAngleSpeed(0.008)  # 50
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 53
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 54
	TShowOnMinimapComponent.new().Create(Entity)  # 56

# Units\Green\Woodwalker.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.45  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecGreen)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier2, C.upUnit, C.upGround, C.upRanged])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atUnarmored)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 85.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 85.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reMana, 4)  # 12
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reMana, 16)  # 13
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 8.0)  # 16 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [1], "Projectiles\\Green\\WoodwalkerProjectile")  # 17
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 2800)  # 18 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtRanged])  # 19
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 99.0)  # 20 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 350)  # 21
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 1166)  # 22
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [2], C.reMana, 4)  # 25
	Entity.Blackboard.SetValue(C.eiWelaRange, [2], 12.0)  # 26
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [2], "Units\\Green\\Sapling")  # 27
	Entity.Blackboard.SetValue(C.eiWelaCount, [2], 2)  # 28
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [2], 800)  # 29
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [2], 1700)  # 30
	Entity.Blackboard.SetValue(C.eiWelaDamage, [3], 1.0)  # 33
	Entity.Blackboard.SetValue(C.eiCooldown, [3], 3000)  # 34
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [3], "EnergyRegeneration").PassInteger("energy_amount", 1, "energy").PassInteger("cooldown", 3)  # 37
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [2], "SummonSaplings").Keyword("Sapling").Keyword("Timed").PassInteger("energy_cost", 4, "energy").PassInteger("sapling_amount", 2)  # 40
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaAttack, 4)  # 46
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaDefense, 3)  # 47
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaUtility, 3)  # 48

# Units\Green\Woodwalker.ets:52
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 54
	InitUnitMeta(Entity)  # 55
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(0.2, 0, 0.1), Vector3(0.2, 2.0, 0.1), 0.8)  # 58
	TMeshComponent.new().CreateGrouped(Entity, [0, 1], ("Units\\Green\\Woodwalker" + Entity.SkinFileSuffix()) + "\\Woodwalker.xml").ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_WALK, 189, 224).CreateNewAnimation(C.ANIMATION_ATTACK, 153, 187).CreateNewAnimation(C.ANIMATION_STAND, 92, 152).CreateNewAnimation(C.ANIMATION_ABILITY_1, 37, 91).IgnoreScalingForAnimations().BindZoneToBone(C.BIND_ZONE_CENTER, "WoodwalkerSpine4").BindZoneToBone(C.BIND_ZONE_WEAPON, "WoodwalkerLPalm").BindZoneToBone(C.BIND_ZONE_WEAPON_MUZZLE, "WoodwalkerWeaponEye").BindZoneToBone(C.BIND_ZONE_HEAD, "WoodwalkerHead")  # 60
	TAnimationComponent.new().CreateGrouped(Entity, [0, 1, 2]).AbilityGroup([2])  # 71
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [1.0], [0])  # 73

# Units\Green\Woodwalker.ets:77
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 79
	InitUnitEntity(Entity)  # 80
	TResourceDisplayIntegerProgressBarComponent.new().Create(Entity).FixedCap(4).ShowResource(C.reMana).HideIfEmpty()  # 129
	TSoundComponent.new().CreateGrouped(Entity, [1], "event:/card/green/unit/woodwalker/attack_fire").TriggerOnPreFire().StopOnFree()  # 134
	TParticleEffectComponent.new().CreateGrouped(Entity, [2], "\\Green\\woodwalker_summon_sapling.pfx", 3.0).ActivateOnPreFire().DeactivateOnFire().BindToSubPositionGroup(C.BIND_ZONE_WEAPON_MUZZLE, [0, 1])  # 138
	TSoundComponent.new().CreateGrouped(Entity, [2], "event:/card/green/unit/woodwalker/summon_sapling/attack_fire").TriggerOnPreFire().StopOnFree()  # 143
