# Generated by tools/transpile_scripts.py from Scripts\Spells\Golems\Cataclysm.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\Golems\Cataclysm.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiCooldown, [0, 1], 500)  # 5
	Entity.Blackboard.SetValue(C.eiWelaRange, [0], 6.0)  # 6
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [0], 200)  # 7
	Entity.Blackboard.SetValue(C.eiWelaModifier, [0], 0.5)  # 8

# Spells\Golems\Cataclysm.ets:11
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 13
	TModifierWelaRangeComponent.new().CreateGrouped(Entity, [0]).ScaleWithStage().AddModifier()  # 15
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [0]).MustHaveAny([C.upUnit, C.upBuilding]).MustNotHave([C.upBase, C.upSpellImmune])  # 20

# Spells\Golems\Cataclysm.ets:31
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 33
	TThinkImpulseTimerCooldownComponent.new().CreateGrouped(Entity, [0, 1])  # 36
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [0])  # 38
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [0]).SetTargetTeamConstraint(C.tcAll)  # 39
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [0])  # 41
	TWarheadSpottyKillComponent.new().CreateGrouped(Entity, [0]).Exile()  # 42
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [0]).Name("Cataclysm").TriggerOnKillDone()  # 44
	TBrainWelaTargetlessComponent.new().CreateGrouped(Entity, [1])  # 48
	TWelaEffectSuicideComponent.new().CreateGrouped(Entity, [1])  # 49
