# Generated by tools/transpile_scripts.py from Scripts\Projectiles\White\ArcherProjectile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")

var InheritsFrom: String = "Projectiles/White/ArcherBaseProjectile.ets"  # Projectiles\White\ArcherProjectile.ets:2

# Projectiles\White\ArcherProjectile.ets:4
func CreateData(Entity) -> void:
	pass

# Projectiles\White\ArcherProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10

# Projectiles\White\ArcherProjectile.ets:16
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 18
	TPositionerSplineComponent.new().Create(Entity).BothTangents(PI / 8, 0.0, 1.0).BindToSubPosition(C.BIND_ZONE_WEAPON_MUZZLE, [0, 1])  # 24
