# Generated by tools/transpile_scripts.py from Scripts\Projectiles\White\BallistaProjectile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\White\BallistaProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(26) / 1000)  # 5
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reWelaCharge, 2)  # 8
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reWelaCharge, 2)  # 9
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [1], C.reWelaCharge, 1)  # 11
	Entity.Blackboard.SetValue(C.eiWelaRange, [1], 6.0)  # 12
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [1], "Projectiles\\White\\BallistaHealProjectile")  # 13
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtFlatHeal])  # 14
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 250)  # 15
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 5.5)  # 16
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [1], 2)  # 17

# Projectiles\White\BallistaProjectile.ets:20
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 22
	TMeshComponent.new().Create(Entity, "Units\\White\\Ballista\\BallistaArrow\\BallistaArrow.xml").ApplyLegacySizeFactor()  # 25
	Entity.Eventbus.Write(C.eiModelSize, [0.9])  # 27
	TVertexTraceComponent.new().CreateGrouped(Entity, []).Texture("Effects\\Textures\\LightTrace.tga").Color(2164260863).Width(0.3).SamplingDistance(0.5).FadeLength(3.0).MaxLength(7.0).TexturePerDistance(4.0).Additive()  # 29

# Projectiles\White\BallistaProjectile.ets:41
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 43
	TPositionerSplineComponent.new().Create(Entity).StartTangent(0.0, 0.0, 1.0).EndTangent(PI / 7, 0.0, 1.0).BindToSubPosition(C.BIND_ZONE_WEAPON_MUZZLE, [0, 1])  # 81
	TSoundComponent.new().Create(Entity, "event:/card/white/unit/ballista/attack_impact").TriggerOnFree()  # 86
