# Generated by tools/transpile_scripts.py from Scripts\Projectiles\White\PatronSaintProjectile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\White\PatronSaintProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(20) / 1000)  # 5
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [1], 3.0)  # 7
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 60.0)  # 8
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtFlatHeal, C.dtSplash])  # 9

# Projectiles\White\PatronSaintProjectile.ets:12
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 14
	TOrienterMovementComponent.new().Create(Entity)  # 17
	if Entity.SkinID == C.SKIN_GROUP_MACHINE:  # 18
		TVertexQuadComponent.new().Create(Entity, "Effects\\Textures\\BlueLensFlare.tga", 6.0, 6.0).ScreenSpace().Additive()  # 20
		TPointLightComponent.new().Create(Entity, 2940240127, 2.0)  # 23
		TPointLightComponent.new().Create(Entity, 440434943, 10.0).SetLightShape(Vector3(5, 10, 0))  # 24
	else:
		TVertexQuadComponent.new().Create(Entity, "Effects\\Textures\\LensFlare.tga", 8.0, 4.0).ScreenSpace().Additive()  # 29
		TPointLightComponent.new().Create(Entity, 2952790015, 2.0)  # 32
		TPointLightComponent.new().Create(Entity, 452919192, 10.0).SetLightShape(Vector3(5, 10, 0))  # 33
	TParticleEffectComponent.new().Create(Entity, ("\\White\\patron_saint" + Entity.SkinFileSuffix()) + "_projectile.pfx", 6.5).ActivateOnCreate()  # 36

# Projectiles\White\PatronSaintProjectile.ets:41
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 43
	TPositionerSplineComponent.new().Create(Entity).BothTangents(PI / 16, 0.0, 1.0).BindToSubPosition(C.BIND_ZONE_WEAPON_MUZZLE, [0, 1])  # 76
	TParticleEffectComponent.new().CreateGrouped(Entity, [0], ("\\White\\patron_saint" + Entity.SkinFileSuffix()) + "_impact.pfx", 1.6).ActivateOnFireWarhead().ScaleWith(C.eiWelaAreaOfEffect)  # 80
	TParticleEffectComponent.new().CreateGrouped(Entity, [0], "\\White\\white_border_wide_once.pfx", 5.0).ActivateOnFireWarhead().FixedOrientationDefault().ScaleWith(C.eiWelaAreaOfEffect).FixedOffsetGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 84
	TCameraShakerComponent.new().CreateGrouped(Entity, []).PresetRotationLight().ActivateOnFree()  # 91
	TCameraShakerComponent.new().CreateGrouped(Entity, []).PresetVectorLight().ActivateOnFree()  # 94
	TParticleEffectComponent.new().CreateGrouped(Entity, [1], "\\White\\white_border_wide_once.pfx", 5.0).ActivateOnFireWarhead().FixedOrientationDefault().ScaleWith(C.eiWelaAreaOfEffect).FixedOffsetGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 98
	TSoundComponent.new().Create(Entity, "event:/card/white/unit/patron_saint/attack_impact").TriggerOnFree()  # 105
