# Generated by tools/transpile_scripts.py from Scripts\Projectiles\White\SuntowerProjectile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\White\SuntowerProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(20) / 1000)  # 5

# Projectiles\White\SuntowerProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10
	TOrienterMovementComponent.new().Create(Entity)  # 13
	TPointLightComponent.new().Create(Entity, 2952790015, 2.0)  # 14
	TVertexQuadComponent.new().Create(Entity, "Effects\\Textures\\LensFlare.tga", 4.0, 2.0).ScreenSpace().Additive()  # 15
	TParticleEffectComponent.new().Create(Entity, "\\White\\suntower_projectile.pfx", 8.5).ActivateOnCreate()  # 18
	TPointLightComponent.new().Create(Entity, 452919192, 10.0).SetLightShape(Vector3(3, 5, 0))  # 20

# Projectiles\White\SuntowerProjectile.ets:25
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 27
	TPositionerSplineComponent.new().Create(Entity).StartTangent(PI / 16, 0.0, 1.0).EndTangent((-PI) / 16, 0.0, 2.0).OrientStartWithTarget().BindToSubPosition(C.BIND_ZONE_WEAPON_MUZZLE, [0, 1])  # 38
	TSoundComponent.new().Create(Entity, "event:/card/white/building/suntower/attack_impact").TriggerOnFree()  # 44
