# Generated by tools/transpile_scripts.py from Scripts\Units\White\Avenger.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TStatisticsUnitComponent.new().Create(Entity)  # 27
	THealthComponent.new().Create(Entity)  # 29
	TArmorComponent.new().Create(Entity)  # 30
	TMovementComponent.new().Create(Entity)  # 31
	TThinkImpulseTimerComponent.new().Create(Entity)  # 32
	TBrainFollowLaneComponent.new().Create(Entity)  # 33
	TBrainActionComponent.new().CreateGroupedAll(Entity)  # 34
	TAutoBrainOnDeathComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).FireAtGround()  # 37
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).MustNotHave([C.upSoulless])  # 39
	TWelaEffectFactoryComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).PassCardValues()  # 41
	TPathfindingComponent.new().Create(Entity)  # 45

# Units\White\Avenger.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.7  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecWhite)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier3, C.upUnit, C.upRanged, C.upFlying])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atLight)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 230.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 230.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 6.0)  # 14 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [2], "Projectiles\\White\\AvengerProjectileBounce")  # 15
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [3], "Projectiles\\White\\AvengerProjectile")  # 16
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 2000)  # 17 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiDamageType, [1, 2, 3], [C.dtRanged])  # 18
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1, 2, 3], 42.0)  # 19 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 550)  # 20
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 966)  # 21

# Units\White\Avenger.ets:36
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 38
	InitUnitMeta(Entity)  # 39

# Units\White\Avenger.ets:64
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 66
	InitUnitEntity(Entity)  # 67
	TBrainApproachComponent.new().CreateGrouped(Entity, [0])  # 70
	TWelaTargetingRadialAttentionComponent.new().CreateGrouped(Entity, [0]).SetTargetTeamConstraint(C.tcEnemies)  # 71
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [1]).Preemptive()  # 74
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [1], true)  # 76
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [1]).SetTargetTeamConstraint(C.tcEnemies)  # 77
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).MustNotHave([C.upInvisible, C.upBanished])  # 79
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [0, 1], C.eiDamageable)  # 81
	TWelaEffectFireComponent.new().CreateGrouped(Entity, [1]).MultiTargetGroup([2]).MultiTargetGroup([3])  # 83
	TWelaReadyResourceCompareComponent.new().CreateGrouped(Entity, [2]).ComparedResource(C.reHealth).ComparedResource(C.reOverheal).SetComparator(C.coGreaterEqual).ReferenceValue(230.0).ReferenceIsAbsolute()  # 86 {@UBL_Health}
	TWelaEffectProjectileComponent.new().CreateGrouped(Entity, [2])  # 92
	TWelaEffectProjectileComponent.new().CreateGrouped(Entity, [3])  # 94
