# Generated by tools/transpile_scripts.py from Scripts\Units\White\Ballista.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TStatisticsUnitComponent.new().Create(Entity)  # 27
	THealthComponent.new().Create(Entity)  # 29
	TArmorComponent.new().Create(Entity)  # 30
	TMovementComponent.new().Create(Entity)  # 31
	TThinkImpulseTimerComponent.new().Create(Entity)  # 32
	TBrainFollowLaneComponent.new().Create(Entity)  # 33
	TBrainActionComponent.new().CreateGroupedAll(Entity)  # 34
	TAutoBrainOnDeathComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).FireAtGround()  # 37
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).MustNotHave([C.upSoulless])  # 39
	TWelaEffectFactoryComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).PassCardValues()  # 41
	TPathfindingComponent.new().Create(Entity)  # 45

# Units\White\Ballista.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.85  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecWhite)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier1, C.upUnit, C.upGround, C.upRanged])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atLight)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 64.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 64.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 14.0)  # 14 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [0, 1], "Projectiles\\White\\BallistaProjectile")  # 15
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 2800)  # 16 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtRanged, C.dtSiege])  # 17
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 23.0)  # 18 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [1], 0.1)  # 19
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 0)  # 20
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 1166)  # 21
	Entity.Blackboard.SetValue(C.eiWelaModifier, [2], 5.0)  # 24

# Units\White\Ballista.ets:40
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 42
	InitUnitMeta(Entity)  # 43

# Units\White\Ballista.ets:67
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 69
	InitUnitEntity(Entity)  # 70
	TBrainApproachComponent.new().CreateGrouped(Entity, [0])  # 73
	TWelaTargetingRadialAttentionComponent.new().CreateGrouped(Entity, [0]).DisableStraightPreference().SetTargetTeamConstraint(C.tcEnemies)  # 74
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [1]).Preemptive()  # 78
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [1], true)  # 80
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [1]).SetTargetTeamConstraint(C.tcEnemies)  # 81
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [0, 1], C.eiDamageable)  # 83
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).MustHave([C.upGround]).MustNotHave([C.upInvisible, C.upBanished])  # 85
	TWelaEffectProjectileComponent.new().CreateGrouped(Entity, [1])  # 88
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [2]).MustHave([C.upFlying])  # 91
	TModifierWelaRangeComponent.new().CreateGrouped(Entity, [1]).AddModifier().SetValueGroup([2]).ReadyGroup([2])  # 93
