# Generated by tools/transpile_scripts.py from Scripts\Units\White\PatronSaint.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TStatisticsUnitComponent.new().Create(Entity)  # 27
	THealthComponent.new().Create(Entity)  # 29
	TArmorComponent.new().Create(Entity)  # 30
	TMovementComponent.new().Create(Entity)  # 31
	TThinkImpulseTimerComponent.new().Create(Entity)  # 32
	TBrainFollowLaneComponent.new().Create(Entity)  # 33
	TBrainActionComponent.new().CreateGroupedAll(Entity)  # 34
	TAutoBrainOnDeathComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).FireAtGround()  # 37
	TWelaReadyUnitPropertyComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).MustNotHave([C.upSoulless])  # 39
	TWelaEffectFactoryComponent.new().CreateGrouped(Entity, [C.GROUP_SOUL]).PassCardValues()  # 41
	TPathfindingComponent.new().Create(Entity)  # 45

# Units\White\PatronSaint.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.6  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecWhite)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier3, C.upUnit, C.upGround, C.upRanged, C.upRangedGroundOnly, C.upLegendary])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atMedium)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 680.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 680.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 4.0)  # 14 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [1], "Projectiles\\White\\PatronSaintProjectile")  # 15
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtRanged, C.dtSplash])  # 16
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 110.0)  # 17 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 2300)  # 18 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 433)  # 19
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 2000)  # 20
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [1], 2.0)  # 21
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [2, 3], 200)  # 24
	Entity.Blackboard.SetValue(C.eiLinkPattern, [2, 3], "Links\\GuardedAura")  # 25
	Entity.Blackboard.SetValue(C.eiWelaRange, [2, 3], 6.0)  # 26
	Entity.Blackboard.SetValue(C.eiWelaActive, [2], false)  # 27

# Units\White\PatronSaint.ets:45
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 47
	InitUnitMeta(Entity)  # 48

# Units\White\PatronSaint.ets:80
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 82
	InitUnitEntity(Entity)  # 83
	TBrainApproachComponent.new().CreateGrouped(Entity, [0])  # 86
	TWelaTargetingRadialAttentionComponent.new().CreateGrouped(Entity, [0]).SetTargetTeamConstraint(C.tcEnemies)  # 87
	TWelaHelperActivateTimerComponent.new().CreateGrouped(Entity, [2]).Delay(3500)  # 91
	TBrainWelaLinkComponent.new().CreateGrouped(Entity, [2]).ThinksPassively()  # 93
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [2]).SetValidateGroup([3]).SetTargetTeamConstraint(C.tcAllies)  # 95
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [2]).MustHave([C.upUnit]).MustNotHave([C.upImmuneToGuarded, C.upGuarded])  # 98
	TWelaTargetConstraintNotSelfComponent.new().CreateGrouped(Entity, [2, 3])  # 101
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [2, 3]).MustHave([C.upUnit]).MustNotHave([C.upImmuneToGuarded])  # 102
	TWelaLinkEffectComponent.new().CreateGrouped(Entity, [2, 3]).CreatorGroup([4])  # 105
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [4]).Name("GuardingLight").TriggerOnFire()  # 107
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [1]).Preemptive()  # 112
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [1], true)  # 114
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [1]).SetTargetTeamConstraint(C.tcEnemies)  # 115
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [0, 1], C.eiDamageable)  # 117
	TWelaTargetConstraintCompareUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).BothMustHaveAny([C.upGround, C.upFlying])  # 118
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [0, 1]).MustNotHave([C.upInvisible, C.upBanished])  # 120
	TWelaEffectProjectileComponent.new().CreateGrouped(Entity, [1])  # 122
	TUnitPropertyComponent.new().CreateGrouped(Entity, [], [C.upHasLegendaryUnit]).GivePropertyOwner()  # 125
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [], "Modifiers\\LegendarySpawn.dws").PassIntValue(3500).ApplyToSelfAtCreate()  # 128
