# Generated by tools/transpile_scripts.py from Scripts\Spells\Green\EvolveThistle.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\Green\EvolveThistle.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiWelaRange, [], 4.0)  # 5
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [], 6)  # 6
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [], "Units\\Green\\Thistle")  # 7

# Spells\Green\EvolveThistle.ets:10
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 12
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, []).MustHave([C.upSapling])  # 14
	TWelaTargetConstraintAlliesComponent.new().CreateGrouped(Entity, [])  # 16

# Spells\Green\EvolveThistle.ets:25
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 27
	TThinkImpulseOnceComponent.new().CreateGrouped(Entity, [])  # 30
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, []).SetTargetTeamConstraint(C.tcAllies)  # 32
	TWelaEffectFactoryComponent.new().CreateGrouped(Entity, []).PassCardValues()  # 34
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [])  # 36
	TWarheadSpottyKillComponent.new().CreateGrouped(Entity, []).Exile()  # 37
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, []).Name("Evolve").TriggerOnFire()  # 39
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, []).Name("EvolveThistleMaxTargets").CheckMaxTargets().TriggerOnFire()  # 42
	TWelaEffectSuicideComponent.new().CreateGrouped(Entity, [])  # 46
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [])  # 48
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [], "Modifiers\\Evolve.dws").PassIntValue(1000).ApplyToProducedUnits()  # 51
