# Generated by tools/transpile_scripts.py from Scripts\Units\Colorless\MeleeGolemTower.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\BuildingTemplate.dws:3
func InitBuildingData(Entity, LimitedLifeTime: bool = false) -> void:
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 12.0)  # 5
	if LimitedLifeTime:  # 8
		Entity.Blackboard.SetValue(C.eiCooldown, [C.GROUP_BUILDING_LIFETIME], 90000)  # 9
	Entity.Blackboard.SetValue(C.eiWelaRange, [C.GROUP_SOUL], 12.0)  # 11

# HelperScripts\BuildingTemplate.dws:23
func InitBuildingMeta(Entity) -> void:
	pass

# HelperScripts\BuildingTemplate.dws:32
func InitBaseBuildingEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 34
	TStatisticsUnitComponent.new().Create(Entity)  # 37
	TPositionComponent.new().Create(Entity)  # 39
	THealthComponent.new().Create(Entity)  # 40
	TArmorComponent.new().Create(Entity)  # 41
	TThinkImpulseTimerComponent.new().Create(Entity)  # 42
	TBrainActionComponent.new().CreateGroupedAll(Entity)  # 43
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, []).Name("BuildingToBasebuilding").TriggerOnDamageDone().CheckUnitPropertyMustHave([C.upBase])  # 45
	TPathfindingComponent.new().Create(Entity)  # 51

# HelperScripts\BuildingTemplate.dws:57
func InitBuildingEntity(Entity, LimitedLifeTime: bool = false) -> void:
	InitBaseBuildingEntity(Entity)  # 59
	if LimitedLifeTime:  # 62
		TWelaHelperBeaconComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME]).TriggerAt([C.upBuildingLimitedTime])  # 64
		TBrainWelaSelftargetGroundComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME])  # 66
		TWelaEffectSuicideComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME])  # 67
	if LimitedLifeTime:  # 71
		TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], false)  # 72

# Units\Colorless\MeleeGolemTower.ets:3
func CreateData(Entity) -> void:
	InitBuildingData(Entity, false)  # 5
	Entity.CollisionRadius = 0.75  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecColorless)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier2, C.upGround, C.upBuilding, C.upMelee, C.upGolem])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atFortified)  # 10 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 655.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 655.0)  # 12 {@UBL_Health}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtMelee])  # 15
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 150.0)  # 16 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 666)  # 17
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 1033)  # 18
	Entity.Blackboard.SetValue(C.eiWelaRange, [1, 2], 0.5 + 1.0)  # 20 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiCooldown, [1, 2], 2800)  # 21 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiDamageType, [2], [C.dtMelee, C.dtSplash])  # 23
	Entity.Blackboard.SetValue(C.eiWelaDamage, [2], 0.333 * 150.0)  # 24 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [2], 2.0)  # 25
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffectCone, [2], 3.141)  # 26
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [2], 466)  # 27
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [2], 866)  # 28

# Units\Colorless\MeleeGolemTower.ets:43
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 45
	InitBuildingMeta(Entity)  # 46

# Units\Colorless\MeleeGolemTower.ets:73
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 75
	InitBuildingEntity(Entity)  # 76
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [1]).Preemptive()  # 79
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [1]).SetTargetTeamConstraint(C.tcEnemies)  # 81
	TWelaTargetConstraintResourceComponent.new().CreateGrouped(Entity, [1]).CheckResource(C.reHealth).Comparator(C.coGreaterEqual).Reference(200.0).CompareCapToReference()  # 83
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [1], C.eiDamageable)  # 88
	TWelaTargetConstraintCompareUnitPropertyComponent.new().CreateGrouped(Entity, [1]).BothMustHaveAny([C.upGround, C.upFlying])  # 89
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [1]).MustNotHave([C.upInvisible, C.upBanished])  # 91
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [1])  # 93
	TWarheadSpottyDamageComponent.new().CreateGrouped(Entity, [1])  # 94
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [1, 2], true)  # 96
	TBrainWelaFightComponent.new().CreateGrouped(Entity, [2]).Preemptive()  # 98
	TWelaTargetingRadialComponent.new().CreateGrouped(Entity, [2]).SetTargetTeamConstraint(C.tcEnemies)  # 100
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [2], C.eiDamageable)  # 102
	TWelaTargetConstraintCompareUnitPropertyComponent.new().CreateGrouped(Entity, [2]).BothMustHaveAny([C.upGround, C.upFlying])  # 103
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [2]).MustNotHave([C.upInvisible, C.upBanished])  # 105
	TWelaTargetConstraintEnemiesComponent.new().CreateGrouped(Entity, [2])  # 107
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [2])  # 108
	TWarheadSplashDamageComponent.new().CreateGrouped(Entity, [2])  # 109
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [2]).Name("Splash").TriggerOnKillDone()  # 110
