# Generated by tools/transpile_scripts.py from Scripts\Links\AegisGatlingLinkFront.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")

var InheritsFrom: String = "Links\\GatlingLinkBase.ets"  # Links\AegisGatlingLinkFront.ets:4

# Links\AegisGatlingLinkFront.ets:6
func CreateData(Entity) -> void:
	pass

# Links\AegisGatlingLinkFront.ets:10
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 12

# Links\AegisGatlingLinkFront.ets:18
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 20
