# Generated by tools/transpile_scripts.py from Scripts\Links\Homeland.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Links\Homeland.dws:3
func Apply(Entity):
	var Result: Array = []
	var Group: int = 0  # 4
	Group = Entity.ReserveFreeGroup()  # 6
	Entity.Blackboard.SetValue(C.eiWelaDamage, [Group], 10.0)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [Group], "Projectiles\\White\\HomelandProjectile")  # 8
	TAutoBrainPreventDeathComponent.new().CreateGrouped(Entity, [Group])  # 11
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [Group])  # 13
	TWarheadSpottyResourceComponent.new().CreateGrouped(Entity, [Group]).SetResourceType(C.reHealth).SetsResourceToValue()  # 14
	TWarheadSpottyRemoveBuffComponent.new().CreateGrouped(Entity, [Group]).All().MustNotHave([C.btDivine, C.btSummoningSickness])  # 17
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [Group]).Name("Rescue").TriggerOnFire()  # 20
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upRescued])  # 25
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [Group], "Modifiers\\ImmuneToRescued.dws")  # 28
	TWarheadSpottyRemoveBuffComponent.new().CreateGrouped(Entity, [Group]).MustHaveAny([C.btState])  # 31
	TWarheadSpottyTeleportComponent.new().CreateGrouped(Entity, [Group]).Offset(1.0).OffsetByCollisionRadius().AsProjectile().ToNexus()  # 33
	Result = [Group]  # 48
	return Result
