# Generated by tools/transpile_scripts.py from Scripts\Links\RootlingLink.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Links\RootlingLink.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiDamageType, [2], [C.dtRanged, C.dtSplash, C.dtAbility])  # 5
	Entity.Blackboard.SetValue(C.eiWelaDamage, [2], 10.0)  # 6
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [2], 3.0)  # 7

# Links\RootlingLink.ets:10
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 12

# Links\RootlingLink.ets:18
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 20
	TLinkBrainComponent.new().CreateGrouped(Entity, [0]).FiresAtCreate([1])  # 24
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [0])  # 26
	TWarheadSpottyDamageComponent.new().CreateGrouped(Entity, [0])  # 27
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [0]).Name("Surefire").TriggerOnDamageDone()  # 28
	TWelaEffectFireComponent.new().CreateGrouped(Entity, [0]).TargetGroup([1])  # 33
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [1]).MustHave([C.upUnit]).MustNotHave([C.upLegendary, C.upImmuneToRooted, C.upImmuneToStateEffects])  # 35
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [1])  # 38
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [1]).Name("Root").TriggerOnFire()  # 39
	TWelaEffectFireComponent.new().CreateGrouped(Entity, [0]).TargetGroup([2]).RedirectToGround()  # 44
	TWelaTargetConstraintEnemiesComponent.new().CreateGrouped(Entity, [2])  # 47
	TWelaTargetConstraintEventComponent.new().CreateGrouped(Entity, [2], C.eiDamageable)  # 48
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [2]).MustHave([C.upRooted]).MustNotHave([C.upBanished])  # 49
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [2])  # 52
	TWarheadSplashDamageComponent.new().CreateGrouped(Entity, [2])  # 53
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [2]).Name("Splash").Name("RootNetwork").TriggerOnKillDone()  # 54
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [2]).Name("Surefire").TriggerOnDamageDone()  # 58
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [1], "Modifiers\\Root.dws")  # 63
