# Generated by tools/transpile_scripts.py from Scripts\Units\Blue\Bombardier.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 12
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapUnitIcon.png")  # 13

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TPathfindingComponent.new().Create(Entity)  # 45
	TOrienterMovementComponent.new().Create(Entity)  # 48
	TOrienterTargetComponent.new().CreateGrouped(Entity, [0, 1])  # 49
	TOrienterSmoothRotateComponent.new().Create(Entity).SetAngleSpeed(0.008)  # 50
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 53
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 54
	TShowOnMinimapComponent.new().Create(Entity)  # 56

# Units\Blue\Bombardier.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.8  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecBlue)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier3, C.upUnit, C.upGround, C.upRanged, C.upImmuneToBlinded])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atLight)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 155.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 155.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reMana, 4)  # 13
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reMana, 4)  # 14
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 9.0)  # 17 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 3600)  # 18 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtRanged, C.dtSplash])  # 19
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 82.0)  # 20 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [1], 18.0)  # 21
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 333)  # 22
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 700)  # 23
	Entity.Blackboard.SetValue(C.eiWelaRange, [2], 9.0)  # 26 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiCooldown, [2], 3600)  # 27 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiDamageType, [2], [C.dtRanged, C.dtSplash])  # 28
	Entity.Blackboard.SetValue(C.eiWelaDamage, [2], 82.0)  # 29 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [2], 23.0)  # 30
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [2], 333)  # 31
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [2], 700)  # 32
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [4], C.reMana, 4)  # 34
	Entity.Blackboard.SetValue(C.eiWelaRange, [4], 20.0)  # 35
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [4], "Projectiles\\Blue\\BombardierProjectile")  # 36
	Entity.Blackboard.SetValue(C.eiDamageType, [4], [C.dtRanged, C.dtAbility])  # 37
	Entity.Blackboard.SetValue(C.eiWelaDamage, [4], 275.0)  # 38
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [4], 1033)  # 39
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [4], 3000)  # 40
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "Surefire")  # 43
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "GroundOnly")  # 44
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "LAZOR")  # 45
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [4], "WaveGun").Keyword("Stunned").PassInteger("energy_cost", 4, "energy").PassInteger("health_threshold", 300, "health").PassInteger("damage_amount", 275, "damage")  # 46
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaAttack, 4)  # 52
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaDefense, 3)  # 53
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaUtility, 3)  # 54

# Units\Blue\Bombardier.ets:58
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 60
	InitUnitMeta(Entity)  # 61
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(0, 1.1, -0.6), Vector3(0, 0.5, 0.5), 1.2)  # 64
	TMeshComponent.new().CreateGrouped(Entity, [0, 1, 2, 3, 4], "Units\\Blue\\Bombardier\\Bombardier.xml").ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_STAND, 0, 0).CreateNewAnimation(C.ANIMATION_WALK, 0, 0).CreateNewAnimation(C.ANIMATION_ATTACK, 0, 20).CreateNewAnimation(C.ANIMATION_ABILITY_1, 21, 73).BindZoneToBone(C.BIND_ZONE_CENTER, "BombadierHead").BindZoneToBone(C.BIND_ZONE_HEAD, "head").BoneOffset(C.BIND_ZONE_HEAD, 0.0, 0.15, -0.20).BindZoneToBone(C.BIND_ZONE_WEAPON_MUZZLE, "BombadierMuzzle").BoneInvertY(C.BIND_ZONE_WEAPON_MUZZLE).BoneSwapXZ(C.BIND_ZONE_WEAPON_MUZZLE).BoneOffset(C.BIND_ZONE_WEAPON_MUZZLE, 0.0, 0.0, 0.4).BindZoneToBone("exhaust0", "BombadierExhaust1").BoneInvertY("exhaust0").BoneSwapXY("exhaust0").BoneSwapYZ("exhaust0").BindZoneToBone("exhaust1", "BombadierExhaust2").BoneInvertY("exhaust1").BoneSwapXY("exhaust1").BoneSwapYZ("exhaust1").BindZoneToBone("exhaust2", "BombadierExhaust3").BoneSwapXY("exhaust2").BoneSwapYZ("exhaust2").BindZoneToBone("exhaust3", "BombadierExhaust4").BoneSwapXY("exhaust3").BoneSwapYZ("exhaust3")  # 66
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [1.8], [0])  # 93
	TAnimationComponent.new().CreateGrouped(Entity, [0, 1, 2, 3, 4]).AbilityGroup([4])  # 95

# Units\Blue\Bombardier.ets:100
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 102
	InitUnitEntity(Entity)  # 103
	TResourceDisplayIntegerProgressBarComponent.new().Create(Entity).ShowResource(C.reMana)  # 162
	TPositionerRotationComponent.new().CreateGrouped(Entity, []).Radius(0.05).RotationSpeed(0.0, 0.0, 1.6 * PI).Factor(0.0, 1.0, 0.0).Phase(L.Random()).FadeIn(1500)  # 165
	TParticleEffectComponent.new().CreateGrouped(Entity, [1, 2, 4], "\\Blue\\bombardier_muzzle_flash.pfx", 0.6).ActivateOnFire().BindToSubPosition(C.BIND_ZONE_WEAPON_MUZZLE)  # 172
	TParticleEffectComponent.new().CreateGrouped(Entity, [1], "\\Blue\\bombardier_laser.pfx", 1.0).ActivateOnFire().BindToSubPosition(C.BIND_ZONE_WEAPON_MUZZLE).IgnoreSize()  # 176
	TParticleEffectComponent.new().CreateGrouped(Entity, [2], "\\Blue\\bombardier_laser_extended.pfx", 1.0).ActivateOnFire().BindToSubPosition(C.BIND_ZONE_WEAPON_MUZZLE).IgnoreSize()  # 180
	TParticleEffectComponent.new().CreateGrouped(Entity, [4], "\\Blue\\bombardier_charge.pfx", 1.0).ActivateOnPreFire().BindToSubPosition(C.BIND_ZONE_WEAPON_MUZZLE)  # 185
	TParticleEffectComponent.new().CreateGrouped(Entity, [4], "\\Blue\\bombardier_exhaust_charge.pfx", 1.0).ActivateOnPreFire().BindToSubPosition("exhaust0")  # 188
	TParticleEffectComponent.new().CreateGrouped(Entity, [4], "\\Blue\\bombardier_exhaust_charge.pfx", 1.0).ActivateOnPreFire().BindToSubPosition("exhaust1")  # 191
	TParticleEffectComponent.new().CreateGrouped(Entity, [4], "\\Blue\\bombardier_exhaust_charge.pfx", 1.0).ActivateOnPreFire().BindToSubPosition("exhaust2")  # 194
	TParticleEffectComponent.new().CreateGrouped(Entity, [4], "\\Blue\\bombardier_exhaust_charge.pfx", 1.0).ActivateOnPreFire().BindToSubPosition("exhaust3")  # 197
	TParticleEffectComponent.new().CreateGrouped(Entity, [4], "\\Blue\\bombardier_exhaust.pfx", 1.0).ActivateOnFire().BindToSubPosition("exhaust0")  # 201
	TParticleEffectComponent.new().CreateGrouped(Entity, [4], "\\Blue\\bombardier_exhaust.pfx", 1.0).ActivateOnFire().BindToSubPosition("exhaust1")  # 204
	TParticleEffectComponent.new().CreateGrouped(Entity, [4], "\\Blue\\bombardier_exhaust.pfx", 1.0).ActivateOnFire().BindToSubPosition("exhaust2")  # 207
	TParticleEffectComponent.new().CreateGrouped(Entity, [4], "\\Blue\\bombardier_exhaust.pfx", 1.0).ActivateOnFire().BindToSubPosition("exhaust3")  # 210
	TSoundComponent.new().CreateGrouped(Entity, [1, 2], "event:/card/blue/unit/bombardier/attack_fire").TriggerOnPreFire()  # 214
	TSoundComponent.new().CreateGrouped(Entity, [4], "event:/card/blue/unit/bombardier/wavegun_fire").TriggerOnPreFire()  # 217
	TCameraShakerComponent.new().CreateGrouped(Entity, [4]).PresetRotationStrong().ActivateOnFire()  # 220
	TCameraShakerComponent.new().CreateGrouped(Entity, [4]).PresetVectorStrong().ActivateOnFire()  # 224
