# Generated by tools/transpile_scripts.py from Scripts\Units\Blue\ObserverDrone.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\BuildingTemplate.dws:3
func InitBuildingData(Entity, LimitedLifeTime: bool = false) -> void:
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 12.0)  # 5
	if LimitedLifeTime:  # 8
		Entity.Blackboard.SetValue(C.eiCooldown, [C.GROUP_BUILDING_LIFETIME], 90000)  # 9
	Entity.Blackboard.SetValue(C.eiWelaRange, [C.GROUP_SOUL], 12.0)  # 11
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 14
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapBuildingIcon.png")  # 15
	if LimitedLifeTime:  # 17
		TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], "TimedLifeBuilding").PassInteger("duration", 90)  # 18

# HelperScripts\BuildingTemplate.dws:23
func InitBuildingMeta(Entity) -> void:
	pass

# HelperScripts\BuildingTemplate.dws:32
func InitBaseBuildingEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 34
	TPathfindingComponent.new().Create(Entity)  # 51

# HelperScripts\BuildingTemplate.dws:57
func InitBuildingEntity(Entity, LimitedLifeTime: bool = false) -> void:
	InitBaseBuildingEntity(Entity)  # 59
	if LimitedLifeTime:  # 71
		TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], false)  # 72
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 75
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 76
	TShowOnMinimapComponent.new().Create(Entity)  # 78
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/env/building/shared/hit").TriggerOnLoseHealth()  # 79
	if LimitedLifeTime:  # 82
		TIndicatorCooldownCircleComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME]).SetTexture(C.PATH_GRAPHICS_EFFECTS_TEXTURES + "ProgressCircle.tga").SetRadius(1.5).ScaleWith(C.eiCollisionRadius).SetThickness(0.1).SetLinearBlend().Color(1627389951).Invert()  # 84

# Units\Blue\ObserverDrone.ets:3
func CreateData(Entity) -> void:
	InitBuildingData(Entity)  # 5
	Entity.CollisionRadius = 0.45  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecBlue)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier1, C.upFlying, C.upBuilding, C.upUnit, C.upGadget, C.upNoAutoAttack, C.upSupporter])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atFortified)  # 10 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 78.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 78.0)  # 12 {@UBL_Health}
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [2, 3], 200)  # 15
	Entity.Blackboard.SetValue(C.eiLinkPattern, [2, 3], "Links\\RangeUpgradeAura")  # 16
	Entity.Blackboard.SetValue(C.eiWelaRange, [2, 3], 4.0)  # 17
	Entity.Blackboard.SetValue(C.eiWelaActive, [2], false)  # 18
	Entity.Blackboard.SetValue(C.eiWelaDamage, [4, 5], 1.0)  # 21
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [6], 1)  # 24
	Entity.Blackboard.SetValue(C.eiLinkPattern, [6], "Links\\InvisibleAura")  # 25
	Entity.Blackboard.SetValue(C.eiWelaRange, [6, 7], 15.0)  # 26
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [], "Flying")  # 29
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [], "LimitedGadget").PassInteger("gadget_limit", 5).PassInteger("gadget_limit_exceeded", 6)  # 30
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [], "Stationary")  # 33
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [], "CloakGround").Keyword("Stealthed")  # 34
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [2], "RangeAura").PassInteger("range_increase_units", 3, "range").PassInteger("range_increase_buildings", 5, "range")  # 36
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHealthbarOffset, 3.5)  # 40
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaAttack, 3)  # 42
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaDefense, 7)  # 43
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaUtility, 0)  # 44

# Units\Blue\ObserverDrone.ets:48
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 50
	InitBuildingMeta(Entity)  # 51
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(-0.2, 1.3, 0), Vector3(0.2, 1.3, 0), 0.6)  # 54
	TPositionerOffsetComponent.new().Create(Entity).Offset(0.0, C.FLYING_HEIGHT, 0.0)  # 56
	TMeshComponent.new().CreateGrouped(Entity, [0, 1], ("Units\\Blue\\ObserverDrone" + Entity.SkinFileSuffix()) + "\\ObserverDrone.xml").ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_STAND, 0, 69).BindZoneToBone(C.BIND_ZONE_CENTER, "CATRigHub001").BoneSwapXZ(C.BIND_ZONE_CENTER).BoneSwapXY(C.BIND_ZONE_CENTER).BindZoneToBone(C.BIND_ZONE_WEAPON_MUZZLE, "CATRigHub001").BoneSwapXZ(C.BIND_ZONE_WEAPON_MUZZLE).BoneSwapXY(C.BIND_ZONE_WEAPON_MUZZLE).BindZoneToBone(C.BIND_ZONE_TOP, "CATRigHub001").BoneSwapXZ(C.BIND_ZONE_TOP).BoneSwapXY(C.BIND_ZONE_TOP).BoneOffset(C.BIND_ZONE_TOP, 0.0, 0.3, 0.0).BindZoneToBone("engine_bottom", "CATRigHub001").BoneSwapXY("engine_bottom").BoneSwapYZ("engine_bottom").BoneInvertZ("engine_bottom").BoneOffset("engine_bottom", 0.0, 0.0, 0.1).BindZoneToBone("engine_left", "CATRigLArmCollarbone").BoneSwapXY("engine_left").BoneOffset("engine_left", 0.0, 0.2, 0.0).BoneRotation("engine_left", 0.025, 0.0, 0.0).BindZoneToBone("engine_right", "CATRigRArmCollarbone").BoneSwapXY("engine_right").BoneInvertZ("engine_right").BoneOffset("engine_right", 0.0, 0.2, 0.0).BoneRotation("engine_right", 0.025, 0.0, 0.0).SetModelOffset(0.0, -1.7, 0.0)  # 59
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [2.0], [0])  # 88
	TAnimationComponent.new().CreateGrouped(Entity, [1])  # 89
	TTextureRangeIndicatorComponent.new().CreateGrouped(Entity, [2]).SetTexture("SpelltargetGeneric.png")  # 91

# Units\Blue\ObserverDrone.ets:96
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 98
	InitBuildingEntity(Entity)  # 99
	TPositionerRotationComponent.new().CreateGrouped(Entity, []).Radius(0.025).RotationSpeed(0.45 * PI, 0.55 * PI, 0.65 * PI).Factor(1.0, 0.0, 1.0).Phase(L.Random()).FadeIn(1500)  # 153
	TParticleEffectComponent.new().CreateGrouped(Entity, [], "\\Blue\\flight_engine.pfx", 1.0).ActivateOnCreate().Delay(1000).BindToSubPosition("engine_bottom")  # 160
	TParticleEffectComponent.new().CreateGrouped(Entity, [], "\\Blue\\flight_engine.pfx", 1.0).ActivateOnCreate().Delay(1200).BindToSubPosition("engine_left")  # 165
	TParticleEffectComponent.new().CreateGrouped(Entity, [], "\\Blue\\flight_engine.pfx", 1.0).ActivateOnCreate().Delay(1300).BindToSubPosition("engine_right")  # 170
	TParticleEffectComponent.new().CreateGrouped(Entity, [2], ("\\Blue\\observer" + Entity.SkinFileSuffix()) + "_aura_field.pfx", 5.0).ActivateOnCreate().ActivateOnWelaActivate().FixedOrientationDefault().FixedHeightGround().ScaleWith(C.eiWelaRange)  # 175
	TParticleEffectComponent.new().CreateGrouped(Entity, [2], "\\Blue\\blue_border_wide.pfx", 5.0).IgnoreModelSize().ActivateOnCreate().ActivateOnWelaActivate().ScaleWith(C.eiWelaRange).FixedOrientationDefault().FixedHeightGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 182
