# Generated by tools/transpile_scripts.py from Scripts\Units\Blue\PhaseDrone.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 12
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapUnitIcon.png")  # 13

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TPathfindingComponent.new().Create(Entity)  # 45
	TOrienterMovementComponent.new().Create(Entity)  # 48
	TOrienterTargetComponent.new().CreateGrouped(Entity, [0, 1])  # 49
	TOrienterSmoothRotateComponent.new().Create(Entity).SetAngleSpeed(0.008)  # 50
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 53
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 54
	TShowOnMinimapComponent.new().Create(Entity)  # 56

# Units\Blue\PhaseDrone.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.7  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecBlue)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier2, C.upUnit, C.upGround, C.upMelee])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atMedium)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 165.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 165.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reMana, 2)  # 13
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reMana, 2)  # 14
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 1.0)  # 17 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtMelee])  # 18
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 16.0)  # 19 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 2000)  # 20 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 400)  # 21
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 966)  # 22
	Entity.Blackboard.SetValue(C.eiCooldown, [2], 8000)  # 25
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [3], C.reMana, 2)  # 28
	Entity.Blackboard.SetValue(C.eiWelaRange, [3], 8.0)  # 29
	Entity.Blackboard.SetValue(C.eiCooldown, [3], 3000)  # 30
	Entity.Blackboard.SetValue(C.eiDamageType, [3], [C.dtMelee, C.dtAbility])  # 31
	Entity.Blackboard.SetValue(C.eiWelaDamage, [3], 100.0)  # 32
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [3], 333)  # 33
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [3], 1066)  # 34
	Entity.Blackboard.SetValue(C.eiWelaRange, [4], 12.0)  # 37
	Entity.Blackboard.SetValue(C.eiWelaDamage, [4], 1.0)  # 38
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [2], "Shieldoverload").PassInteger("duration", 2).PassInteger("cooldown", 8)  # 41
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [3], "TeleportStrike").PassInteger("energy_cost", 2).PassInteger("damage_amount", 100, "damage").PassInteger("cooldown", 3)  # 44
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [4], "InductionEnergy").PassInteger("energy_amount", 1, "energy")  # 48
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaAttack, 3)  # 51
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaDefense, 6)  # 52
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaUtility, 1)  # 53

# Units\Blue\PhaseDrone.ets:57
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 59
	InitUnitMeta(Entity)  # 60
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(0.1, 0, 0.1), Vector3(0.1, 1.0, 0.1), 0.9)  # 63
	TMeshComponent.new().CreateGrouped(Entity, [0, 1, 3], ("Units\\Blue\\Phasedrone" + Entity.SkinFileSuffix()) + "\\Phasedrone.xml").ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_STAND, 87, 146).CreateNewAnimation(C.ANIMATION_WALK, 0, 23).CreateNewAnimation(C.ANIMATION_ATTACK, 25, 53).CreateNewAnimation(C.ANIMATION_ABILITY_1, 54, 85).BindZoneToBone(C.BIND_ZONE_WEAPON, "PhaseDroneLArmPalm").BindZoneToBone(C.BIND_ZONE_HEAD, "PhaseDroneHub002").BoneSwizzleYZX(C.BIND_ZONE_HEAD).BoneOffset(C.BIND_ZONE_HEAD, 0.0, 0.4, 0.3).BindZoneToBone(C.BIND_ZONE_CENTER, "PhaseDroneHub002").BoneSwapXZ(C.BIND_ZONE_CENTER).BoneSwapYZ(C.BIND_ZONE_CENTER)  # 65
	if Entity.SkinID == C.SKIN_GROUP_CRUSADER:  # 79
		TMeshEffectMetal.new().Create().ShowAsColor(C.ecWhite).AssignToEntity(Entity)  # 80
	TAnimationComponent.new().CreateGrouped(Entity, [0, 1, 3]).AbilityGroup([3])  # 84
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [1.8], [0])  # 86

# Units\Blue\PhaseDrone.ets:90
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 92
	InitUnitEntity(Entity)  # 93
	if Entity.SkinID == C.SKIN_GROUP_CRUSADER:  # 166
		TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [2], "Modifiers\\Invincibility.dws")  # 167
	else:
		TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [2], "Modifiers\\Invincibility.dws").Methodname("ApplyBlue")  # 169
	TResourceDisplayIntegerProgressBarComponent.new().Create(Entity).ShowResource(C.reMana)  # 173
	TSoundComponent.new().CreateGrouped(Entity, [1], "event:/card/blue/unit/phasedrone/attack_fire").TriggerOnPreFire().StopOnFree()  # 176
	TParticleEffectComponent.new().CreateGrouped(Entity, [3], ("\\Blue\\phase_drone" + Entity.SkinFileSuffix()) + "_teleport_strike_trigger.pfx", 0.5).ActivateOnPreFire().ScaleWith(C.eiCollisionRadius).BindToSubPositionGroup(C.BIND_ZONE_CENTER, [0, 1])  # 180
	TParticleEffectComponent.new().CreateGrouped(Entity, [3], ("\\Blue\\phase_drone" + Entity.SkinFileSuffix()) + "_teleport_strike_impact.pfx", 0.5).Delay(100).ActivateOnFire().ScaleWith(C.eiCollisionRadius).BindToSubPositionGroup(C.BIND_ZONE_CENTER, [0, 1])  # 185
	TCameraShakerComponent.new().CreateGrouped(Entity, [3]).PresetRotationLight().ActivateOnFire()  # 191
	TCameraShakerComponent.new().CreateGrouped(Entity, [3]).PresetVectorLight().ActivateOnFire()  # 195
	TSoundComponent.new().CreateGrouped(Entity, [3], "event:/card/blue/unit/phasedrone/teleport_strike_fire").TriggerOnPreFire().StopOnFree()  # 199
	TParticleEffectComponent.new().CreateGrouped(Entity, [4], "\\Blue\\induction_energy.pfx", 1.2).ActivateOnFire().BindToSubPositionGroup(C.BIND_ZONE_CENTER, [0, 1])  # 203
	TSoundComponent.new().CreateGrouped(Entity, [4], "event:/card/blue/unit/phasedrone/induction_energy_fire").TriggerOnFire()  # 207
