# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Black\FrostspearProjectile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Black\FrostspearProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(14) / 1000)  # 5

# Projectiles\Black\FrostspearProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10
	TVertexQuadComponent.new().Create(Entity, "Effects\\Spells\\Black\\Frostspear\\FrostspearProjectile.png", 1.2, 0.6).CameraOriented()  # 13
	TParticleEffectComponent.new().Create(Entity, "\\Black\\frostspear_projectile.pfx", 8.3).ActivateOnCreate()  # 16

# Projectiles\Black\FrostspearProjectile.ets:21
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 23
	TPositionerSplineComponent.new().Create(Entity).StartTangent(PI / 3, 0.0, 3.0).StartTangentRandom(PI / 8, PI, 0.0).EndTangent(PI / 8, 0.0, 0.0).OrientStartWithTarget().BindToSubPosition(C.BIND_ZONE_CENTER, [0, 1])  # 40
	TSoundComponent.new().Create(Entity, "event:/card/black/spell/frostspear/attack_impact").TriggerOnFree()  # 47
