# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Black\VecraProjectile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Black\VecraProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(22) / 1000)  # 5

# Projectiles\Black\VecraProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10
	TParticleEffectComponent.new().Create(Entity, ("\\Black\\vecra" + Entity.SkinFileSuffix()) + "_projectile.pfx", 2.2).ActivateOnCreate()  # 13

# Projectiles\Black\VecraProjectile.ets:18
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 20
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [1], "Modifiers\\Frozen.dws")  # 45
	TPositionerSplineComponent.new().Create(Entity).StartTangent(0.0, 0.0, 0.5).EndTangent(0.0, 0.0, 0.0).BindToSubPosition(C.BIND_ZONE_WEAPON_MUZZLE, [0, 1])  # 48
	TSoundComponent.new().Create(Entity, "event:/card/black/unit/vecra/attack_impact").TriggerOnFree()  # 53
