# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Black\VecraFreeze.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Black\VecraFreeze.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiWelaRange, [0], 8.0)  # 5
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [0], 200)  # 6
	Entity.Blackboard.SetValue(C.eiWelaAreaOfEffect, [1], 8.0)  # 8
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 1000.0)  # 9
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtSpell, C.dtSplash])  # 10

# Projectiles\Black\VecraFreeze.ets:13
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 15

# Projectiles\Black\VecraFreeze.ets:21
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 23
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [0], "Modifiers\\Frozen.dws")  # 65
	TParticleEffectComponent.new().CreateGrouped(Entity, [0], ("\\Black\\vecra" + Entity.SkinFileSuffix()) + "_freeze.pfx", 7.0).ActivateOnCreate().ScaleWith(C.eiWelaRange)  # 68
	TParticleEffectComponent.new().CreateGrouped(Entity, [0], "\\Black\\black_border_wide_once.pfx", 5.0).ActivateOnCreate().FixedOrientationDefault().ScaleWith(C.eiWelaRange).FixedHeightGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 72
	TCameraShakerComponent.new().CreateGrouped(Entity, []).PresetRotationStrong().ActivateOnFree()  # 79
	TCameraShakerComponent.new().CreateGrouped(Entity, []).PresetVectorStrong().ActivateOnFree()  # 83
