# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Black\VoidWormProjectile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Black\VoidWormProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(20) / 1000)  # 5

# Projectiles\Black\VoidWormProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10
	TMeshComponent.new().CreateGrouped(Entity, [0, 1], "Units\\Black\\VoidWorm_Default\\Frostblob.xml").ApplyLegacySizeFactor().SetModelRotationOffset(Vector3(3.141 / 2, 0, 0))  # 13
	TMeshEffectWobble.new().Create(C.PATH_GRAPHICS + "Units\\Black\\VoidWorm_Default\\FrostblobVoidMask.tga").AssignToEntity(Entity)  # 17
	TMeshEffectMatcap.new().Create().SetTexture(C.PATH_GRAPHICS_EFFECTS_TEXTURES + "MatcapIce.png").AssignToEntity(Entity)  # 19
	TParticleEffectComponent.new().Create(Entity, "\\Black\\voidworm_projectile.pfx", 5.0).ActivateOnCreate()  # 23
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [1.6], [0])  # 26

# Projectiles\Black\VoidWormProjectile.ets:30
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 32
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [1], "Modifiers\\Frozen.dws")  # 56
	TPositionerSplineComponent.new().Create(Entity).BothTangents(PI / 16, 0.0, 1.0)  # 59
	TSoundComponent.new().Create(Entity, "event:/card/black/unit/voidworm/attack_impact").TriggerOnFree()  # 62
