# Generated by tools/transpile_scripts.py from Scripts\Projectiles\Black\VoidCauldronProjectile.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Projectiles\Black\VoidCauldronProjectile.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(14) / 1000)  # 5

# Projectiles\Black\VoidCauldronProjectile.ets:8
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 10
	TParticleEffectComponent.new().Create(Entity, "\\Black\\voidcauldron_projectile.pfx", 6.0).ActivateOnCreate()  # 13

# Projectiles\Black\VoidCauldronProjectile.ets:18
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 20
	TPositionerSplineComponent.new().Create(Entity).StartTangent(PI / 2, 0.0, 6.0).EndTangent(PI / 16, 0.0, 1.0)  # 34
	TSoundComponent.new().Create(Entity, "event:/card/black/unit/voidcauldron/attack_impact").TriggerOnFree()  # 38
