"""Transpiles the original's DWScript scripts to GDScript (phase 1, see docs/scripts.md).

Usage: python tools/transpile_scripts.py [--check] [--only SUBSTRING]

For every script under reference/.../Scripts (HelperScripts are include-only) and each side (CLIENT, SERVER):
preprocess exactly like the original -> parse -> emit src/content/scripts/{client,server}/<path>.gd.
Also writes
- src/runtime/dws/dws_const.gd: the enum values and constants the original exposes to scripts,
- src/runtime/dws/stubs/<Class>.gd: a `class_name` stub for every Delphi class the scripts reference (and its
  ancestors) that no hand-written file in src/ declares yet; phase 2 replaces them one by one,
- src/content/scripts/script_index.gd: lower-case original path -> generated file, per side (the original
  resolves script paths case-insensitively).
Exit code 1 if any script fails; the failing file and line are printed and nothing is skipped silently.
--check: transpile everything but write nothing (used by the tests).
"""
from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dws.emitter import EmitError, Emitter, gd_string  # noqa: E402
from dws.lexer import LexError  # noqa: E402
from dws.parser import ParseError, parse  # noqa: E402
from dws.preprocess import Preprocessor  # noqa: E402
from dws.symbols import SymbolTable  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, 'reference', 'rise-of-legions')
SCRIPTS = os.path.join(SOURCE, 'Scripts')
OUT = os.path.join(ROOT, 'src', 'content', 'scripts')
RUNTIME = os.path.join(ROOT, 'src', 'runtime', 'dws')
API_DOC = os.path.join(ROOT, 'docs', 'script-api.md')
SIDES = ('CLIENT', 'SERVER')
EXTENSIONS = ('.ets', '.dws', '.sps')

# Scripts the original itself cannot compile on a side. They become a file that only carries the error, so the
# runtime fails on them exactly where the original did.
ORIGINAL_COMPILE_ERRORS = {
    ('ai\\megarootdude.dws', 'SERVER'): 'Unknown name "ArcherDrop" (Prepare assigns an undeclared variable)',
}
STUB_HEADER = '# STUB generated by tools/transpile_scripts.py'


def script_files() -> list[str]:
    found = []
    for folder, _, files in os.walk(SCRIPTS):
        if os.path.relpath(folder, SCRIPTS).lower().startswith('helperscripts'):
            continue
        for name in files:
            if name.lower().endswith(EXTENSIONS):
                found.append(os.path.relpath(os.path.join(folder, name), SCRIPTS))
    return sorted(found, key=str.lower)


def out_path(rel: str, side: str) -> str:
    return os.path.join(OUT, side.lower(), rel + '.gd')


def res_path(path: str) -> str:
    return 'res://' + os.path.relpath(path, ROOT).replace('\\', '/')


def write(path: str, text: str, written: set[str]) -> None:
    written.add(os.path.normcase(os.path.abspath(path)))
    os.makedirs(os.path.dirname(path), exist_ok=True)
    old = None
    if os.path.exists(path):
        with open(path, encoding='utf-8', newline='') as f:
            old = f.read()
    if old != text:
        with open(path, 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)


def error_script(rel: str, side: str, message: str) -> str:
    return '\n'.join([
        f'# Generated by tools/transpile_scripts.py from Scripts\\{rel} ({side}).',
        '# The original does not compile this script on this side; the runtime reports the error like it did.',
        'extends RefCounted', '', f'const ORIGINAL_COMPILE_ERROR = {gd_string(message)}', ''])


# ---- constants --------------------------------------------------------------------------------------------------
def eval_const(sym: SymbolTable, name: str, seen: frozenset = frozenset()):
    """Evaluates a Delphi constant: literals, other constants, + - * and parentheses."""
    if name.lower() in seen:
        raise ValueError(f'constant {name} refers to itself')
    _, _, toks = sym.consts[name.lower()]
    pos = 0

    def atom():
        nonlocal pos
        tok = toks[pos]
        pos += 1
        if tok.is_('sym', '-'):
            return -atom()
        if tok.is_('sym', '('):
            value = expr()
            pos += 1
            return value
        if tok.kind == 'int':
            return int(tok.value)
        if tok.kind == 'float':
            return float(tok.value)
        if tok.kind == 'string':
            return tok.value
        if tok.kind == 'ident' and tok.key in sym.consts:
            return eval_const(sym, tok.value, seen | {name.lower()})
        if tok.kind == 'ident' and tok.key in sym.enum_values:
            return sym.enum_values[tok.key][1]
        if tok.kind == 'ident' and tok.key in ('true', 'false'):
            return tok.key == 'true'
        raise ValueError(f'{tok.file}:{tok.line}: cannot evaluate {tok.value!r} in constant {name}')

    def expr():
        nonlocal pos
        value = atom()
        while pos < len(toks) and toks[pos].kind == 'sym' and toks[pos].value in '+-*':
            op = toks[pos].value
            pos += 1
            rhs = atom()
            value = value + rhs if op == '+' else value - rhs if op == '-' else value * rhs
        return value

    value = expr()
    if pos != len(toks):
        raise ValueError(f'{toks[pos].file}:{toks[pos].line}: cannot evaluate constant {name}')
    return value


def gd_literal(value) -> str:
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, str):
        return gd_string(value)
    return repr(value)


def const_script(sym: SymbolTable) -> tuple[str, list[str]]:
    lines = ['# Generated by tools/transpile_scripts.py: the enum values and constants the original exposes to',
             '# scripts (ScriptManager.ExposeType / ExposeConstant). Do not edit.', 'extends RefCounted', '']
    errors = []
    for type_name in sym.exposed_types:
        enum = sym.enums.get(type_name.lower())
        if enum is None:
            continue
        lines.append(f'# {enum.name} ({enum.file})')
        lines.extend(f'const {value} = {ordinal}' for value, ordinal in enum.values)
        lines.append('')
    lines.append('# ExposeConstant')
    for name in sym.exposed_consts:
        spelling = sym.consts[name.lower()][0]
        try:
            lines.append(f'const {spelling} = {gd_literal(eval_const(sym, name))}')
        except ValueError as e:
            errors.append(str(e))
    return '\n'.join(lines) + '\n', errors


# ---- stubs ------------------------------------------------------------------------------------------------------
def declared_class_names() -> dict[str, str]:
    """class_name -> file for every hand-written (non-stub) GDScript file in src/."""
    found = {}
    for folder, _, files in os.walk(os.path.join(ROOT, 'src')):
        for name in files:
            if not name.endswith('.gd'):
                continue
            path = os.path.join(folder, name)
            with open(path, encoding='utf-8') as f:
                text = f.read()
            if text.startswith(STUB_HEADER):
                continue
            for line in text.splitlines():
                if line.startswith('class_name '):
                    found[line.split()[1]] = path
    return found


def stub_scripts(sym: SymbolTable, used: set[str]) -> dict[str, str]:
    """Stub file text per class name, for the used classes and all their ancestors."""
    real = declared_class_names()
    stubs = {}
    for name in sorted(used):
        for decl in sym.ancestors(name):
            if decl.name in stubs or decl.name in real:
                continue
            chain = sym.ancestors(decl.name)
            parent = chain[1].name if len(chain) > 1 else 'RefCounted'
            stubs[decl.name] = '\n'.join([
                f'{STUB_HEADER} for {decl.name} ({decl.file}:{decl.line}).',
                '# Phase 2 replaces it with the real class (delete this file when a real one declares the name).',
                f'class_name {decl.name}', f'extends {parent}', ''])
    return stubs


def api_doc(sym: SymbolTable, api: dict, used_classes: set[str]) -> str:
    """docs/script-api.md: every class member the transpiled scripts use (the phase 2 work list)."""
    lines = ['# Script API used by the transpiled scripts', '',
             'Generated by `tools/transpile_scripts.py`; do not edit. The phase 2 work list: every member of an',
             'original class that some script calls (`M()`), reads (`M`) or assigns (`M :=`), under the class that',
             'declares it, with the sides that use it (C = client, S = server). A `?` owner means the receiver\'s',
             'type was not known statically; the member exists on all the listed classes with the same spelling.',
             'Delphi overloads share one GDScript method: see the declarations for their parameter lists.', '',
             f'{len(used_classes)} classes are referenced by name; {len(api)} declare used members.', '']
    for owner in sorted(api, key=lambda o: (o.startswith('?'), o.lower())):
        decl = sym.types.get(owner.lower())
        where = f' ({decl.file.replace(chr(92), "/")}:{decl.line})' if decl else ''
        lines.append(f'## {owner}{where}')
        lines.append('')
        items = []
        for (member, use), sides in sorted(api[owner].items(), key=lambda kv: kv[0][0].lower()):
            text = member + {'call': '()', 'read': '', 'write': ' :='}[use]
            items.append(f'`{text}` {"".join(sorted(sides))}')
        lines.append(', '.join(items))
        lines.append('')
    return '\n'.join(lines)


# ---- main -------------------------------------------------------------------------------------------------------
def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true', help='transpile but write nothing')
    ap.add_argument('--only', help='only scripts whose path contains this text (case-insensitive)')
    args = ap.parse_args()
    if not os.path.isdir(SCRIPTS):
        print(f'missing {SCRIPTS}: run tools/fetch_reference.ps1 first')
        return 1

    sym = SymbolTable.scan(SOURCE)
    files = [f for f in script_files() if not args.only or args.only.lower() in f.lower()]
    errors: list[str] = []
    outputs: dict[str, str] = {}
    index: dict[str, dict[str, str]] = {side: {} for side in SIDES}
    used_classes: set[str] = set()
    api: dict[str, dict[tuple[str, str], set[str]]] = {}   # owner -> (member, use) -> sides
    for side in SIDES:
        for rel in files:
            path = out_path(rel, side)
            known = ORIGINAL_COMPILE_ERRORS.get((rel.lower(), side))
            try:
                tokens = Preprocessor(SCRIPTS, {side}).load_script(os.path.join(SCRIPTS, rel))
                emitter = Emitter(sym, rel, side)
                text = emitter.emit(parse(tokens))
                if known:
                    errors.append(f'[{side}] {rel}: listed as an original compile error but transpiles; '
                                  'remove it from ORIGINAL_COMPILE_ERRORS')
                    continue
                used_classes |= emitter.used_classes
                for owner, member, use in emitter.used_members:
                    api.setdefault(owner, {}).setdefault((member, use), set()).add(side[0])
            except (LexError, ParseError, EmitError) as e:
                if not known:
                    errors.append(f'[{side}] {e}')
                    continue
                text = error_script(rel, side, known)
            outputs[path] = text
            index[side][rel.lower().replace('/', '\\')] = res_path(path)

    const_text, const_errors = const_script(sym)
    errors.extend(const_errors)
    for e in errors:
        print('ERROR', e)
    print(f'{len(files)} scripts x {len(SIDES)} sides: {len(outputs)} written, {len(errors)} errors; '
          f'{len(used_classes)} Delphi classes referenced')
    if errors:
        return 1
    if args.check:
        outdated = []
        for path, text in list(outputs.items()) + [(os.path.join(RUNTIME, 'dws_const.gd'), const_text)]:
            try:
                with open(path, encoding='utf-8', newline='') as f:
                    same = f.read() == text
            except OSError:
                same = False
            if not same:
                outdated.append(os.path.relpath(path, ROOT))
        for path in outdated[:20]:
            print('OUT OF DATE', path)
        if outdated:
            print(f'{len(outdated)} generated files are out of date: run python tools/transpile_scripts.py')
        return 1 if outdated else 0

    written: set[str] = set()
    for path, text in outputs.items():
        write(path, text, written)
    write(os.path.join(RUNTIME, 'dws_const.gd'), const_text, written)
    stubs = stub_scripts(sym, used_classes)
    for name, text in stubs.items():
        write(os.path.join(RUNTIME, 'stubs', name + '.gd'), text, written)
    index_lines = ['# Generated by tools/transpile_scripts.py: original script path (lower case, as the original',
                   '# resolves it case-insensitively) -> generated GDScript, per side. Do not edit.',
                   'extends RefCounted', '']
    for side in SIDES:
        index_lines.append(f'const {side} = {{')
        index_lines.extend(f'\t{gd_string(k)}: {gd_string(v)},' for k, v in sorted(index[side].items()))
        index_lines.append('}')
        index_lines.append('')
    write(os.path.join(OUT, 'script_index.gd'), '\n'.join(index_lines), written)
    if not args.only:
        write(API_DOC, api_doc(sym, api, used_classes), set())

    # stale outputs: generated files this run did not produce (a script or stub that no longer exists)
    stale = 0
    for folder in (OUT, os.path.join(RUNTIME, 'stubs')) if not args.only else ():
        for dirpath, _, names in os.walk(folder):
            for name in names:
                path = os.path.normcase(os.path.abspath(os.path.join(dirpath, name)))
                script = path[:-len('.uid')] if path.endswith('.gd.uid') else path
                if script.endswith('.gd') and script not in written:
                    os.remove(path)
                    stale += 1
    print(f'stubs: {len(stubs)}; stale files removed: {stale}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
