"""Transpiles the original's DWScript scripts to GDScript (phase 1, see docs/scripts.md).

Usage: python tools/transpile_scripts.py [--check] [--only SUBSTRING]

For every script under reference/.../Scripts (HelperScripts are include-only) and each side (CLIENT, SERVER):
preprocess exactly like the original -> parse -> emit src/content/scripts/{client,server}/<path>.gd.
Also writes
- src/runtime/dws/dws_const.gd: the enum values and constants the original exposes to scripts (and the same for the
  C++ game code: native/src/dws/dws_const.h),
- src/runtime/dws/stubs/<Class>.gd: a `class_name` stub for every Delphi class the scripts reference (and its
  ancestors) that no hand-written file in src/ declares yet; phase 2 replaces them one by one,
- src/content/scripts/script_index.gd: lower-case original path -> generated file, per side (the original
  resolves script paths case-insensitively).
Exit code 1 if any script fails; the failing file and line are printed and nothing is skipped silently.
--check: transpile everything but write nothing (used by the tests).
"""
from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dws.emitter import EmitError, Emitter, gd_string  # noqa: E402
from dws.lexer import LexError  # noqa: E402
from dws.parser import ParseError, parse  # noqa: E402
from dws.preprocess import Preprocessor  # noqa: E402
from dws.symbols import SymbolTable  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, 'reference', 'rise-of-legions')
SCRIPTS = os.path.join(SOURCE, 'Scripts')
OUT = os.path.join(ROOT, 'src', 'content', 'scripts')
RUNTIME = os.path.join(ROOT, 'src', 'runtime', 'dws')
API_DOC = os.path.join(ROOT, 'docs', 'script-api.md')
SIDES = ('CLIENT', 'SERVER')
EXTENSIONS = ('.ets', '.dws', '.sps')

# Scripts the original itself cannot compile on a side. They become a file that only carries the error, so the
# runtime fails on them exactly where the original did.
ORIGINAL_COMPILE_ERRORS = {
    ('ai\\megarootdude.dws', 'SERVER'): 'Unknown name "ArcherDrop" (Prepare assigns an undeclared variable)',
}
STUB_HEADER = '# STUB generated by tools/transpile_scripts.py'


def script_files() -> list[str]:
    found = []
    for folder, _, files in os.walk(SCRIPTS):
        if os.path.relpath(folder, SCRIPTS).lower().startswith('helperscripts'):
            continue
        for name in files:
            if name.lower().endswith(EXTENSIONS):
                found.append(os.path.relpath(os.path.join(folder, name), SCRIPTS))
    return sorted(found, key=str.lower)


def out_path(rel: str, side: str) -> str:
    return os.path.join(OUT, side.lower(), rel + '.gd')


def res_path(path: str) -> str:
    return 'res://' + os.path.relpath(path, ROOT).replace('\\', '/')


def write(path: str, text: str, written: set[str]) -> None:
    written.add(os.path.normcase(os.path.abspath(path)))
    os.makedirs(os.path.dirname(path), exist_ok=True)
    old = None
    if os.path.exists(path):
        with open(path, encoding='utf-8', newline='') as f:
            old = f.read()
    if old != text:
        with open(path, 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)


def error_script(rel: str, side: str, message: str) -> str:
    return '\n'.join([
        f'# Generated by tools/transpile_scripts.py from Scripts\\{rel} ({side}).',
        '# The original does not compile this script on this side; the runtime reports the error like it did.',
        'extends RefCounted', '', f'const ORIGINAL_COMPILE_ERROR = {gd_string(message)}', ''])


# ---- constants --------------------------------------------------------------------------------------------------
def eval_const(sym: SymbolTable, name: str, seen: frozenset = frozenset()):
    """Evaluates a Delphi constant: literals, other constants, + - * and parentheses."""
    if name.lower() in seen:
        raise ValueError(f'constant {name} refers to itself')
    _, _, toks = sym.consts[name.lower()]
    pos = 0

    def atom():
        nonlocal pos
        tok = toks[pos]
        pos += 1
        if tok.is_('sym', '-'):
            return -atom()
        if tok.is_('sym', '('):
            value = expr()
            pos += 1
            return value
        if tok.kind == 'int':
            return int(tok.value)
        if tok.kind == 'float':
            return float(tok.value)
        if tok.kind == 'string':
            return tok.value
        if tok.kind == 'ident' and tok.key in sym.consts:
            return eval_const(sym, tok.value, seen | {name.lower()})
        if tok.kind == 'ident' and tok.key in sym.enum_values:
            return sym.enum_values[tok.key][1]
        if tok.kind == 'ident' and tok.key in ('true', 'false'):
            return tok.key == 'true'
        raise ValueError(f'{tok.file}:{tok.line}: cannot evaluate {tok.value!r} in constant {name}')

    def expr():
        nonlocal pos
        value = atom()
        while pos < len(toks) and toks[pos].kind == 'sym' and toks[pos].value in '+-*':
            op = toks[pos].value
            pos += 1
            rhs = atom()
            value = value + rhs if op == '+' else value - rhs if op == '-' else value * rhs
        return value

    value = expr()
    if pos != len(toks):
        raise ValueError(f'{toks[pos].file}:{toks[pos].line}: cannot evaluate constant {name}')
    return value


def gd_literal(value) -> str:
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, str):
        return gd_string(value)
    return repr(value)


def const_script(sym: SymbolTable) -> tuple[str, list[str]]:
    lines = ['# Generated by tools/transpile_scripts.py: the enum values and constants the original exposes to',
             '# scripts (ScriptManager.ExposeType / ExposeConstant). Do not edit.', 'extends RefCounted', '']
    errors = []
    for type_name in sym.exposed_types:
        enum = sym.enums.get(type_name.lower())
        if enum is None:
            continue
        lines.append(f'# {enum.name} ({enum.file})')
        lines.extend(f'const {value} = {ordinal}' for value, ordinal in enum.values)
        lines.append('')
    lines.append('# ExposeConstant')
    for name in sym.exposed_consts:
        spelling = sym.consts[name.lower()][0]
        try:
            lines.append(f'const {spelling} = {gd_literal(eval_const(sym, name))}')
        except ValueError as e:
            errors.append(str(e))
    return '\n'.join(lines) + '\n', errors


def const_header(const_text: str) -> str:
    """native/src/dws/dws_const.h: the same constants for the C++ game code (namespace C, as the scripts' `C.`)."""
    lines = ['#pragma once', '', '// Generated by tools/transpile_scripts.py: the enum values and constants the original '
             'exposes to', '// scripts (ScriptManager.ExposeType / ExposeConstant). Do not edit.', '',
             'namespace godot::C {', '']
    for line in const_text.splitlines():
        if line.startswith('# ') and not line.startswith('# Generated') and not line.startswith('# scripts'):
            lines.append('// ' + line[2:])
            continue
        m = re.match(r'const (\w+) = (.*)$', line)
        if not m:
            if line == '' and lines[-1] != '':
                lines.append('')
            continue
        name, value = m.groups()
        if re.fullmatch(r'-?\d+', value):
            lines.append(f'constexpr int {name} = {value};')
        elif value in ('true', 'false'):
            lines.append(f'constexpr bool {name} = {value};')
        elif value.startswith('"'):
            lines.append(f'inline constexpr const char *{name} = {value};')
        else:
            lines.append(f'constexpr double {name} = {value};')
    lines += ['', '} // namespace godot::C']
    return '\n'.join(lines) + '\n'


# ---- stubs ------------------------------------------------------------------------------------------------------
def declared_class_names() -> dict[str, str]:
    """class_name -> file for every hand-written (non-stub) GDScript file in src/ and every C++ class in native/src/
    (`GDCLASS(Name, Base)`; their methods count as unknown arity)."""
    found = {}
    for folder, _, files in os.walk(os.path.join(ROOT, 'native', 'src')):
        for name in files:
            if name.endswith('.h'):
                path = os.path.join(folder, name)
                with open(path, encoding='utf-8') as f:
                    for m in re.finditer(r'\bGDCLASS\((\w+),', f.read()):
                        found[m.group(1)] = path
    for folder, _, files in os.walk(os.path.join(ROOT, 'src')):
        for name in files:
            if not name.endswith('.gd'):
                continue
            path = os.path.join(folder, name)
            with open(path, encoding='utf-8') as f:
                text = f.read()
            if text.startswith(STUB_HEADER):
                continue
            for line in text.splitlines():
                if line.startswith('class_name '):
                    found[line.split()[1]] = path
    return found


def gd_param_count(params: str) -> int:
    """Number of parameters in a GDScript parameter list text (commas inside brackets do not count)."""
    depth, count, seen = 0, 0, False
    for ch in params:
        if ch in '([{':
            depth += 1
        elif ch in ')]}':
            depth -= 1
        elif ch == ',' and depth == 0:
            count += 1
            continue
        if not ch.isspace():
            seen = True
    return count + 1 if seen else 0


def gd_method_arities(path: str) -> dict[str, int]:
    """Method name -> parameter count for the top-level funcs of a hand-written GDScript file."""
    with open(path, encoding='utf-8') as f:
        text = f.read()
    return {m.group(1): gd_param_count(m.group(2))
            for m in re.finditer(r'^func (\w+)\(([^)]*)\)', text, re.M)}


def called_methods(api: dict) -> dict[str, set[str]]:
    """Declaring class -> names of its members the scripts call (a `?` owner counts for each listed class)."""
    called: dict[str, set[str]] = {}
    for owner, uses in api.items():
        for name in owner.lstrip('? ').split('/'):
            for member, use in uses:
                if use == 'call':
                    called.setdefault(name, set()).add(member)
    return called


def called_routines(decl, names: set[str]) -> dict:
    """Name -> declaration (longest overload) of the called public instance procedures/functions of decl."""
    found = {}
    for m in decl.members:
        if (m.kind == 'method' and m.routine in ('procedure', 'function') and not m.is_class
                and m.visibility in ('public', 'published') and m.name in names):
            if len(m.params) >= len(found.get(m.name, m).params):
                found[m.name] = m
    return found


# C++ classes whose GDScript subclasses extend a GDScript layer instead (docs/native.md, "GDScript subclasses of C++
# classes"): GDScript cannot override a bound C++ method, so the overridable part stays in the layer for now.
GD_BASES = {'TEntityComponent': 'TGDEntityComponent'}


def stub_scripts(sym: SymbolTable, used: set[str], called: dict[str, set[str]] | None = None) -> dict[str, str]:
    """Stub file text per class name, for the used classes and all their ancestors.

    A stub declares the Delphi constructors of its class (instance methods returning self, see docs/scripts.md),
    so calls with the class's own constructor parameters compile. GDScript overrides may only add parameters with
    defaults, so every parameter is defaulted and the count is at least the inherited method's. The body runs the
    inherited constructor, so the component still joins its entity; the class-specific part is not ported yet.
    The instance methods the scripts call (`called`) become no-ops, so real scripts run through: a function that
    returns its own class or an ancestor (the builder chains, `.FireAtGround`) returns self, others null."""
    called = called or {}
    real = declared_class_names()
    real_arities = {name: gd_method_arities(path) for name, path in real.items()}
    stub_arities: dict[str, dict[str, int]] = {}

    def arity(class_name: str, method: str) -> int | None:
        """Parameter count of `method` as class_name has it, declared there or inherited."""
        for decl in sym.ancestors(class_name):
            name = GD_BASES.get(decl.name, decl.name)
            found = real_arities.get(name, stub_arities.get(name, {})).get(method)
            if found is not None:
                return found
        return None

    def constructors(decl) -> dict[str, list[str]]:
        """Constructor name -> parameter names of its longest overload, declared in this class."""
        found: dict[str, list[str]] = {}
        for m in decl.members:
            if m.routine == 'constructor' and not m.is_class and m.visibility in ('public', 'published'):
                names = [p.name for p in m.params]
                if len(names) >= len(found.get(m.name, [])):
                    found[m.name] = names
        return found

    stubs = {}
    for name in sorted(used):
        # root first, so each stub sees the arities of its ancestors
        for decl in reversed(sym.ancestors(name)):
            if decl.name in stubs or decl.name in real:
                continue
            chain = sym.ancestors(decl.name)
            parent = chain[1].name if len(chain) > 1 else 'RefCounted'
            lines = [f'{STUB_HEADER} for {decl.name} ({decl.file}:{decl.line}).',
                     '# Phase 2 replaces it with the real class (delete this file when a real one declares the name).',
                     f'class_name {decl.name}', f'extends {GD_BASES.get(parent, parent)}', '']
            own = {}
            for ctor, names in sorted(constructors(decl).items()):
                inherited = arity(parent, ctor)
                count = max(len(names), inherited or 0)
                names = names + [f'Param{i}' for i in range(len(names), count)]
                own[ctor] = count
                call = f'super({", ".join(names[:inherited])})' if inherited is not None else 'pass'
                lines += ['', f'func {ctor}({", ".join(n + " = null" for n in names)}):', f'\t{call}',
                          '\treturn self', '']
            own_types = {d.name.lower() for d in chain}
            for method, m in sorted(called_routines(decl, called.get(decl.name, set())).items()):
                inherited = arity(parent, method)
                if method in own or (inherited is not None and (inherited >= len(m.params) or any(
                        method in real_arities.get(d.name, {}) for d in sym.ancestors(parent)))):
                    continue  # the ancestor's method takes these calls (a real one is never shadowed)
                names = [p.name for p in m.params]
                names += [f'Param{i}' for i in range(len(names), inherited or 0)]
                own[method] = len(names)
                if m.routine != 'function':
                    body = 'pass'
                else:
                    body = 'return self' if m.type.lower() in own_types else 'return null'
                lines += ['', f'func {method}({", ".join(n + " = null" for n in names)}):',
                          '\t# not ported yet: no-op', f'\t{body}', '']
            stub_arities[decl.name] = {**stub_arities.get(parent, {}), **own}
            stubs[decl.name] = '\n'.join(lines).rstrip('\n') + '\n'
    return stubs


def api_doc(sym: SymbolTable, api: dict, used_classes: set[str]) -> str:
    """docs/script-api.md: every class member the transpiled scripts use (the phase 2 work list)."""
    lines = ['# Script API used by the transpiled scripts', '',
             'Generated by `tools/transpile_scripts.py`; do not edit. The phase 2 work list: every member of an',
             'original class that some script calls (`M()`), reads (`M`) or assigns (`M :=`), under the class that',
             'declares it, with the sides that use it (C = client, S = server). A `?` owner means the receiver\'s',
             'type was not known statically; the member exists on all the listed classes with the same spelling.',
             'Delphi overloads share one GDScript method: see the declarations for their parameter lists.', '',
             f'{len(used_classes)} classes are referenced by name; {len(api)} declare used members.', '']
    for owner in sorted(api, key=lambda o: (o.startswith('?'), o.lower())):
        decl = sym.types.get(owner.lower())
        where = f' ({decl.file.replace(chr(92), "/")}:{decl.line})' if decl else ''
        lines.append(f'## {owner}{where}')
        lines.append('')
        items = []
        for (member, use), sides in sorted(api[owner].items(), key=lambda kv: (kv[0][0].lower(), kv[0][1])):
            text = member + {'call': '()', 'read': '', 'write': ' :='}[use]
            items.append(f'`{text}` {"".join(sorted(sides))}')
        lines.append(', '.join(items))
        lines.append('')
    return '\n'.join(lines)


# ---- main -------------------------------------------------------------------------------------------------------
def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true', help='transpile but write nothing')
    ap.add_argument('--only', help='only scripts whose path contains this text (case-insensitive)')
    args = ap.parse_args()
    if not os.path.isdir(SCRIPTS):
        print(f'missing {SCRIPTS}: run tools/fetch_reference.ps1 first')
        return 1

    sym = SymbolTable.scan(SOURCE)
    files = [f for f in script_files() if not args.only or args.only.lower() in f.lower()]
    errors: list[str] = []
    outputs: dict[str, str] = {}
    index: dict[str, dict[str, str]] = {side: {} for side in SIDES}
    used_classes: set[str] = set()
    api: dict[str, dict[tuple[str, str], set[str]]] = {}   # owner -> (member, use) -> sides
    for side in SIDES:
        for rel in files:
            path = out_path(rel, side)
            known = ORIGINAL_COMPILE_ERRORS.get((rel.lower(), side))
            try:
                tokens = Preprocessor(SCRIPTS, {side}).load_script(os.path.join(SCRIPTS, rel))
                emitter = Emitter(sym, rel, side)
                text = emitter.emit(parse(tokens))
                if known:
                    errors.append(f'[{side}] {rel}: listed as an original compile error but transpiles; '
                                  'remove it from ORIGINAL_COMPILE_ERRORS')
                    continue
                used_classes |= emitter.used_classes
                for owner, member, use in emitter.used_members:
                    api.setdefault(owner, {}).setdefault((member, use), set()).add(side[0])
            except (LexError, ParseError, EmitError) as e:
                if not known:
                    errors.append(f'[{side}] {e}')
                    continue
                text = error_script(rel, side, known)
            outputs[path] = text
            index[side][rel.lower().replace('/', '\\')] = res_path(path)

    const_text, const_errors = const_script(sym)
    errors.extend(const_errors)
    generated_consts = [(os.path.join(RUNTIME, 'dws_const.gd'), const_text),
                        (os.path.join(ROOT, 'native', 'src', 'dws', 'dws_const.h'), const_header(const_text))]
    for e in errors:
        print('ERROR', e)
    print(f'{len(files)} scripts x {len(SIDES)} sides: {len(outputs)} written, {len(errors)} errors; '
          f'{len(used_classes)} Delphi classes referenced')
    if errors:
        return 1
    if args.check:
        outdated = []
        for path, text in list(outputs.items()) + generated_consts:
            try:
                with open(path, encoding='utf-8', newline='') as f:
                    same = f.read() == text
            except OSError:
                same = False
            if not same:
                outdated.append(os.path.relpath(path, ROOT))
        for path in outdated[:20]:
            print('OUT OF DATE', path)
        if outdated:
            print(f'{len(outdated)} generated files are out of date: run python tools/transpile_scripts.py')
        return 1 if outdated else 0

    written: set[str] = set()
    for path, text in outputs.items():
        write(path, text, written)
    for path, text in generated_consts:
        write(path, text, written)
    stubs = stub_scripts(sym, used_classes, called_methods(api))
    for name, text in stubs.items():
        write(os.path.join(RUNTIME, 'stubs', name + '.gd'), text, written)
    index_lines = ['# Generated by tools/transpile_scripts.py: original script path (lower case, as the original',
                   '# resolves it case-insensitively) -> generated GDScript, per side. Do not edit.',
                   'extends RefCounted', '']
    for side in SIDES:
        index_lines.append(f'const {side} = {{')
        index_lines.extend(f'\t{gd_string(k)}: {gd_string(v)},' for k, v in sorted(index[side].items()))
        index_lines.append('}')
        index_lines.append('')
    write(os.path.join(OUT, 'script_index.gd'), '\n'.join(index_lines), written)
    if not args.only:
        write(API_DOC, api_doc(sym, api, used_classes), set())

    # stale outputs: generated files this run did not produce (a script or stub that no longer exists)
    stale = 0
    for folder in (OUT, os.path.join(RUNTIME, 'stubs')) if not args.only else ():
        for dirpath, _, names in os.walk(folder):
            for name in names:
                path = os.path.normcase(os.path.abspath(os.path.join(dirpath, name)))
                script = path[:-len('.uid')] if path.endswith('.gd.uid') else path
                if script.endswith('.gd') and script not in written:
                    os.remove(path)
                    stale += 1
    print(f'stubs: {len(stubs)}; stale files removed: {stale}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
