# Generated by tools/transpile_scripts.py from Scripts\Spells\White\SolarFlareSubFlare.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\White\SolarFlareSubFlare.dws:3
func Apply(Entity, League: int) -> void:
	var EffectGroup: int = 0  # 4
	EffectGroup = Entity.ReserveFreeGroup()  # 6
	Entity.Blackboard.SetValue(C.eiCooldown, [EffectGroup], 500)  # 7
	Entity.Blackboard.SetValue(C.eiWelaDamage, [EffectGroup], 25.0)  # 9
	Entity.Blackboard.SetValue(C.eiDamageType, [EffectGroup], [C.dtFlatHeal, C.dtOverheal])  # 10
	TThinkImpulseTimerCooldownComponent.new().CreateGrouped(Entity, [EffectGroup])  # 13
	TBrainWelaSelftargetComponent.new().CreateGrouped(Entity, [EffectGroup]).ThinksPassively()  # 14
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [EffectGroup], false)  # 16
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [EffectGroup]).MustHave([C.upUnit]).MustNotHave([C.upUnhealable]).ConstraintsWarhead()  # 18
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [EffectGroup])  # 23
	TWarheadSpottyHealComponent.new().CreateGrouped(Entity, [EffectGroup])  # 24
	TWelaEffectStatisticsComponent.new().CreateGrouped(Entity, [EffectGroup]).Name("FlatHeal").TriggerOnFire()  # 25
	TWelaEffectRemoveAfterUseComponent.new().CreateGrouped(Entity, [EffectGroup])  # 29
