# STUB generated by tools/transpile_scripts.py for TAutoBrainOnDealDamageComponent (GameServer\BaseConflict.EntityComponents.Server.Brains.pas:670).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TAutoBrainOnDealDamageComponent
extends TAutoBrainComponent
