# STUB generated by tools/transpile_scripts.py for TAutoBrainOnResourceComponent (GameServer\BaseConflict.EntityComponents.Server.Brains.pas:715).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TAutoBrainOnResourceComponent
extends TAutoBrainComponent


func TimesForEach():
	# not ported yet: no-op
	return self


func TriggerOn(Resource = null):
	# not ported yet: no-op
	return self
