# STUB generated by tools/transpile_scripts.py for TBrainOverwatchComponent (GameServer\BaseConflict.EntityComponents.Server.Brains.pas:258).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TBrainOverwatchComponent
extends TBrainComponent
