# STUB generated by tools/transpile_scripts.py for TBrainWelaSelftargetGroundComponent (GameServer\BaseConflict.EntityComponents.Server.Brains.pas:383).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TBrainWelaSelftargetGroundComponent
extends TBrainWelaComponent
