# STUB generated by tools/transpile_scripts.py for TBrainWelaFightComponent (GameServer\BaseConflict.EntityComponents.Server.Brains.pas:962).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TBrainWelaFightComponent
extends TBrainTargetingWelaComponent
