# STUB generated by tools/transpile_scripts.py for TCommanderIncomeLoanComponent (BaseConflict.EntityComponents.Shared.pas:553).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TCommanderIncomeLoanComponent
extends TCommanderIncomeComponent
