# STUB generated by tools/transpile_scripts.py for TCommanderComponent (BaseConflict.EntityComponents.Client.pas:199).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TCommanderComponent
extends TEntityComponent
