# STUB generated by tools/transpile_scripts.py for TDeckCardButtonComponent (BaseConflict.EntityComponents.Client.GUI.pas:79).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TDeckCardButtonComponent
extends TAbilitybuttonComponent
