# STUB generated by tools/transpile_scripts.py for TMeshEffectWithTimekeys (BaseConflict.EntityComponents.Client.Visuals.pas:525).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TMeshEffectWithTimekeys
extends TMeshEffectGeneric


func Create(Duration = null, Param1 = null):
	super(Duration, Param1)
	return self


func AddKey(TimeKey = null, Value = null):
	# not ported yet: no-op
	return self


func AddNextTimeLine():
	# not ported yet: no-op
	return self


func AddPermaKey(Value = null):
	# not ported yet: no-op
	return self
