# STUB generated by tools/transpile_scripts.py for TMeshComponent (BaseConflict.EntityComponents.Client.Visuals.pas:870).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TMeshComponent
extends TVisualizerComponent
