# STUB generated by tools/transpile_scripts.py for TMeshEffectInvisible (BaseConflict.EntityComponents.Client.Visuals.pas:741).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TMeshEffectInvisible
extends TMeshEffectGeneric


func Create(Param0 = null, Param1 = null):
	super(Param0, Param1)
	return self


func Smooth(Step = null):
	# not ported yet: no-op
	return self


func Span(Span = null):
	# not ported yet: no-op
	return self


func Speed(Speed = null):
	# not ported yet: no-op
	return self
