# STUB generated by tools/transpile_scripts.py for TMeshEffectWarp (BaseConflict.EntityComponents.Client.Visuals.pas:693).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TMeshEffectWarp
extends TMeshEffectWithTimekeys


func Create(TextureFilename = null, Duration = null):
	super(TextureFilename, Duration)
	return self


func Smooth(Step = null):
	# not ported yet: no-op
	return self
