# STUB generated by tools/transpile_scripts.py for TMeshEffectMetal (BaseConflict.EntityComponents.Client.Visuals.pas:706).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TMeshEffectMetal
extends TMeshEffectGeneric
