# STUB generated by tools/transpile_scripts.py for TModifierComponent (BaseConflict.EntityComponents.Shared.Wela.pas:32).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TModifierComponent
extends TEntityComponent


func CreateGrouped(Owner = null, ComponentGroup = null):
	super(Owner, ComponentGroup)
	return self
