# STUB generated by tools/transpile_scripts.py for TModifierResourceComponent (BaseConflict.EntityComponents.Shared.Wela.pas:102).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TModifierResourceComponent
extends TModifierComponent
