# STUB generated by tools/transpile_scripts.py for TOrienterTargetComponent (BaseConflict.EntityComponents.Client.Visuals.pas:138).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TOrienterTargetComponent
extends TGDEntityComponent


func FrontFromPivot():
	# not ported yet: no-op
	return self


func FrontGroup(Group = null):
	# not ported yet: no-op
	return self


func FrontWithY():
	# not ported yet: no-op
	return self


func KeepLastFront():
	# not ported yet: no-op
	return self


func TargetGroup(Group = null):
	# not ported yet: no-op
	return self
