# STUB generated by tools/transpile_scripts.py for TOrienterSmoothRotateComponent (BaseConflict.EntityComponents.Client.Visuals.pas:178).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TOrienterSmoothRotateComponent
extends TEntityComponent
