# STUB generated by tools/transpile_scripts.py for TResourceDisplayHealthComponent (BaseConflict.EntityComponents.Client.GUI.pas:316).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TResourceDisplayHealthComponent
extends TResourceDisplayProgressBarComponent


func Create(Owner = null):
	super(Owner)
	return self
