# STUB generated by tools/transpile_scripts.py for TResourceDisplayBarComponent (BaseConflict.EntityComponents.Client.GUI.pas:274).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TResourceDisplayBarComponent
extends TResourceDisplayComponent


func GradientBottom(GradientBottom = null):
	# not ported yet: no-op
	return self


func GradientTop(GradientTop = null):
	# not ported yet: no-op
	return self
