# STUB generated by tools/transpile_scripts.py for TResourceDisplayComponent (BaseConflict.EntityComponents.Client.GUI.pas:244).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TResourceDisplayComponent
extends TEntityDisplayComponent
