# STUB generated by tools/transpile_scripts.py for TResourceDisplayProgressBarComponent (BaseConflict.EntityComponents.Client.GUI.pas:299).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TResourceDisplayProgressBarComponent
extends TResourceDisplayBarComponent
