# STUB generated by tools/transpile_scripts.py for TSpelltargetVisualizerLineBetweenTargetsComponent (BaseConflict.EntityComponents.Client.GUI.pas:631).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TSpelltargetVisualizerLineBetweenTargetsComponent
extends TSpelltargetVisualizerComponent
