# STUB generated by tools/transpile_scripts.py for TSpelltargetVisualizerLineBetweenTargetsComponent (BaseConflict.EntityComponents.Client.GUI.pas:631).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TSpelltargetVisualizerLineBetweenTargetsComponent
extends TSpelltargetVisualizerComponent


func CreateGrouped(Owner = null, Group = null):
	super(Owner, Group)
	return self


func Texture(TexturePath = null):
	# not ported yet: no-op
	return self


func Width(Width = null):
	# not ported yet: no-op
	return self
