# STUB generated by tools/transpile_scripts.py for TTextureRangeIndicatorComponent (BaseConflict.EntityComponents.Client.GUI.pas:406).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TTextureRangeIndicatorComponent
extends TRangeIndicatorComponent
