# STUB generated by tools/transpile_scripts.py for TTooltipUnitAbilityComponent (BaseConflict.EntityComponents.Client.GUI.pas:100).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TTooltipUnitAbilityComponent
extends TEntityComponent


func Create(Owner = null, AbilityName = null):
	super(Owner)
	return self


func CreateGrouped(Owner = null, Group = null, AbilityName = null):
	super(Owner, Group)
	return self


func IsCardDescription():
	# not ported yet: no-op
	return self


func Keyword(Keyword = null):
	# not ported yet: no-op
	return self


func PassInteger(Key = null, Value = null, SpanClass = null):
	# not ported yet: no-op
	return self


func PassPercentage(Key = null, Value = null, SpanClass = null):
	# not ported yet: no-op
	return self


func PassSingle(Key = null, IntegralPart = null, FractionalPart = null, SpanClass = null):
	# not ported yet: no-op
	return self


func PassSingleAsInteger(Key = null, Value = null, SpanClass = null):
	# not ported yet: no-op
	return self


func PassString(Key = null, Value = null, SpanClass = null):
	# not ported yet: no-op
	return self
