# STUB generated by tools/transpile_scripts.py for TTutorialDirectorAction (BaseConflict.EntityComponents.Client.pas:620).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TTutorialDirectorAction
extends TObject
