# STUB generated by tools/transpile_scripts.py for TTutorialDirectorActionArrowHighlight (BaseConflict.EntityComponents.Client.pas:718).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TTutorialDirectorActionArrowHighlight
extends TTutorialDirectorAction


func Create():
	super()
	return self
