# STUB generated by tools/transpile_scripts.py for TVisualModificatorSizeComponent (BaseConflict.EntityComponents.Client.Visuals.pas:227).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TVisualModificatorSizeComponent
extends TEntityComponent


func Duration(Duration = null):
	# not ported yet: no-op
	return self


func Keypoints(Sizes = null):
	# not ported yet: no-op
	return self


func KeypointsY(Sizes = null):
	# not ported yet: no-op
	return self


func SetTargetSize(Size = null):
	# not ported yet: no-op
	return self


func TimeKeys(Times = null):
	# not ported yet: no-op
	return self
