# STUB generated by tools/transpile_scripts.py for TWarheadSpottyWelaStopComponent (GameServer\BaseConflict.EntityComponents.Server.Warheads.pas:210).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TWarheadSpottyWelaStopComponent
extends TWarheadSpottyComponent
