# STUB generated by tools/transpile_scripts.py for TWarheadSplashHealComponent (GameServer\BaseConflict.EntityComponents.Server.Warheads.pas:276).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TWarheadSplashHealComponent
extends TWarheadSplashHealthComponent


func CreateGrouped(Owner = null, Group = null):
	super(Owner, Group)
	return self
