# STUB generated by tools/transpile_scripts.py for TWarheadSpottyResourceComponent (GameServer\BaseConflict.EntityComponents.Server.Warheads.pas:159).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TWarheadSpottyResourceComponent
extends TWarheadSpottyComponent


func CreateGrouped(Owner = null, Group = null):
	super(Owner, Group)
	return self


func AmountIsPercentage():
	# not ported yet: no-op
	return self


func ChangesMax():
	# not ported yet: no-op
	return self


func DontFillCap():
	# not ported yet: no-op
	return self


func ResetResource():
	# not ported yet: no-op
	return self


func SearchForWelaBeacon(Properties = null):
	# not ported yet: no-op
	return self


func SetFactor(Factor = null):
	# not ported yet: no-op
	return self


func SetResourceSource(Eventname = null):
	# not ported yet: no-op
	return self


func SetResourceType(ResType = null):
	# not ported yet: no-op
	return self


func SetsResourceToValue():
	# not ported yet: no-op
	return self


func TargetGroup(Group = null):
	# not ported yet: no-op
	return self
