# STUB generated by tools/transpile_scripts.py for TWarheadSpottyResourceComponent (GameServer\BaseConflict.EntityComponents.Server.Warheads.pas:159).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TWarheadSpottyResourceComponent
extends TWarheadSpottyComponent


func CreateGrouped(Owner = null, Group = null):
	super(Owner, Group)
	return self
