# STUB generated by tools/transpile_scripts.py for TWelaEffectPayCostComponent (GameServer\BaseConflict.EntityComponents.Server.Welas.pas:306).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TWelaEffectPayCostComponent
extends TWelaEffectComponent


func CreateGrouped(Owner = null, Group = null):
	super(Owner, Group)
	return self
