# STUB generated by tools/transpile_scripts.py for TWelaTargetConstraintComponent (BaseConflict.EntityComponents.Shared.Wela.pas:222).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TWelaTargetConstraintComponent
extends TEntityComponent


func ConstraintsWarhead():
	# not ported yet: no-op
	return self
