# STUB generated by tools/transpile_scripts.py for TWelaTargetingComponent (GameServer\BaseConflict.EntityComponents.Server.Welas.pas:40).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TWelaTargetingComponent
extends TEntityComponent


func CreateGrouped(Owner = null, Group = null):
	super(Owner, Group)
	return self


func MaxNewTargetCount(Count = null):
	# not ported yet: no-op
	return self


func PicksRandomTargets():
	# not ported yet: no-op
	return self


func PicksRandomTargetsWithRepetition():
	# not ported yet: no-op
	return self


func SetTargetTeamConstraint(Value = null):
	# not ported yet: no-op
	return self


func SetTargetTeamConstraintPriority(Value = null):
	# not ported yet: no-op
	return self


func SetValidateGroup(Group = null):
	# not ported yet: no-op
	return self
