# STUB generated by tools/transpile_scripts.py for TWelaTargetConstraintBlacklistComponent (BaseConflict.EntityComponents.Shared.Wela.pas:265).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TWelaTargetConstraintBlacklistComponent
extends TWelaTargetConstraintComponent
