# STUB generated by tools/transpile_scripts.py for TWelaEffectResetCooldownComponent (GameServer\BaseConflict.EntityComponents.Server.Welas.pas:522).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TWelaEffectResetCooldownComponent
extends TWelaEffectComponent
