# STUB generated by tools/transpile_scripts.py for TWelaTargetConstraintCompareUnitPropertyComponent (BaseConflict.EntityComponents.Shared.Wela.pas:469).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TWelaTargetConstraintCompareUnitPropertyComponent
extends TWelaTargetConstraintUnitPropertyComponent


func BothMustHaveAny(Properties = null):
	# not ported yet: no-op
	return self
