# STUB generated by tools/transpile_scripts.py for TWelaTriggerCheckTakeDamageComponent (BaseConflict.EntityComponents.Shared.Wela.pas:527).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TWelaTriggerCheckTakeDamageComponent
extends TEntityComponent
