# STUB generated by tools/transpile_scripts.py for TWelaReadyEventCompareComponent (BaseConflict.EntityComponents.Shared.Wela.pas:747).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TWelaReadyEventCompareComponent
extends TWelaReadyComponent


func CreateGrouped(Owner = null, Group = null):
	super(Owner, Group)
	return self


func ComparedEvent(EventIdentifier = null):
	# not ported yet: no-op
	return self


func ReferenceValue(ReferenceValue = null):
	# not ported yet: no-op
	return self


func SetComparator(Comparator = null):
	# not ported yet: no-op
	return self
