# STUB generated by tools/transpile_scripts.py for TWelaTargetConstraintAlliesComponent (BaseConflict.EntityComponents.Shared.Wela.pas:415).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TWelaTargetConstraintAlliesComponent
extends TWelaTargetConstraintTeamComponent
