# STUB generated by tools/transpile_scripts.py for TWelaEffectOnlyByChanceComponent (GameServer\BaseConflict.EntityComponents.Server.Welas.pas:280).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TWelaEffectOnlyByChanceComponent
extends TEntityComponent
