# STUB generated by tools/transpile_scripts.py for TWelaTargetingRadialComponent (GameServer\BaseConflict.EntityComponents.Server.Welas.pas:116).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TWelaTargetingRadialComponent
extends TWelaTargetingComponent


func CreateGrouped(Owner = null, Group = null):
	super(Owner, Group)
	return self


func Cone(DirectionX = null, DirectionZ = null, Angle = null):
	# not ported yet: no-op
	return self


func IgnoreOwnCollisionradius():
	# not ported yet: no-op
	return self


func PrioritizeMiddleDistant():
	# not ported yet: no-op
	return self


func PrioritizeMostDistant():
	# not ported yet: no-op
	return self


func RangeFromEvent(EventIdentifier = null):
	# not ported yet: no-op
	return self
