# STUB generated by tools/transpile_scripts.py for TWelaTargetConstraintTeamIDComponent (BaseConflict.EntityComponents.Shared.Wela.pas:395).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TWelaTargetConstraintTeamIDComponent
extends TWelaTargetConstraintComponent
