# STUB generated by tools/transpile_scripts.py for TWelaEffectActivationAbilityComponent (GameServer\BaseConflict.EntityComponents.Server.Welas.pas:353).
# Phase 2 replaces it with the real class (delete this file when a real one declares the name).
class_name TWelaEffectActivationAbilityComponent
extends TWelaEffectComponent


func CreateGrouped(Owner = null, Group = null):
	super(Owner, Group)
	return self


func CheckNotFull(ResType = null):
	# not ported yet: no-op
	return self


func OnlyAfterGameStart():
	# not ported yet: no-op
	return self


func SetActivationGroup(ActivationGroup = null):
	# not ported yet: no-op
	return self


func SetCheckGroup(CheckGroup = null):
	# not ported yet: no-op
	return self


func SetsActive():
	# not ported yet: no-op
	return self


func TriggerOnReachResourceCap(ResType = null):
	# not ported yet: no-op
	return self
