# Generated by tools/transpile_scripts.py from Scripts\Units\Neutral\Lanetower.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\BuildingTemplate.dws:3
func InitBuildingData(Entity, LimitedLifeTime: bool = false) -> void:
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 12.0)  # 5
	if LimitedLifeTime:  # 8
		Entity.Blackboard.SetValue(C.eiCooldown, [C.GROUP_BUILDING_LIFETIME], 90000)  # 9
	Entity.Blackboard.SetValue(C.eiWelaRange, [C.GROUP_SOUL], 12.0)  # 11
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 14
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapBuildingIcon.png")  # 15
	if LimitedLifeTime:  # 17
		TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], "TimedLifeBuilding").PassInteger("duration", 90)  # 18

# HelperScripts\BuildingTemplate.dws:23
func InitBuildingMeta(Entity) -> void:
	pass

# HelperScripts\BuildingTemplate.dws:32
func InitBaseBuildingEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 34
	TPathfindingComponent.new().Create(Entity)  # 51

# HelperScripts\BuildingTemplate.dws:57
func InitBuildingEntity(Entity, LimitedLifeTime: bool = false) -> void:
	InitBaseBuildingEntity(Entity)  # 59
	if LimitedLifeTime:  # 71
		TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], false)  # 72
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 75
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 76
	TShowOnMinimapComponent.new().Create(Entity)  # 78
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/env/building/shared/hit").TriggerOnLoseHealth()  # 79
	if LimitedLifeTime:  # 82
		TIndicatorCooldownCircleComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME]).SetTexture(C.PATH_GRAPHICS_EFFECTS_TEXTURES + "ProgressCircle.tga").SetRadius(1.5).ScaleWith(C.eiCollisionRadius).SetThickness(0.1).SetLinearBlend().Color(1627389951).Invert()  # 84

# Units\Neutral\Lanetower.ets:3
func CreateData(Entity) -> void:
	InitBuildingData(Entity)  # 5
	Entity.CollisionRadius = 1.0  # 6
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upFlying, C.upGround, C.upMonumental, C.upBuilding, C.upBase, C.upRanged, C.upLanetower])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atFortified)  # 10
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [7], C.reWelaCharge, 0)  # 12
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [7], C.reWelaCharge, 20)  # 13
	if (L.Game().IsDuo() and L.Game().IsPvP()) and L.Game().IsOneLane():  # 17
		Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reWelaCharge, L.i([8, 18, 18, 23, 23], Entity.CardLeague()))  # 19
		Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reWelaCharge, L.i([4, 9, 9, 12, 12], Entity.CardLeague()))  # 20
		Entity.Blackboard.SetValue(C.eiWelaTargetCount, [1], 2)  # 21
		Entity.Blackboard.SetValue(C.eiCooldown, [1], 1250)  # 22
	else:
		Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reWelaCharge, L.i([6, 14, 14, 18, 18], Entity.CardLeague()))  # 28
		Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reWelaCharge, L.i([3, 7, 7, 9, 9], Entity.CardLeague()))  # 29
		Entity.Blackboard.SetValue(C.eiWelaTargetCount, [1], 1)  # 30
		Entity.Blackboard.SetValue(C.eiCooldown, [1], 1000)  # 31
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [1], C.reWelaCharge, 1)  # 35
	Entity.Blackboard.SetValue(C.eiWelaRange, [1], 15.0)  # 36
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtTrue, C.dtRanged])  # 38
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], L.f([100.0, 100.0, 100.0, 100.0, 100.0], Entity.CardLeague()))  # 39
	Entity.Blackboard.SetValue(C.eiWelaRange, [3], 30.0)  # 42
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [2], "Units\\Neutral\\LaneNode")  # 45
	Entity.Blackboard.SetIndexedValue(C.eiWelaUnitPattern, [2], 1, "Units\\Neutral\\LaneNode_Red")  # 46
	Entity.Blackboard.SetIndexedValue(C.eiWelaUnitPattern, [2], 2, "Units\\Neutral\\LaneNode_Blue")  # 47
	Entity.Blackboard.SetValue(C.eiWelaDamage, [5], 1.0)  # 50
	Entity.Blackboard.SetValue(C.eiCooldown, [5], L.i([10000, 9000, 8000, 6000, 6000], Entity.CardLeague()))  # 51
	Entity.Blackboard.SetValue(C.eiWelaDamage, [6], 1.0)  # 55
	Entity.Blackboard.SetValue(C.eiCooldown, [6], 500)  # 56
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [7], C.reWelaCharge, 20)  # 59
	Entity.Blackboard.SetValue(C.eiWelaDamage, [7], 100.0)  # 60
	Entity.Blackboard.SetValue(C.eiDamageType, [7], [C.dtTrue, C.dtRanged])  # 61
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [7], "Projectiles\\Neutral\\LaneTowerAntiNexusProjectile")  # 62
	Entity.Blackboard.SetValue(C.eiWelaDamage, [8], 0.0)  # 65
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "minimap_icon_tower_%d.png")  # 68
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIconSize, 2.5)  # 69
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHealthbarOffset, 1.2)  # 70
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [], "Monumental")  # 72
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [5], "EnergyRegenerationLanetower").PassInteger("charge_amount", 1, "generic").PassInteger("cooldown_league_1", 10).PassInteger("cooldown_league_2", 9).PassInteger("cooldown_league_3", 8).PassInteger("cooldown_league_4", 6).PassInteger("cooldown_league_5", 6)  # 73
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "Ammo_Basebuilding").PassInteger("charge_cost", 1, "generic")  # 80
	if (L.Game().IsDuo() and L.Game().IsPvP()) and L.Game().IsOneLane():  # 83
		TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "MultiShot2").PassInteger("target_count", 2)  # 84
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "Splash_Lanetower1").PassInteger("damage_amount", L.i([25, 25, 30, 30, 30], Entity.CardLeague()), "damage")  # 87
	if L.Game().HasShowdown():  # 90
		TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [7], "NexusBuster1").PassInteger("damage_amount", 100, "damage").PassInteger("cooldown", 10).PassInteger("activation_cooldown", L.i([6, 9, 9, 12, 12], Entity.CardLeague()))  # 91

# Units\Neutral\Lanetower.ets:98
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 100
	InitBuildingMeta(Entity)  # 101
	TPointLightComponent.new().CreateGrouped(Entity, [2], 2852126720, 0.0).SetLightShape(Vector3(2.5, 2, 0)).BindToSubPosition(C.BIND_ZONE_CENTER)  # 104
	TMeshComponent.new().CreateGrouped(Entity, [0], "Units\\Neutral\\Lanetower\\LanetowerBase.xml").CreateNewAnimation(C.ANIMATION_STAND, 0, 0).BindTextureToTeam(C.mtGlow, "LanetowerGlow.tga", 1).BindTextureToTeam(C.mtGlow, "LanetowerGlow2.tga", 2).BindZoneToBone(C.BIND_ZONE_HIT_ZONE_AIR, "crystal_hit_zone").BoneOffset(C.BIND_ZONE_HIT_ZONE_AIR, 0.0, 3.0, 0.0).BoneOffset(C.BIND_ZONE_TOP, 0.0, 2.5, 0.0)  # 108
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [0.12], [0, 1, 2, 3, 6, 7])  # 116

# Units\Neutral\Lanetower.ets:120
func CreateEntity(Entity) -> void:
	var TowerCaptureEventGroup: int = 0  # 121
	CreateMeta(Entity)  # 123
	InitBuildingEntity(Entity)  # 124
	TowerCaptureEventGroup = Entity.ReserveFreeGroup()  # 125
	TDynamicZoneRadialEmitterComponent.new().CreateGrouped(Entity, [3]).SetZone([C.dzDrop])  # 204
	TResourceDisplayIntegerProgressBarComponent.new().Create(Entity).ShowResource(C.reWelaCharge).SizeY(8.0)  # 208
	TStateDisplayStackComponent.new().Create(Entity)  # 212
	TStateDisplayComponent.new().Create(Entity).Texture("HUD/Unitbars/icon_out_of_ammo.png").CheckWelaIsReadyInGroup([11]).ReverseWelaIsReadyCheck()  # 213
	TWelaReadyCostComponent.new().CreateGrouped(Entity, [11]).SetPayingGroupForType(C.reWelaCharge, []).ValueGroup([1])  # 217
	TStateDisplayComponent.new().Create(Entity).Texture("HUD/Unitbars/icon_not_reloading.png").CheckWelaIsReadyInGroup([12])  # 221
	TWelaReadyEnemiesNearbyComponent.new().CreateGrouped(Entity, [12]).ValueGroup([1]).CheckGroup([13])  # 224
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [13]).MustHaveAny([C.upUnit, C.upBuilding]).MustNotHave([C.upInvisible, C.upBanished])  # 227
	TTextureRangeIndicatorComponent.new().CreateGrouped(Entity, [3]).HideInCaptureMode().DrawOnShowSpawnZone([C.dzDrop]).DrawCircle(0.5).SetTexture(C.PATH_GRAPHICS_EFFECTS_TEXTURES + "RangeLine.tga").ShowTeamColor().ShowWeaponRange().IsPermanent()  # 231
	TGameIntensityComponent.new().Create(Entity)  # 240
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/env/building/lane_tower/death").TriggerOnDie()  # 242
	TParticleEffectComponent.new().CreateGrouped(Entity, [1], "\\Neutral\\tower_fire.pfx", 0.12).ActivateOnFire().BindToSubPositionGroup(C.BIND_ZONE_WEAPON_MUZZLE, [2]).FixedOrientationDefault()  # 245
	TSoundComponent.new().CreateGrouped(Entity, [1], "event:/env/building/lane_tower/attack_fire").TriggerOnFire()  # 250
	TResourceDisplayProgressBarComponent.new().CreateGrouped(Entity, [7]).GradientTop(4292796126).GradientBottom(4282400832).ShowResource(C.reWelaCharge).HideIfEmpty()  # 253
	if L.Game().HasShowdown():  # 259
		TSoundComponent.new().CreateGrouped(Entity, [7], "event:/env/building/lane_tower/nexus_buster_fire").TriggerOnFire()  # 261
		TParticleEffectComponent.new().CreateGrouped(Entity, [6], "\\Neutral\\tower_nexus_shot_charge.pfx", 0.16).ActivateOnFire().BindToSubPositionGroup(C.BIND_ZONE_WEAPON_MUZZLE, [2])  # 264
		TSoundComponent.new().CreateGrouped(Entity, [1, 6], "event:/env/building/lane_tower/nexus_buster_charge_loop").IsLoop().TriggerOnFire().StopGroup([1]).StopOnFire().StopOnFree()  # 268
		TParticleEffectComponent.new().CreateGrouped(Entity, [7], "\\Neutral\\tower_nexus_shot_fire.pfx", 0.10).ActivateOnFire().BindToSubPositionGroup(C.BIND_ZONE_WEAPON_MUZZLE, [2]).FixedOrientationDefault()  # 275
