# Generated by tools/transpile_scripts.py from Scripts\Units\Neutral\LanetowerLevel3.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")

var Game = null  # Units\Neutral\LanetowerLevel3.ets:3
var InheritsFrom: String = "Units\\Neutral\\Lanetower.ets"  # Units\Neutral\LanetowerLevel3.ets:4

# Units\Neutral\LanetowerLevel3.ets:6
func CreateData(Entity) -> void:
	if (Game.IsDuo() and Game.IsPvP()) and Game.IsOneLane():  # 10
		Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 2.0 * L.f([1200.0, 1400.0, 1600.0, 1600.0, 1600.0], Entity.CardLeague()))  # 12
		Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 2.0 * L.f([1200.0, 1400.0, 1600.0, 1600.0, 1600.0], Entity.CardLeague()))  # 13
	else:
		Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, L.f([1200.0, 1400.0, 1600.0, 1600.0, 1600.0], Entity.CardLeague()))  # 19
		Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, L.f([1200.0, 1400.0, 1600.0, 1600.0, 1600.0], Entity.CardLeague()))  # 20
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [0, 1], "Projectiles\\Neutral\\LanetowerLevel3Projectile")  # 23
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHealthbarOffset, 1.9)  # 26

# Units\Neutral\LanetowerLevel3.ets:30
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 32
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(0, 0, 0), Vector3(0, 4, 0), 1.4)  # 35
	TMeshComponent.new().CreateGrouped(Entity, [2], "Units\\Neutral\\Lanetower\\LanetowerCrystal.xml").CreateNewAnimation(C.ANIMATION_STAND, 0, 201).BindTextureToTeam(C.mtDiffuse, "LanetowerDiffuse.tga", 1).BindTextureToTeam(C.mtDiffuse, "LanetowerDiffuse2.tga", 2).BindTextureToTeam(C.mtGlow, "LanetowerGlow.tga", 1).BindTextureToTeam(C.mtGlow, "LanetowerGlow2.tga", 2)  # 37
	TMeshEffectComponent.new().CreateGrouped(Entity, [2]).SetEffect(TMeshEffectMatcap.new().Create().SetTexture(C.PATH_GRAPHICS_EFFECTS_TEXTURES + "MatcapCrystal%d.png"))  # 44
	TMeshComponent.new().CreateGrouped(Entity, [0], "Units\\Neutral\\Lanetower\\LanetowerCrystalRunes.xml").CreateNewAnimation(C.ANIMATION_STAND, 0, 301).BindTextureToTeam(C.mtDiffuse, "LanetowerDiffuse.tga", 1).BindTextureToTeam(C.mtDiffuse, "LanetowerDiffuse2.tga", 2).BindTextureToTeam(C.mtGlow, "LanetowerGlow.tga", 1).BindTextureToTeam(C.mtGlow, "LanetowerGlow2.tga", 2)  # 50
	TMeshComponent.new().CreateGrouped(Entity, [3], "Units\\Neutral\\Lanetower\\LanetowerBaseUpgrade.xml").CreateNewAnimation(C.ANIMATION_STAND, 0, 0).BindTextureToTeam(C.mtGlow, "LanetowerGlow.tga", 1).BindTextureToTeam(C.mtGlow, "LanetowerGlow2.tga", 2)  # 57
	TMeshEffectComponent.new().CreateGrouped(Entity, [0, 1, 2, 3, 4]).SetEffect(TMeshEffectSpawn.new().Create().OverrideColor(4283455832).OverrideColorIdentity(C.ecWhite))  # 62

# Units\Neutral\LanetowerLevel3.ets:71
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 73
