# Generated by tools/transpile_scripts.py from Scripts\Units\Neutral\NexusLevel1.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")

var Game = null  # Units\Neutral\NexusLevel1.ets:3
var InheritsFrom: String = "Units\\Neutral\\Nexus.ets"  # Units\Neutral\NexusLevel1.ets:4

# Units\Neutral\NexusLevel1.ets:6
func CreateData(Entity) -> void:
	if Game.IsDuo() and Game.IsPvP():  # 10
		Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 2.0 * L.f([2500.0, 3250.0, 3750.0, 3750.0, 3750.0], Entity.CardLeague()))  # 12
		Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 2.0 * L.f([2500.0, 3250.0, 3750.0, 3750.0, 3750.0], Entity.CardLeague()))  # 13
	else:
		Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, L.f([2500.0, 3250.0, 3750.0, 3750.0, 3750.0], Entity.CardLeague()))  # 19
		Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, L.f([2500.0, 3250.0, 3750.0, 3750.0, 3750.0], Entity.CardLeague()))  # 20
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [1], "Projectiles\\Neutral\\NexusLevel1Projectile")  # 23
	Entity.Blackboard.SetValue(C.eiCooldown, [4], (6 * 60) * 1000)  # 26
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [4], "Units\\Neutral\\NexusLevel2")  # 27
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [4], "NexusUpgrade")  # 30

# Units\Neutral\NexusLevel1.ets:34
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 36
	TMeshComponent.new().CreateGrouped(Entity, [0], "Units\\Neutral\\Nexus\\Nexus.xml").CreateNewAnimation(C.ANIMATION_STAND, 0, 0).BindZoneToBone(C.BIND_ZONE_HIT_ZONE, "crystal_low").BoneOffset(C.BIND_ZONE_HIT_ZONE, 0.0, 2.5, 0.0).BindZoneToBone(C.BIND_ZONE_HIT_ZONE_AIR, "crystal_high").BoneOffset(C.BIND_ZONE_HIT_ZONE_AIR, 0.0, 4.0, 0.0).BoneOffset(C.BIND_ZONE_TOP, 0.0, 4.5, 0.0)  # 38

# Units\Neutral\NexusLevel1.ets:48
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 50
