# Generated by tools/transpile_scripts.py from Scripts\Units\Neutral\Nexus.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\BuildingTemplate.dws:3
func InitBuildingData(Entity, LimitedLifeTime: bool = false) -> void:
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 12.0)  # 5
	if LimitedLifeTime:  # 8
		Entity.Blackboard.SetValue(C.eiCooldown, [C.GROUP_BUILDING_LIFETIME], 90000)  # 9
	Entity.Blackboard.SetValue(C.eiWelaRange, [C.GROUP_SOUL], 12.0)  # 11
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 14
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapBuildingIcon.png")  # 15
	if LimitedLifeTime:  # 17
		TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], "TimedLifeBuilding").PassInteger("duration", 90)  # 18

# HelperScripts\BuildingTemplate.dws:23
func InitBuildingMeta(Entity) -> void:
	pass

# HelperScripts\BuildingTemplate.dws:32
func InitBaseBuildingEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 34
	TPathfindingComponent.new().Create(Entity)  # 51

# HelperScripts\BuildingTemplate.dws:57
func InitBuildingEntity(Entity, LimitedLifeTime: bool = false) -> void:
	InitBaseBuildingEntity(Entity)  # 59
	if LimitedLifeTime:  # 71
		TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], false)  # 72
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 75
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 76
	TShowOnMinimapComponent.new().Create(Entity)  # 78
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/env/building/shared/hit").TriggerOnLoseHealth()  # 79
	if LimitedLifeTime:  # 82
		TIndicatorCooldownCircleComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME]).SetTexture(C.PATH_GRAPHICS_EFFECTS_TEXTURES + "ProgressCircle.tga").SetRadius(1.5).ScaleWith(C.eiCollisionRadius).SetThickness(0.1).SetLinearBlend().Color(1627389951).Invert()  # 84

# Units\Neutral\Nexus.ets:3
func CreateData(Entity) -> void:
	InitBuildingData(Entity)  # 5
	Entity.CollisionRadius = 3.5  # 6
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, false)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upFlying, C.upGround, C.upMonumental, C.upBuilding, C.upRanged, C.upBase, C.upNexus, C.upSpellImmune])  # 9
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atFortified)  # 10
	if (L.Game().IsDuo() and L.Game().IsPvP()) and L.Game().IsOneLane():  # 14
		Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reWelaCharge, L.i([10, 20, 20, 25, 25], Entity.CardLeague()))  # 16
		Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reWelaCharge, L.i([10, 20, 20, 25, 25], Entity.CardLeague()))  # 17
		Entity.Blackboard.SetValue(C.eiCooldown, [1], 1250)  # 18
		Entity.Blackboard.SetValue(C.eiWelaTargetCount, [1], 2)  # 19
	else:
		Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reWelaCharge, L.i([8, 16, 16, 20, 20], Entity.CardLeague()))  # 25
		Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reWelaCharge, L.i([8, 16, 16, 20, 20], Entity.CardLeague()))  # 26
		Entity.Blackboard.SetValue(C.eiCooldown, [1], 1000)  # 27
		Entity.Blackboard.SetValue(C.eiWelaTargetCount, [1], 1)  # 28
	Entity.Blackboard.SetIndexedValue(C.eiResourceCost, [1], C.reWelaCharge, 1)  # 32
	Entity.Blackboard.SetValue(C.eiWelaRange, [1], 15.0)  # 33
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtTrue, C.dtRanged])  # 35
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], L.f([110.0, 110.0, 120.0, 120.0, 120.0], Entity.CardLeague()))  # 36
	Entity.Blackboard.SetValue(C.eiWelaRange, [3], 31.5)  # 39
	Entity.Blackboard.SetValue(C.eiWelaDamage, [6], 1.0)  # 42
	Entity.Blackboard.SetValue(C.eiCooldown, [6], L.i([10000, 9000, 8000, 6000, 6000], Entity.CardLeague()))  # 43
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "minimap_icon_nexus_%d.png")  # 46
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIconSize, 5.0)  # 47
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHealthbarOffset, 10.0)  # 48
	TTooltipUnitAbilityComponent.new().Create(Entity, "PrimaryTarget")  # 50
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [], "Monumental")  # 51
	TTooltipUnitAbilityComponent.new().Create(Entity, "SpellImmune")  # 52
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [6], "EnergyRegenerationLanetower").PassInteger("charge_amount", 1, "generic").PassInteger("cooldown_league_1", 10).PassInteger("cooldown_league_2", 9).PassInteger("cooldown_league_3", 8).PassInteger("cooldown_league_4", 6).PassInteger("cooldown_league_5", 6)  # 53
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "Ammo_Basebuilding").PassInteger("charge_cost", 1, "generic")  # 60
	if (L.Game().IsDuo() and L.Game().IsPvP()) and L.Game().IsOneLane():  # 63
		TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "MultiShot2").PassInteger("target_count", 2)  # 64
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "Splash_Nexus1").PassInteger("damage_amount", L.i([30, 30, 35, 35, 35], Entity.CardLeague()), "damage")  # 67

# Units\Neutral\Nexus.ets:72
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 74
	InitBuildingMeta(Entity)  # 75
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(0, 0, 0), Vector3(0, 0.1, 0), 3.5)  # 78
	TAnimationComponent.new().CreateGrouped(Entity, [0])  # 80
	TMeshComponent.new().CreateGrouped(Entity, [2], "Units\\Neutral\\Nexus\\NexusCrystal.xml").CreateNewAnimation(C.ANIMATION_STAND, 0, 200).BindTextureToTeam(C.mtDiffuse, "NexusDiffuse.tga", 1).BindTextureToTeam(C.mtDiffuse, "NexusDiffuse2.tga", 2).BindTextureToTeam(C.mtGlow, "NexusGlow.tga", 1).BindTextureToTeam(C.mtGlow, "NexusGlow2.tga", 2)  # 82
	TPointLightComponent.new().CreateGrouped(Entity, [2], 2315255808, 0.0).SetLightShape(Vector3(5, 2, 5)).SetModelOffset(Vector3(0, -20, 0))  # 89
	TParticleEffectComponent.new().CreateGrouped(Entity, [2], "\\Neutral\\NexusDie%d.pfx", 1.0).ActivateOnLose().IgnoreModelSize().FixedOrientationDefault().SetModelOffset(Vector3(0, 35, 0))  # 93
	TMeshEffectComponent.new().CreateGrouped(Entity, [2]).ActivateOnLose().SetEffect(TMeshEffectGlow.new().Create(10000).AddKey(0, 0.0).AddKey(2800, 0.1).AddKey(3100, 1.0).AddKey(3201, 0.0).AddKey(10000, 0.0))  # 99
	TMeshEffectComponent.new().CreateGrouped(Entity, [2]).SetEffect(TMeshEffectMatcap.new().Create().SetTexture(C.PATH_GRAPHICS_EFFECTS_TEXTURES + "MatcapCrystal%d.png"))  # 110
	TAnimatorComponent.new().CreateGrouped(Entity, [2, 3]).Duration(30000).ActivateOnLose().HideAfter(3150)  # 116
	TCameraShakerComponent.new().Create(Entity).RotationShaker(0.005, 0.005, 0.02).Duration(1000).Waves(24).ActivateOnLose().Delay(3200)  # 121
	TCameraShakerComponent.new().Create(Entity).VectorShaker(0.0, -1.0, 0.0).Strength(0.3).Duration(1000).Waves(16).ActivateOnLose().Delay(3200)  # 128
	TCameraShakerComponent.new().Create(Entity).RotationShaker(0.001, 0.001, 0.005).Duration(3200).Waves(24).Invert().ActivateOnLose()  # 136
	TCameraShakerComponent.new().Create(Entity).VectorShaker(0.0, -1.0, 0.0).Strength(0.1).Duration(3200).Waves(16).Invert().ActivateOnLose()  # 143
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/env/building/nexus/destroy").TriggerOnLose()  # 151
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [0.12], [0, 1, 2, 3, 6])  # 154

# Units\Neutral\Nexus.ets:158
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 160
	InitBuildingEntity(Entity)  # 161
	TDynamicZoneRadialEmitterComponent.new().CreateGrouped(Entity, [3]).SetZone([C.dzDrop, C.dzNexus])  # 189
	TResourceDisplayIntegerProgressBarComponent.new().Create(Entity).ShowResource(C.reWelaCharge).SizeY(8.0)  # 193
	TStateDisplayStackComponent.new().Create(Entity)  # 197
	TStateDisplayComponent.new().Create(Entity).Texture("HUD/Unitbars/icon_out_of_ammo.png").CheckWelaIsReadyInGroup([11]).ReverseWelaIsReadyCheck()  # 198
	TWelaReadyCostComponent.new().CreateGrouped(Entity, [11]).SetPayingGroupForType(C.reWelaCharge, []).ValueGroup([1])  # 202
	TStateDisplayComponent.new().Create(Entity).Texture("HUD/Unitbars/icon_not_reloading.png").CheckWelaIsReadyInGroup([12])  # 206
	TWelaReadyEnemiesNearbyComponent.new().CreateGrouped(Entity, [12]).ValueGroup([1])  # 209
	TTextureRangeIndicatorComponent.new().CreateGrouped(Entity, [3]).HideInCaptureMode().DrawOnShowSpawnZone([C.dzDrop, C.dzNexus]).DrawCircle(0.5).SetTexture(C.PATH_GRAPHICS_EFFECTS_TEXTURES + "RangeLine.tga").ShowTeamColor().ShowWeaponRange().IsPermanent()  # 212
	TSoundComponent.new().CreateGrouped(Entity, [1], "event:/env/building/nexus/attack_fire").TriggerOnFire()  # 221
	TSoundComponent.new().CreateGrouped(Entity, [], "env/building/nexus/damaged").TriggerOnLoseHealth()  # 224
