# Generated by tools/transpile_scripts.py from Scripts\Units\Neutral\NexusLevel2.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")

var Game = null  # Units\Neutral\NexusLevel2.ets:3
var InheritsFrom: String = "Units\\Neutral\\Nexus.ets"  # Units\Neutral\NexusLevel2.ets:4

# Units\Neutral\NexusLevel2.ets:6
func CreateData(Entity) -> void:
	if Game.IsDuo() and Game.IsPvP():  # 10
		Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 2.0 * L.f([2750.0, 3600.0, 4000.0, 4000.0, 4000.0], Entity.CardLeague()))  # 12
		Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 2.0 * L.f([2750.0, 3600.0, 4000.0, 4000.0, 4000.0], Entity.CardLeague()))  # 13
	else:
		Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, L.f([2750.0, 3600.0, 4000.0, 4000.0, 4000.0], Entity.CardLeague()))  # 19
		Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, L.f([2750.0, 3600.0, 4000.0, 4000.0, 4000.0], Entity.CardLeague()))  # 20
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [1], "Projectiles\\Neutral\\NexusLevel2Projectile")  # 23
	if Entity.CardLeague() > 2:  # 25
		Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [4], "Units\\Neutral\\NexusLevel3")  # 26
	if Entity.CardLeague() > 2:  # 29
		TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [4], "NexusUpgrade")  # 30

# Units\Neutral\NexusLevel2.ets:34
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 36
	TMeshComponent.new().CreateGrouped(Entity, [0], "Units\\Neutral\\Nexus\\Nexus.xml").CreateNewAnimation(C.ANIMATION_SPAWN, 0, 20).CreateNewAnimation(C.ANIMATION_STAND, 20, 20).BindZoneToBone(C.BIND_ZONE_HIT_ZONE, "crystal_low").BoneOffset(C.BIND_ZONE_HIT_ZONE, 0.0, 2.5, 0.0).BindZoneToBone(C.BIND_ZONE_HIT_ZONE_AIR, "crystal_high").BoneOffset(C.BIND_ZONE_HIT_ZONE_AIR, 0.0, 4.0, 0.0).BoneOffset(C.BIND_ZONE_TOP, 0.0, 4.5, 0.0)  # 38
	TMeshComponent.new().CreateGrouped(Entity, [6], "Units\\Neutral\\Nexus\\NexusBaseUpgrade.xml").BindTextureToTeam(C.mtGlow, "NexusGlow.tga", 1).BindTextureToTeam(C.mtGlow, "NexusGlow2.tga", 2)  # 47
	TMeshComponent.new().CreateGrouped(Entity, [3], "Units\\Neutral\\Nexus\\NexusRunes.xml").CreateNewAnimation(C.ANIMATION_STAND, 0, 601).BindTextureToTeam(C.mtDiffuse, "NexusDiffuse.tga", 1).BindTextureToTeam(C.mtDiffuse, "NexusDiffuse2.tga", 2).BindTextureToTeam(C.mtGlow, "NexusGlow.tga", 1).BindTextureToTeam(C.mtGlow, "NexusGlow2.tga", 2)  # 51
	TMeshEffectComponent.new().CreateGrouped(Entity, [3, 6]).SetEffect(TMeshEffectSpawn.new().Create().OverrideColor(4283455832).OverrideColorIdentity(C.ecWhite))  # 58

# Units\Neutral\NexusLevel2.ets:67
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 69
