# Generated by tools/transpile_scripts.py from Scripts\Environment\AtmoWind.ets (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Environment\AtmoWind.ets:1
func CreateMeta(Entity) -> void:
	L.Assert(false, "Environmentobjects shouldn't created on server side!")  # 5

# Environment\AtmoWind.ets:12
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 14
