# Generated by tools/transpile_scripts.py from Scripts\Spells\Blue\EnergyRift.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\Blue\EnergyRift.dws:1
func Apply(Entity) -> void:
	var Group: int = 0  # 2
	var FireGroup: int = 0  # 2
	Group = Entity.ReserveFreeGroup()  # 4
	Entity.Blackboard.SetValue(C.eiCooldown, [Group], 30000)  # 5
	FireGroup = Entity.ReserveFreeGroup()  # 6
	Entity.Blackboard.SetValue(C.eiCooldown, [FireGroup], 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaDamage, [FireGroup], 24.0)  # 8
	Entity.Blackboard.SetValue(C.eiWelaRange, [FireGroup], 14.0)  # 9
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [FireGroup], "Projectiles\\Blue\\EnergyRiftProjectile")  # 10
	Entity.Blackboard.SetValue(C.eiDamageType, [FireGroup], [C.dtSpell])  # 11
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upHasEnergyRift])  # 34
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\Blue\\energy_rift_cast.pfx", 2.0).ActivateNow().BindToSubPositionGroup(C.BIND_ZONE_TOP, [0, 1]).SetModelOffset(0.0, 1.8, 0.0)  # 37
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\Blue\\energy_rift_buff.pfx", 2.0).Delay(200).ActivateNow().ActivateOnCreate().BindToSubPositionGroup(C.BIND_ZONE_TOP, [0, 1]).SetModelOffset(0.0, 1.8, 0.0)  # 42
	TCameraShakerComponent.new().CreateGrouped(Entity, []).Delay(300).PresetRotationLight().ActivateNow()  # 49
	TCameraShakerComponent.new().CreateGrouped(Entity, []).Delay(300).PresetVectorLight().ActivateNow()  # 54
	TSoundComponent.new().CreateGrouped(Entity, [FireGroup], "event:/card/blue/spell/energy_rift/attack_fire").TriggerOnFire()  # 59
