# Generated by tools/transpile_scripts.py from Scripts\Spells\Blue\FactoryReset.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\Blue\FactoryReset.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiWelaRange, [], 4.0)  # 5
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [], 8)  # 6

# Spells\Blue\FactoryReset.ets:9
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 11
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, []).MustHaveAny([C.upUnit, C.upBuilding]).MustNotHave([C.upLegendary, C.upBase, C.upSpellImmune])  # 13
	TTextureRangeIndicatorComponent.new().CreateGrouped(Entity, []).SetTexture("SpelltargetGround.png")  # 18
	TRangeIndicatorHighlightEntitiesComponent.new().CreateGrouped(Entity, [])  # 20

# Spells\Blue\FactoryReset.ets:24
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 26
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/card/blue/spell/factory_reset/cast").TriggerOnCreate()  # 60
	TMeshEffectComponent.new().CreateGrouped(Entity, []).TargetGroup([]).ApplyToFireTarget().ActivateOnFire().SetEffect(TMeshEffectTint.new().Create(300, 4284197375).Additive().AddKey(0, 0.0).AddKey(100, 1.0).AddKey(300, 0.0))  # 63
	TParticleEffectComponent.new().CreateGrouped(Entity, [], "\\Blue\\factory_reset_apply.pfx", 1.2).ClonesToTarget().ActivateOnFire().FixedOrientationDefault().ScaleWith(C.eiCollisionRadius).FixedHeightGround()  # 75
	TParticleEffectComponent.new().CreateGrouped(Entity, [], "\\Blue\\factory_reset_cast.pfx", 5.0).ActivateOnCreate().FixedOrientationDefault().ScaleWith(C.eiWelaRange).FixedHeightGround()  # 82
	TParticleEffectComponent.new().CreateGrouped(Entity, [], "\\Blue\\blue_border_wide_once.pfx", 5.0).ActivateOnCreate().FixedOrientationDefault().ScaleWith(C.eiWelaRange).FixedHeightGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 88
