# Generated by tools/transpile_scripts.py from Scripts\Spells\Blue\Relocate.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\Blue\Relocate.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 5.0)  # 5
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [0, 1], 6)  # 6
	Entity.Blackboard.SetValue(C.eiCooldown, [2], 2000)  # 8

# Spells\Blue\Relocate.ets:11
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 13
	TWelaTargetConstraintAlliesComponent.new().CreateGrouped(Entity, [10])  # 16
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [10]).MustHaveAny([C.upUnit, C.upBuilding]).MustNotHave([C.upBase, C.upSpellImmune])  # 17
	TWelaTargetConstraintUnitPropertyComponent.new().CreateGrouped(Entity, [11]).MustNotHave([C.upImmuneToRelocate])  # 22
	TWelaTargetConstraintBooleanComponent.new().CreateGrouped(Entity, [0]).GroupA([10]).GroupB([11]).OperatorAnd()  # 25
	TRangeIndicatorHighlightEntitiesComponent.new().CreateGrouped(Entity, [0]).Valid([10]).Invalid([11])  # 31

# Spells\Blue\Relocate.ets:37
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 39
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [0], "Spells\\Blue\\Relocate.dws").PassSavedTargetPosition(1).OverrideLastParameterGroup([]).PassOffsetToOwner()  # 60
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [0], "Modifiers\\Stopped.dws").PassIntValue(600)  # 65
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/card/blue/spell/relocate/cast").TriggerOnCreate()  # 69
	TSoundComponent.new().CreateGrouped(Entity, [0], "event:/card/blue/spell/relocate/cast_with_targets").TriggerOnFire()  # 72
	TParticleEffectComponent.new().CreateGrouped(Entity, [0], "\\Blue\\relocate_cast.pfx", 5.0).ActivateOnCreate().FixedOrientationDefault().ScaleWith(C.eiWelaRange).FixedHeightGround()  # 75
	TParticleEffectComponent.new().CreateGrouped(Entity, [1], "\\Blue\\relocate_cast_finish.pfx", 5.0).Delay(466).ActivateOnFire().ActivateAtFireTarget().FixedOrientationDefault().ScaleWith(C.eiWelaRange).FixedHeightGround()  # 81
	TParticleEffectComponent.new().CreateGrouped(Entity, [1], "\\Blue\\blue_border_wide_once.pfx", 5.0).Delay(500).ActivateOnFire().ActivateAtFireTarget().FixedOrientationDefault().ScaleWith(C.eiWelaRange).FixedHeightGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 89
	TParticleEffectComponent.new().CreateGrouped(Entity, [0], "\\Blue\\blue_border_wide_once.pfx", 5.0).ActivateOnCreate().FixedOrientationDefault().ScaleWith(C.eiWelaRange).FixedHeightGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 98
