# Generated by tools/transpile_scripts.py from Scripts\Spells\Blue\Relocate.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Spells\Blue\Relocate.dws:3
func Apply(Entity, Target: Vector2, Offset: Vector2) -> void:
	var Group: int = 0  # 4
	var BuildingGroup: int = 0  # 4
	var EffectGroup: int = 0  # 4
	var ReplenishGroup: int = 0  # 4
	var ImmuneGroup: int = 0  # 4
	EffectGroup = Entity.ReserveFreeGroup()  # 6
	Group = Entity.ReserveFreeGroup()  # 7
	BuildingGroup = Entity.ReserveFreeGroup()  # 8
	ReplenishGroup = Entity.ReserveFreeGroup()  # 9
	ImmuneGroup = Entity.ReserveFreeGroup()  # 10
	Entity.Blackboard.SetValue(C.eiCooldown, [Group], 500)  # 11
	Entity.Blackboard.SetValue(C.eiCooldown, [EffectGroup], 1500)  # 13
	Entity.Blackboard.SetIndexedValue(C.eiWelaDamage, [BuildingGroup], 1, 0.3)  # 15
	Entity.Blackboard.SetIndexedValue(C.eiWelaDamage, [BuildingGroup], 2, 0.25)  # 16
	Entity.Blackboard.SetIndexedValue(C.eiWelaDamage, [BuildingGroup], 3, 0.15)  # 17
	Entity.Blackboard.SetValue(C.eiDamageType, [BuildingGroup], [C.dtSpell, C.dtFlatHeal])  # 18
	TWelaHelperResolveComponent.new().CreateGrouped(Entity, [BuildingGroup]).ResolveTier()  # 20
	Entity.Blackboard.SetIndexedValue(C.eiWelaDamage, [ReplenishGroup], 1, 0.3)  # 23
	Entity.Blackboard.SetIndexedValue(C.eiWelaDamage, [ReplenishGroup], 2, 0.2)  # 24
	Entity.Blackboard.SetIndexedValue(C.eiWelaDamage, [ReplenishGroup], 3, 0.2)  # 25
	Entity.Blackboard.SetValue(C.eiDamageType, [ReplenishGroup], [C.dtSpell])  # 26
	TWelaHelperResolveComponent.new().CreateGrouped(Entity, [ReplenishGroup]).ResolveTier()  # 28
	Entity.Blackboard.SetValue(C.eiCooldown, [ImmuneGroup], 20000)  # 31
	TUnitPropertyComponent.new().CreateGrouped(Entity, [ImmuneGroup], [C.upImmuneToRelocate])  # 72
	TParticleEffectComponent.new().CreateGrouped(Entity, [ImmuneGroup], "\\Blue\\relocate_immune.pfx", 1.0).ActivateNow().ActivateOnCreate()  # 75
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\Blue\\relocate_apply.pfx", 1.1).ActivateNow()  # 79
	TMeshEffectGlow.new().Create(900).FixedColorIdentity(C.ecBlue).AddKey(0, 0.0).AddKey(450, 0.15).AddKey(500, 0.5).AddKey(600, 0.5).AddKey(900, 0.0).AssignToEntity(Entity)  # 82
	TVisualModificatorSizeComponent.new().CreateGrouped(Entity, [0, 1, 2, 3, 4, 5, 6, 7, 8, Group, EffectGroup]).Keypoints([1.0, 1.0, 1.1, 0.0, 1.1, 1.0]).TimeKeys([0, 300, 400, 500, 600, 700]).Duration(700)  # 91
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\Blue\\relocate_finish.pfx", 1.0).ActivateOnFire()  # 96
