# Generated by tools/transpile_scripts.py from Scripts\Scenarios\Mutators\HighlyExplosive.dws (SERVER).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Scenarios\Mutators\HighlyExplosive.dws:3
func Apply(Entity, Game) -> void:
	var EffectGroup: int = 0  # 4
	EffectGroup = Entity.ReserveFreeGroup()  # 6
	TAutoBrainUnitSpawnComponent.new().CreateGrouped(Entity, [EffectGroup])  # 9
	TWelaEffectInstantComponent.new().CreateGrouped(Entity, [EffectGroup])  # 10
	TWelaTargetConstraintTeamIDComponent.new().CreateGrouped(Entity, [EffectGroup]).SetTargetTeam(2)  # 11
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [EffectGroup], "Scenarios\\Mutators\\HighlyExplosiveBuff.dws")  # 15
