# Generated by tools/transpile_scripts.py from Scripts\Units\White\Footman.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 12
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapUnitIcon.png")  # 13

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TPathfindingComponent.new().Create(Entity)  # 45
	TOrienterMovementComponent.new().Create(Entity)  # 48
	TOrienterTargetComponent.new().CreateGrouped(Entity, [0, 1])  # 49
	TOrienterSmoothRotateComponent.new().Create(Entity).SetAngleSpeed(0.008)  # 50
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 53
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 54
	TShowOnMinimapComponent.new().Create(Entity)  # 56

# Units\White\Footman.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.55  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecWhite)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier1, C.upUnit, C.upMelee, C.upGround])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atMedium)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 32.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 32.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 1.0)  # 14 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtMelee])  # 15
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 13.0)  # 16 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 2000)  # 17 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 300)  # 18
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 800)  # 19
	Entity.Blackboard.SetValue(C.eiWelaDamage, [2], 10.0)  # 22
	Entity.Blackboard.SetValue(C.eiCooldown, [2], 5000)  # 23
	Entity.Blackboard.SetValue(C.eiWelaModifier, [2], 0.0)  # 24
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [2], "ShieldBlock").Keyword("Shieldblock").PassInteger("cooldown", 5)  # 27
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaAttack, 2)  # 31
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaDefense, 8)  # 32
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaUtility, 0)  # 33

# Units\White\Footman.ets:37
func CreateMeta(Entity) -> void:
	var MeshComponent = null  # 39
	CreateData(Entity)  # 42
	InitUnitMeta(Entity)  # 43
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(0, 0, 0), Vector3(0, 1.2, 0), 0.6)  # 46
	MeshComponent = TMeshComponent.new().CreateGrouped(Entity, [0, 1], ("Units\\White\\Footman" + Entity.SkinFileSuffix()) + "\\Footman.xml").ApplyLegacySizeFactor().IgnoreScalingForAnimations()  # 48
	if Entity.SkinID == C.SKIN_GROUP_WOODLANDS:  # 52
		MeshComponent.BindZoneToBone(C.BIND_ZONE_CENTER, "ForestKnightSpine4").BindZoneToBone(C.BIND_ZONE_WEAPON, "ForestKnightRPalm").BindZoneToBone(C.BIND_ZONE_HEAD, "ForestKnightHead").CreateNewAnimation(C.ANIMATION_STAND, 0, 57).CreateNewAnimation(C.ANIMATION_ATTACK, 58, 71).CreateNewAnimation(C.ANIMATION_WALK, 72, 112)  # 54
		TMeshEffectMetal.new().Create().AssignToEntity(Entity)  # 62
	elif Entity.SkinID == C.SKIN_GROUP_UNDERWORLD:  # 64
		MeshComponent.BindZoneToBone(C.BIND_ZONE_CENTER, "TormentedSoulSpine4").BindZoneToBone(C.BIND_ZONE_WEAPON, "TormentedSoulRPalm").BindZoneToBone(C.BIND_ZONE_HEAD, "TormentedSoulHead").CreateNewAnimation(C.ANIMATION_STAND, 0, 52).CreateNewAnimation(C.ANIMATION_ATTACK, 53, 71).CreateNewAnimation(C.ANIMATION_WALK, 72, 112)  # 66
	else:
		MeshComponent.BindZoneToBone(C.BIND_ZONE_CENTER, "FootmanSpine4").BindZoneToBone(C.BIND_ZONE_WEAPON, "FootmanRPalm").BindZoneToBone(C.BIND_ZONE_HEAD, "FootmanHead").BoneSwapXY(C.BIND_ZONE_CENTER).CreateNewAnimation(C.ANIMATION_STAND, 0, 56).CreateNewAnimation(C.ANIMATION_ATTACK, 58, 81).CreateNewAnimation(C.ANIMATION_WALK, 83, 122)  # 76
		TMeshEffectMetal.new().Create().AssignToEntity(Entity)  # 85
	TAnimationComponent.new().CreateGrouped(Entity, [0, 1])  # 88
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [1.0], [0])  # 89

# Units\White\Footman.ets:93
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 95
	InitUnitEntity(Entity)  # 96
	TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [2], true)  # 130
	TSoundComponent.new().CreateGrouped(Entity, [1], "event:/card/white/unit/footman/attack").TriggerOnPreFire().StopOnFree()  # 133
	TParticleEffectComponent.new().CreateGrouped(Entity, [2], "\\White\\shield_block.pfx", 1.7).ActivateOnCreate().ScaleWith(C.eiCollisionRadius).BindToSubPositionGroup(C.BIND_ZONE_CENTER, [0, 1]).VisibleWithWelaReady()  # 137
	TParticleEffectComponent.new().CreateGrouped(Entity, [2], "\\White\\footman_shield_block_trigger.pfx", 1.0).ActivateOnFire().IgnoreModelSize().BindToSubPositionGroup(C.BIND_ZONE_CENTER, [0, 1])  # 143
	TSoundComponent.new().CreateGrouped(Entity, [2], "event:/card/white/effect/shield_block").TriggerOnFire()  # 148
