# Generated by tools/transpile_scripts.py from Scripts\Units\White\Marksman.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\UnitTemplate.dws:3
func InitUnitData(Entity) -> void:
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udUsePathfinding, true)  # 5
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 22.0)  # 6
	Entity.Blackboard.SetValue(C.eiSpeed, [], float(4) / 1000)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [C.GROUP_SOUL], "Projectiles\\Black\\SoulGatherProjectileSpawner")  # 9
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 12
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapUnitIcon.png")  # 13

# HelperScripts\UnitTemplate.dws:17
func InitUnitMeta(Entity) -> void:
	pass

# HelperScripts\UnitTemplate.dws:22
func InitUnitEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 24
	TPathfindingComponent.new().Create(Entity)  # 45
	TOrienterMovementComponent.new().Create(Entity)  # 48
	TOrienterTargetComponent.new().CreateGrouped(Entity, [0, 1])  # 49
	TOrienterSmoothRotateComponent.new().Create(Entity).SetAngleSpeed(0.008)  # 50
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 53
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 54
	TShowOnMinimapComponent.new().Create(Entity)  # 56

# Units\White\Marksman.ets:3
func CreateData(Entity) -> void:
	InitUnitData(Entity)  # 5
	Entity.CollisionRadius = 0.45  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecWhite)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier2, C.upUnit, C.upGround, C.upRanged])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atUnarmored)  # 9 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 28.0)  # 10 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 28.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 13.5)  # 14 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [0, 1], "Projectiles\\White\\MarksmanProjectile")  # 15
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 5000)  # 16 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtRanged])  # 17
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 190.0)  # 18 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiWelaActionpoint, [1], 733)  # 19
	Entity.Blackboard.SetValue(C.eiWelaActionduration, [1], 1166)  # 20
	Entity.Blackboard.SetValue(C.eiWelaModifier, [2], 6.0)  # 23
	Entity.Blackboard.SetValue(C.eiCooldown, [2], 10000)  # 24
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "SteadyAim").PassString("range_increase", "+6", "range").PassInteger("duration", 10)  # 27
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [1], "BigGameHunter")  # 30
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaAttack, 10)  # 32
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaDefense, 0)  # 33
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaUtility, 0)  # 34

# Units\White\Marksman.ets:38
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 40
	InitUnitMeta(Entity)  # 41
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(0, 0, 0), Vector3(0, 1.2, 0), 0.6)  # 44
	TMeshComponent.new().CreateGrouped(Entity, [0, 1], ("Units\\White\\Marksman" + Entity.SkinFileSuffix()) + "\\Marksman.xml").ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_STAND, 56, 116).CreateNewAnimation(C.ANIMATION_WALK, 0, 20).CreateNewAnimation(C.ANIMATION_ATTACK, 21, 55).SetAnimationSpeed(C.ANIMATION_WALK, 0.91).BindZoneToBone(C.BIND_ZONE_CENTER, "MarksmanSpine4").BoneSwapXY(C.BIND_ZONE_CENTER).BindZoneToBone(C.BIND_ZONE_WEAPON, "MarksmanWeapon_muzzle").BoneSwapXZ(C.BIND_ZONE_WEAPON).BindZoneToBone(C.BIND_ZONE_WEAPON_MUZZLE, "MarksmanWeapon_muzzle").BoneSwapXZ(C.BIND_ZONE_WEAPON_MUZZLE).BindZoneToBone(C.BIND_ZONE_HEAD, "MarksmanHead")  # 46
	TMeshEffectMetal.new().Create().AssignToEntity(Entity)  # 59
	TAnimationComponent.new().CreateGrouped(Entity, [0, 1])  # 62
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [1.0], [0])  # 63

# Units\White\Marksman.ets:67
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 69
	InitUnitEntity(Entity)  # 70
	TModifierWelaRangeComponent.new().CreateGrouped(Entity, [1]).AddModifier().ScaleWithTime().ActivateOnStand().DeactivateOnMoveTo().SetValueGroup([2])  # 94
	TSoundComponent.new().CreateGrouped(Entity, [1], "event:/card/white/unit/marksman/attack_fire").TriggerOnFire().StopOnFree()  # 102
	TCameraShakerComponent.new().CreateGrouped(Entity, [1]).PresetRotationLight().ActivateOnFire()  # 106
	TCameraShakerComponent.new().CreateGrouped(Entity, [1]).PresetVectorLight().ActivateOnFire()  # 110
	TParticleEffectComponent.new().CreateGrouped(Entity, [1], "\\White\\marksman_muzzle_flash.pfx", 1.0).ActivateOnFire().BindToSubPosition(C.BIND_ZONE_WEAPON_MUZZLE)  # 114
