# Generated by tools/transpile_scripts.py from Scripts\Units\White\Suntower.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# HelperScripts\BuildingTemplate.dws:3
func InitBuildingData(Entity, LimitedLifeTime: bool = false) -> void:
	Entity.Blackboard.SetValue(C.eiAttentionrange, [0, 1, 2, 3, 4, 5], 12.0)  # 5
	if LimitedLifeTime:  # 8
		Entity.Blackboard.SetValue(C.eiCooldown, [C.GROUP_BUILDING_LIFETIME], 90000)  # 9
	Entity.Blackboard.SetValue(C.eiWelaRange, [C.GROUP_SOUL], 12.0)  # 11
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHasDeathEffect, true)  # 14
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udMinimapIcon, "MinimapBuildingIcon.png")  # 15
	if LimitedLifeTime:  # 17
		TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], "TimedLifeBuilding").PassInteger("duration", 90)  # 18

# HelperScripts\BuildingTemplate.dws:23
func InitBuildingMeta(Entity) -> void:
	pass

# HelperScripts\BuildingTemplate.dws:32
func InitBaseBuildingEntity(Entity) -> void:
	TCollisionComponent.new().Create(Entity)  # 34
	TPathfindingComponent.new().Create(Entity)  # 51

# HelperScripts\BuildingTemplate.dws:57
func InitBuildingEntity(Entity, LimitedLifeTime: bool = false) -> void:
	InitBaseBuildingEntity(Entity)  # 59
	if LimitedLifeTime:  # 71
		TWelaReadyCooldownComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME], false)  # 72
	TEntityDisplayWrapperComponent.new().Create(Entity)  # 75
	TResourceDisplayHealthComponent.new().Create(Entity).OrderValue(-1)  # 76
	TShowOnMinimapComponent.new().Create(Entity)  # 78
	TSoundComponent.new().CreateGrouped(Entity, [], "event:/env/building/shared/hit").TriggerOnLoseHealth()  # 79
	if LimitedLifeTime:  # 82
		TIndicatorCooldownCircleComponent.new().CreateGrouped(Entity, [C.GROUP_BUILDING_LIFETIME]).SetTexture(C.PATH_GRAPHICS_EFFECTS_TEXTURES + "ProgressCircle.tga").SetRadius(1.5).ScaleWith(C.eiCollisionRadius).SetThickness(0.1).SetLinearBlend().Color(1627389951).Invert()  # 84

# Units\White\Suntower.ets:3
func CreateData(Entity) -> void:
	InitBuildingData(Entity, true)  # 5
	Entity.CollisionRadius = 0.95  # 6
	Entity.Blackboard.SetValue(C.eiColorIdentity, [], C.ecWhite)  # 7
	Entity.Blackboard.SetValue(C.eiUnitProperties, [], [C.upTier2, C.upGround, C.upBuilding, C.upRanged])  # 8
	Entity.Blackboard.SetValue(C.eiArmorType, [], C.atFortified)  # 10 {@UBL_Armortype}
	Entity.Blackboard.SetIndexedValue(C.eiResourceCap, [], C.reHealth, 465.0)  # 11 {@UBL_Health}
	Entity.Blackboard.SetIndexedValue(C.eiResourceBalance, [], C.reHealth, 465.0)  # 12 {@UBL_Health}
	Entity.Blackboard.SetValue(C.eiWelaRange, [0, 1], 11.0)  # 15 {@UBL_Range}
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [0, 1], "Projectiles\\White\\SuntowerProjectile")  # 16
	Entity.Blackboard.SetValue(C.eiCooldown, [1], 2000)  # 17 {@UBL_Cooldown}
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtRanged])  # 18
	Entity.Blackboard.SetValue(C.eiWelaDamage, [1], 50.0)  # 19 {@UBL_Damage}
	Entity.Blackboard.SetValue(C.eiWelaRange, [2, 3], 5.5)  # 22
	Entity.Blackboard.SetValue(C.eiWelaTargetCount, [2, 3], 200)  # 23
	Entity.Blackboard.SetValue(C.eiLinkPattern, [2, 3], "Links\\HomelandAura")  # 24
	TTooltipUnitAbilityComponent.new().CreateGrouped(Entity, [2], "Homeland").Keyword("Rescued").Keyword("StateEffect")  # 27
	Entity.Blackboard.SetIndexedValue(C.eiUnitData, [], C.udHealthbarOffset, -1.4)  # 31
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaAttack, 3)  # 33
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaDefense, 7)  # 34
	Entity.Blackboard.SetIndexedValue(C.eiCardStats, [], C.reMetaUtility, 0)  # 35

# Units\White\Suntower.ets:39
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 41
	InitBuildingMeta(Entity)  # 42
	TClickCollisionComponent.new().Create(Entity).SetCapsule(Vector3(0, 0, 0), Vector3(0, 2.4, 0), 0.95)  # 45
	TMeshComponent.new().CreateGrouped(Entity, [0], "Units\\White\\Suntower\\Suntower.xml").ApplyLegacySizeFactor().CreateNewAnimation(C.ANIMATION_STAND, 0, 49).BoneOffset(C.BIND_ZONE_TOP, 0.0, 1.4, 0.0).BindZoneToBone(C.BIND_ZONE_HEAD, "head").BoneOffset(C.BIND_ZONE_HEAD, 0.0, 1.6, 0.0).BindZoneToBone(C.BIND_ZONE_WEAPON_MUZZLE, "Object499").SetModelOffset(0.0, 2.0, 0.0).FixedOrientationDefault()  # 47
	TMeshEffectMetal.new().Create().AssignToEntity(Entity)  # 57
	Entity.Eventbus.WriteGrouped(C.eiModelSize, [0.75], [0])  # 59
	TTextureRangeIndicatorComponent.new().CreateGrouped(Entity, [1]).SetTexture("SpelltargetShootingRange.png")  # 61
	TTextureRangeIndicatorComponent.new().CreateGrouped(Entity, [2]).SetTexture("SpelltargetGeneric.png")  # 63

# Units\White\Suntower.ets:68
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 70
	InitBuildingEntity(Entity, true)  # 71
	TParticleEffectComponent.new().CreateGrouped(Entity, [0], "\\White\\suntower_idle.pfx", 6.0).ActivateOnCreate().SetModelOffset(Vector3(0, 3.5, 0))  # 101
	TParticleEffectComponent.new().CreateGrouped(Entity, [1], "\\White\\suntower_attack.pfx", 2.0).ActivateOnFire().BindToSubPositionGroup(C.BIND_ZONE_WEAPON_MUZZLE, [0, 1])  # 105
	TParticleEffectComponent.new().CreateGrouped(Entity, [2], "\\White\\white_border_wide.pfx", 5.0).ActivateOnCreate().ScaleWith(C.eiWelaRange).FixedHeightGround().VisibleWithOption(C.coGameplayShowEffectRadius)  # 109
	TSoundComponent.new().CreateGrouped(Entity, [1], "event:/card/white/building/suntower/attack_fire").TriggerOnFire().StopOnFree()  # 115
