# Generated by tools/transpile_scripts.py from Scripts\Links\Befogged.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Links\Befogged.dws:3
func Apply(Entity):
	var Result: Array = []
	var Group: int = 0  # 4
	Group = Entity.ReserveFreeGroup()  # 6
	Entity.Blackboard.SetValue(C.eiWelaModifier, [Group], -3.0)  # 7
	TModifierWelaRangeComponent.new().CreateGrouped(Entity, [C.GROUP_APPROACH_MAINWEAPON, C.GROUP_MAINWEAPON, Group]).AddModifier()  # 12
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upBefogged, C.upHasStateEffect])  # 15
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\Shared\\Befogged.pfx", 0.5).ActivateNow().ActivateOnCreate().ScaleWith(C.eiCollisionRadius).BindToSubPositionGroup(C.BIND_ZONE_HEAD, [0, 1])  # 18
	Result = [Group]  # 25
	return Result
