# Generated by tools/transpile_scripts.py from Scripts\Links\CrystalPowerLink.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Links\CrystalPowerLink.ets:3
func CreateData(Entity) -> void:
	pass

# Links\CrystalPowerLink.ets:7
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 9

# Links\CrystalPowerLink.ets:15
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 17
	TWarheadLinkApplyScriptComponent.new().CreateGrouped(Entity, [], "Links\\CrystalPower.dws")  # 22
	TPositionerAttacherComponent.new().Create(Entity).AttachToSource().SetSubPosition(C.BIND_ZONE_WEAPON_MUZZLE)  # 25
	TLinkRayVisualizerComponent.new().Create(Entity).Texture("\\Units\\Colorless\\SmallCasterGolem\\CrystalPowerLink\\CrystalPowerLink.png").SetOpacity(0.2).SetWidth(L.RVariedSingle_Create(0.3, 0.05)).SetLength(L.RVariedSingle_Create(5, 1)).SetLongitudinalSpeed(L.RVariedSingle_Create(8.0, 0.5)).SetRaycount(1)  # 28
	TPositionerAttacherComponent.new().CreateGrouped(Entity, [1]).AttachToDestination().SetSubPosition(C.BIND_ZONE_WEAPON)  # 36
