# Generated by tools/transpile_scripts.py from Scripts\Links\Guarded.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Links\Guarded.dws:3
func Apply(Entity):
	var Result: Array = []
	var Group: int = 0  # 4
	Group = Entity.ReserveFreeGroup()  # 6
	Entity.Blackboard.SetValue(C.eiWelaDamage, [Group], 1.0)  # 7
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upGuarded])  # 24
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [Group], "Modifiers\\Invincibility.dws")  # 27
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [Group], "Modifiers\\ImmuneToGuarded.dws")  # 29
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\White\\guarded_buff.pfx", 1.5).ActivateNow().ActivateOnCreate().BindToSubPositionGroup(C.BIND_ZONE_CENTER, [0, 1])  # 32
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\White\\guarded_trigger.pfx", 1.2).ActivateOnFireWarhead()  # 36
	Result = [Group]  # 40
	return Result
