# Generated by tools/transpile_scripts.py from Scripts\Links\Homeland.dws (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Links\Homeland.dws:3
func Apply(Entity):
	var Result: Array = []
	var Group: int = 0  # 4
	Group = Entity.ReserveFreeGroup()  # 6
	Entity.Blackboard.SetValue(C.eiWelaDamage, [Group], 10.0)  # 7
	Entity.Blackboard.SetValue(C.eiWelaUnitPattern, [Group], "Projectiles\\White\\HomelandProjectile")  # 8
	TUnitPropertyComponent.new().CreateGrouped(Entity, [Group], [C.upRescued])  # 25
	TWarheadApplyScriptComponent.new().CreateGrouped(Entity, [Group], "Modifiers\\ImmuneToRescued.dws")  # 28
	TParticleEffectComponent.new().CreateGrouped(Entity, [Group], "\\White\\homeland_aura_buff.pfx", 0.6).ActivateNow().ActivateOnCreate().ScaleWith(C.eiCollisionRadius).FixedOrientationDefault()  # 41
	Result = [Group]  # 48
	return Result
