# Generated by tools/transpile_scripts.py from Scripts\Links\ProjectileReflectorAura.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Links\ProjectileReflectorAura.ets:3
func CreateData(Entity) -> void:
	pass

# Links\ProjectileReflectorAura.ets:7
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 9

# Links\ProjectileReflectorAura.ets:15
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 17
	TWarheadLinkApplyScriptComponent.new().CreateGrouped(Entity, [], "Links\\ProjectileReflector.dws")  # 22
	TPositionerAttacherComponent.new().Create(Entity).AttachToSource().SetSubPositionGroup(C.BIND_ZONE_WEAPON_MUZZLE, [1]).ApplyFront()  # 25
	TPositionerAttacherComponent.new().CreateGrouped(Entity, [2]).AttachToDestination().SetSubPosition(C.BIND_ZONE_HIT_ZONE)  # 30
	TLinkRayVisualizerComponent.new().Create(Entity).Texture("\\Units\\Blue\\Shielddrone\\ReflectorLink\\ReflectorLink.png").SetOpacity(0.1).SetStartWidth(0.1).SetLongitudinalSpeed(L.RVariedSingle_Create(3, 1.0)).SetRotationSpeed(L.RVariedSingle_Create(3, 0.5)).SetWidth(L.RVariedSingle_Create(0.3, 0.0)).SetLength(L.RVariedSingle_Create(1.5, 0.0)).SetEndposJitter(0.5).SetRaycount(5)  # 34
