# Generated by tools/transpile_scripts.py from Scripts\Links\VecraAura.ets (CLIENT).
# Do not edit: change the transpiler and regenerate.
extends RefCounted

const C = preload("res://src/runtime/dws/dws_const.gd")
const L = preload("res://src/runtime/dws/dws_lib.gd")


# Links\VecraAura.ets:3
func CreateData(Entity) -> void:
	Entity.Blackboard.SetValue(C.eiWelaDamage, [0], 12.0)  # 6
	Entity.Blackboard.SetValue(C.eiCooldown, [0], 1000)  # 7
	Entity.Blackboard.SetValue(C.eiDamageType, [0], [C.dtAbility])  # 8
	Entity.Blackboard.SetValue(C.eiWelaModifier, [1], 0.5)  # 10
	Entity.Blackboard.SetValue(C.eiDamageType, [1], [C.dtHoT])  # 11

# Links\VecraAura.ets:14
func CreateMeta(Entity) -> void:
	CreateData(Entity)  # 16

# Links\VecraAura.ets:22
func CreateEntity(Entity) -> void:
	CreateMeta(Entity)  # 24
	TPositionerAttacherComponent.new().Create(Entity).AttachToSource().SetSubPosition(C.BIND_ZONE_HIT_ZONE)  # 44
	TLinkRayVisualizerComponent.new().Create(Entity).Texture(("\\Units\\Black\\Vecra" + Entity.SkinFileSuffix()) + "\\FrostLink\\FrostLink.tga").SetOpacity(0.1).SetWidth(L.RVariedSingle_Create(0.3, 0.05)).SetLength(L.RVariedSingle_Create(5, 1)).SetLongitudinalSpeed(L.RVariedSingle_Create(-8.0, 0.5)).SetRaycount(1)  # 48
	TSoundComponent.new().CreateGrouped(Entity, [0], "event:/card/black/unit/vecra/monarch_of_frost").TriggerOnCreate().StopOnFree()  # 56
